const optionIds = ["a", "b", "c", "d"];

function q({ id, topic, prompt, answers, correct, explanation }) {
  return {
    id,
    topic,
    prompt,
    options: answers.map((text, index) => ({ id: optionIds[index], text })),
    correctId: optionIds[correct],
    explanation,
  };
}

export const questions = [
  q({
    id: "metode-1",
    topic: "Metode razvoja",
    prompt: "Sto najbolje opisuje metode razvoja softvera?",
    answers: [
      "Organizacijski pristupi prema kojima se planira, razvija i kontrolira rad na softveru.",
      "Skup programskih jezika i biblioteka kojima se implementira sustav.",
      "Tehnike testiranja kojima se provjerava samo zavrsna verzija proizvoda.",
      "Dokumenti koji opisuju arhitekturu, kod i korisnicke upute.",
    ],
    correct: 0,
    explanation: "Metode razvoja govore kako se organizira rad na softverskom projektu.",
  }),
  q({
    id: "metode-2",
    topic: "Metode razvoja",
    prompt: "Koja tvrdnja najbolje objasnjava zasto se ne razvija svaki softver isto?",
    answers: [
      "Zato sto izbor pristupa ovisi o proizvodu, korisnicima, timu i nacinu rada.",
      "Zato sto se za svaki softver mora koristiti drukciji programski jezik.",
      "Zato sto svaka metoda razvoja potpuno zabranjuje dokumentaciju.",
      "Zato sto je testiranje uvijek vaznije od planiranja i dizajna sustava.",
    ],
    correct: 0,
    explanation: "Metoda se bira prema kontekstu projekta, a ne postoji jedan univerzalan pristup.",
  }),
  q({
    id: "metode-3",
    topic: "Metode razvoja",
    prompt: "Koji je cilj metode razvoja softvera?",
    answers: [
      "Uciniti razvoj uredjenim, ucinkovitim i predvidivim.",
      "Ukloniti potrebu za komunikacijom s korisnikom.",
      "Osigurati da se kod pise prije definiranja zahtjeva.",
      "Zamijeniti testiranje detaljnom dokumentacijom.",
    ],
    correct: 0,
    explanation: "U biljeskama je cilj metoda razvoja uredjen, ucinkovit i predvidiv razvoj.",
  }),
  q({
    id: "metode-4",
    topic: "Metode razvoja",
    prompt: "Koja recenica najbolje opisuje svrhu predmeta iz biljeski?",
    answers: [
      "Nauciti kako se softver planira, razvija, testira, dokumentira i modelira u praksi.",
      "Nauciti iskljucivo sintaksu programskih jezika potrebnih za implementaciju sustava.",
      "Nauciti samo generirati dokumentaciju iz komentara u izvornom kodu.",
      "Nauciti samo razlike izmedju Scrum i Kanban sastanaka.",
    ],
    correct: 0,
    explanation: "Svrha predmeta je shvatiti prakticni proces nastanka softvera i informacijskih sustava.",
  }),
  q({
    id: "waterfall-1",
    topic: "Vodopad",
    prompt: "Koja tvrdnja najtocnije opisuje metodu vodopada?",
    answers: [
      "Linearan i sekvencijalan model u kojem se faze izvode jedna nakon druge.",
      "Iterativan okvir s kratkim sprintovima i stalnim promjenama prioriteta.",
      "Metoda neprekidne isporuke bez definiranog redoslijeda faza.",
      "Tehnika dokumentiranja koda iz komentara u izvornim datotekama.",
    ],
    correct: 0,
    explanation: "Vodopad je linearan i sekvencijalan model razvoja.",
  }),
  q({
    id: "waterfall-1a",
    topic: "Vodopad",
    prompt: "Koja tvrdnja o nastanku metode vodopada odgovara biljeskama?",
    answers: [
      "Rijec je o jednoj od najstarijih metoda, povezanoj s Winstonom W. Royceom i 1970. godinom.",
      "Nastala je 2001. kao dio Agilnog manifesta.",
      "Prvi put se spominje 1986. u clanku o timskom radu i ragbiju.",
      "Razvila ju je Toyota 1940-ih u sklopu proizvodnje upravo na vrijeme.",
    ],
    correct: 0,
    explanation: "Biljeske navode da je metoda vodopada najstarija metoda i povezuju je s Royceom 1970.",
  }),
  q({
    id: "waterfall-2",
    topic: "Vodopad",
    prompt: "Sto znaci da je vodopad sekvencijalan?",
    answers: [
      "Da svaka faza slijedi nakon prethodne i ne preskace se redoslijed.",
      "Da se sve faze izvode paralelno kako bi se ubrzao razvoj.",
      "Da se zahtjevi definiraju tek nakon implementacije.",
      "Da korisnik sam odlucuje kada se prelazi u iducu fazu bez tima.",
    ],
    correct: 0,
    explanation: "Sekvencijalnost znaci rad po unaprijed odredjenom slijedu.",
  }),
  q({
    id: "waterfall-3",
    topic: "Vodopad",
    prompt: "Za kakve projekte je metoda vodopada najprikladnija?",
    answers: [
      "Za projekte s jasnim i stabilnim zahtjevima koji se ne mijenjaju cesto.",
      "Za projekte u kojima korisnik svaki dan mijenja prioritete i opseg.",
      "Za projekte bez dokumentacije i bez definirane arhitekture.",
      "Za projekte u kojima se proizvod isporucuje nakon svakog dnevnog sastanka.",
    ],
    correct: 0,
    explanation: "Vodopad bolje funkcionira kada su zahtjevi unaprijed poznati i stabilni.",
  }),
  q({
    id: "waterfall-4",
    topic: "Vodopad",
    prompt: "Koliko faza ima metoda vodopada prema biljeskama?",
    answers: ["6", "4", "5", "7"],
    correct: 0,
    explanation: "Biljeske navode sest faza metode vodopada.",
  }),
  q({
    id: "waterfall-5",
    topic: "Vodopad",
    prompt: "Koji je tocan redoslijed prvih triju faza metode vodopada?",
    answers: [
      "Analiza zahtjeva, dizajn sustava, implementacija i testiranje jedinica.",
      "Dizajn sustava, analiza zahtjeva, integracija i testiranje sustava.",
      "Implementacija, analiza zahtjeva, pustanje u pogon.",
      "Analiza zahtjeva, integracija sustava, dizajn sustava.",
    ],
    correct: 0,
    explanation: "Vodopad prvo definira sto sustav treba raditi, zatim kako ce biti strukturiran, pa prelazi u kod.",
  }),
  q({
    id: "waterfall-6",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara analiza zahtjeva?",
    answers: [
      "Sto sustav treba raditi?",
      "Kako ce se moduli spojiti u cjelinu?",
      "Je li sustav spreman za stvarnu uporabu?",
      "Kako se preostali posao smanjuje kroz vrijeme?",
    ],
    correct: 0,
    explanation: "Analiza zahtjeva definira potrebe, zahtjeve i funkcionalnosti sustava.",
  }),
  q({
    id: "waterfall-7",
    topic: "Vodopad",
    prompt: "Tko sudjeluje u fazi analize zahtjeva?",
    answers: [
      "Narucitelj softvera i razvojni tim.",
      "Samo razvojni tim bez narucitelja.",
      "Samo krajnji korisnici nakon isporuke.",
      "Scrum Master i predstavnici vise Scrum timova.",
    ],
    correct: 0,
    explanation: "U analizi zahtjeva sudjeluju narucitelj i razvojni tim kako bi se razumio problem.",
  }),
  q({
    id: "waterfall-8",
    topic: "Vodopad",
    prompt: "Koji je rezultat faze analize zahtjeva?",
    answers: [
      "Dokument sa zahtjevima.",
      "Arhitektura sustava.",
      "Skup testiranih modula.",
      "Burn-down grafikon.",
    ],
    correct: 0,
    explanation: "Dokument sa zahtjevima je osnova za daljnji razvoj.",
  }),
  q({
    id: "waterfall-9",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara dizajn sustava?",
    answers: [
      "Kako ce sustav biti strukturiran i izveden?",
      "Koje su greske ostale nakon isporuke?",
      "Sto je sljedece najvaznije za izraditi?",
      "Koji clan tima preuzima koji zadatak u sprintu?",
    ],
    correct: 0,
    explanation: "Dizajn sustava pretvara zahtjeve u strukturu pogodnu za implementaciju.",
  }),
  q({
    id: "waterfall-10",
    topic: "Vodopad",
    prompt: "Sto je rezultat faze dizajna sustava?",
    answers: [
      "Arhitektura sustava.",
      "Dokument sa zahtjevima.",
      "Popis testova koji su neuspjeli.",
      "Korisnicka dokumentacija.",
    ],
    correct: 0,
    explanation: "U PDF-u je rezultat faze dizajna sustava arhitektura sustava.",
  }),
  q({
    id: "waterfall-11",
    topic: "Vodopad",
    prompt: "Kako treba razumjeti hardverske komponente u dizajnu sustava?",
    answers: [
      "Kao tehnicku osnovu na kojoj sustav radi, ako je relevantna za taj projekt.",
      "Kao obavezne fizicke dijelove bez kojih softver ne moze postojati.",
      "Kao graficke elemente korisnickog sucelja koje treba dizajnirati.",
      "Kao Scrum artefakte koji opisuju stanje zadataka.",
    ],
    correct: 0,
    explanation: "Ako hardver nije bitan za projekt, fokus dizajna ostaje na strukturi i arhitekturi softvera.",
  }),
  q({
    id: "waterfall-12",
    topic: "Vodopad",
    prompt: "Sto se dogadja u fazi implementacije i testiranja jedinica?",
    answers: [
      "Plan sustava prelazi u programski kod, a jedinice se zasebno testiraju.",
      "Sustav se isporucuje narucitelju nakon pozitivnog testiranja.",
      "Moduli se povezuju i testira se samo cijeli sustav.",
      "Definiraju se korisnicke price i poslovna pravila.",
    ],
    correct: 0,
    explanation: "U toj fazi sustav se razvija po manjim cjelinama i svaka se provjerava zasebno.",
  }),
  q({
    id: "waterfall-13",
    topic: "Vodopad",
    prompt: "Koji je krajnji rezultat implementacije i testiranja jedinica?",
    answers: [
      "Skup modula koji su testirani kao jedinice.",
      "Prilagodjeni Product Backlog.",
      "Arhitektura sustava i hardverski zahtjevi.",
      "Korisnicke upute za krajnje korisnike.",
    ],
    correct: 0,
    explanation: "PDF navodi da je rezultat te faze skup testiranih modula.",
  }),
  q({
    id: "waterfall-14",
    topic: "Vodopad",
    prompt: "Sto je cilj integracije i testiranja sustava?",
    answers: [
      "Provjeriti rade li jedinice zajedno kao cjelovit sustav.",
      "Odrediti dugorocnu viziju proizvoda.",
      "Napisati dokument zahtjeva prije pocetka razvoja.",
      "Ograniciti WIP na Kanban ploci.",
    ],
    correct: 0,
    explanation: "Moduli se povezuju u sustav i testira se cjelina.",
  }),
  q({
    id: "waterfall-15",
    topic: "Vodopad",
    prompt: "Sto znaci da je integracija inkrementalna?",
    answers: [
      "Da se provodi u vise koraka, postupnim povezivanjem dijelova.",
      "Da se cijeli sustav spaja odjednom bez medjukoraka.",
      "Da se proizvod isporucuje svaki dan nakon Daily Scruma.",
      "Da se zahtjevi mijenjaju nakon svake korisnicke price.",
    ],
    correct: 0,
    explanation: "Inkrementalna integracija znaci povezivanje u postupnim koracima.",
  }),
  q({
    id: "waterfall-16",
    topic: "Vodopad",
    prompt: "Kada se provodi pustanje u pogon?",
    answers: [
      "Nakon sto su rezultati testiranja pozitivni.",
      "Prije analize zahtjeva ako korisnik trazi prototip.",
      "Prije integracije modula kako bi se ubrzao projekt.",
      "Tijekom svakog Product Backlog Refinementa.",
    ],
    correct: 0,
    explanation: "Pustanje u pogon dolazi nakon uspjesnog testiranja.",
  }),
  q({
    id: "waterfall-17",
    topic: "Vodopad",
    prompt: "Koja faza pocinje nakon sto je sustav pusten u uporabu?",
    answers: [
      "Odrzavanje.",
      "Dizajn sustava.",
      "Analiza zahtjeva.",
      "Sprint Planning.",
    ],
    correct: 0,
    explanation: "Odrzavanje pocinje nakon isporuke ili pustanja sustava u uporabu.",
  }),
  q({
    id: "waterfall-18",
    topic: "Vodopad",
    prompt: "Koja vrsta odrzavanja znaci dodavanje i poboljsavanje funkcionalnosti?",
    answers: [
      "Usavrsavanje.",
      "Korektivno odrzavanje.",
      "Adaptivno odrzavanje.",
      "Preventivno odrzavanje.",
    ],
    correct: 0,
    explanation: "Usavrsavanje se odnosi na nadogradnju funkcionalnosti i nove verzije.",
  }),
  q({
    id: "waterfall-19",
    topic: "Vodopad",
    prompt: "Koja vrsta odrzavanja se odnosi na ispravljanje gresaka koje nisu ranije otkrivene?",
    answers: [
      "Korektivno odrzavanje.",
      "Preventivno odrzavanje.",
      "Adaptivno odrzavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Korektivno odrzavanje ispravlja greske i nedostatke.",
  }),
  q({
    id: "waterfall-20",
    topic: "Vodopad",
    prompt: "Koja vrsta odrzavanja sluzi sprjecavanju predvidivih buducih gresaka?",
    answers: [
      "Preventivno odrzavanje.",
      "Korektivno odrzavanje.",
      "Adaptivno odrzavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Preventivno odrzavanje pokusava sprijeciti probleme prije nego nastanu.",
  }),
  q({
    id: "waterfall-21",
    topic: "Vodopad",
    prompt: "Koja je prednost metode vodopada?",
    answers: [
      "Faze su jasno definirane i lako ih je pratiti.",
      "Promjene zahtjeva se uvode bez troska u bilo kojoj fazi.",
      "Testiranje je kontinuirano tijekom cijelog razvoja.",
      "Nema potrebe za dokumentacijom jer je tim samoorganiziran.",
    ],
    correct: 0,
    explanation: "Jedna od prednosti vodopada je preglednost i jasno definirane faze.",
  }),
  q({
    id: "waterfall-22",
    topic: "Vodopad",
    prompt: "Koji je vazan nedostatak metode vodopada?",
    answers: [
      "Promjene je tesko uvoditi kada projekt odmakne.",
      "Zahtjevi su potpuno nevidljivi do kraja projekta.",
      "Metoda nema redoslijed faza.",
      "Testiranje pocinje prije definiranja zahtjeva.",
    ],
    correct: 0,
    explanation: "Vodopad je slabije prilagodljiv promjenama.",
  }),
  q({
    id: "waterfall-23",
    topic: "Vodopad",
    prompt: "Zasto vodopad nije prikladan za kompleksne i dugotrajne projekte?",
    answers: [
      "Zato sto je slabo fleksibilan i tesko prihvaca naknadne promjene zahtjeva.",
      "Zato sto nema definirane faze pa se razvoj ne moze pratiti.",
      "Zato sto ne koristi nikakvu dokumentaciju tijekom razvoja.",
      "Zato sto zahtijeva da se proizvod isporucuje nakon svakog dnevnog sastanka.",
    ],
    correct: 0,
    explanation: "Kod dugih i kompleksnih projekata zahtjevi se cesce mijenjaju, a vodopad na to slabo reagira.",
  }),
  q({
    id: "agile-1",
    topic: "Agilne metode",
    prompt: "Sto najbolje opisuje agilne metode?",
    answers: [
      "Fleksibilan i iterativan pristup koji naglasava korisnika, suradnju i prilagodbu.",
      "Linearan pristup u kojem se promjene zahtjeva izbjegavaju nakon pocetka razvoja.",
      "Skup alata za automatsko generiranje dokumentacije iz komentara u kodu.",
      "Metoda odrzavanja kojom se sprjecavaju buduce greske.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika, fleksibilnost i ceste prilagodbe.",
  }),
  q({
    id: "agile-2",
    topic: "Agilne metode",
    prompt: "Zasto agilne metode omogucuju ranije otkrivanje gresaka?",
    answers: [
      "Zbog cestih provjera, testiranja i prilagodbi tijekom razvoja.",
      "Zato sto se testiranje radi tek nakon pustanja u pogon.",
      "Zato sto korisnik nije ukljucen dok proizvod nije gotov.",
      "Zato sto se dokumentacija pise umjesto testiranja.",
    ],
    correct: 0,
    explanation: "Cesta testiranja i povratne informacije smanjuju rizik kasnog otkrivanja problema.",
  }),
  q({
    id: "agile-3",
    topic: "Agilne metode",
    prompt: "Sto je Agilni manifest?",
    answers: [
      "Skup temeljnih vrijednosti i principa na kojima se temelji agilni razvoj.",
      "Popis svih zadataka koje razvojni tim planira izvrsiti u sprintu.",
      "Grafikon koji prikazuje smanjenje preostalog posla kroz vrijeme.",
      "Dokument koji opisuje hardverske komponente sustava.",
    ],
    correct: 0,
    explanation: "Agilni manifest daje osnovni nacin razmisljanja za agilni razvoj.",
  }),
  q({
    id: "agile-4",
    topic: "Agilne metode",
    prompt: "Koja vrijednost pripada Agilnom manifestu?",
    answers: [
      "Pojedinci i interakcija vazniji su od procesa i alata.",
      "Procesi i alati vazniji su od komunikacije u timu.",
      "Opsezna dokumentacija vaznija je od funkcionalnog softvera.",
      "Unaprijed zadani plan vazniji je od odgovora na promjene.",
    ],
    correct: 0,
    explanation: "Manifest daje prednost ljudima i komunikaciji nad procesima i alatima.",
  }),
  q({
    id: "agile-5",
    topic: "Agilne metode",
    prompt: "Sto Agilni manifest stavlja ispred opsezne dokumentacije?",
    answers: [
      "Funkcionalan softver.",
      "Formalni ugovor.",
      "Plan testiranja.",
      "Arhitekturu sustava.",
    ],
    correct: 0,
    explanation: "Jedna od vrijednosti manifesta je funkcionalan softver ispred opsezne dokumentacije.",
  }),
  q({
    id: "agile-6",
    topic: "Agilne metode",
    prompt: "Koji je odnos agilnih metoda prema promjenama?",
    answers: [
      "Promjene se prihvacaju i na njih se nastoji brzo reagirati.",
      "Promjene se blokiraju nakon analize zahtjeva.",
      "Promjene su dopustene samo nakon pustanja u pogon.",
      "Promjene su zamjena za testiranje i dokumentaciju.",
    ],
    correct: 0,
    explanation: "Agilni pristup daje prednost odgovoru na promjene pred krutim pracenjem plana.",
  }),
  q({
    id: "agile-7",
    topic: "Agilne metode",
    prompt: "Kada je nastao Agilni manifest prema biljeskama?",
    answers: [
      "2001. godine.",
      "1970. godine.",
      "1986. godine.",
      "1940-ih godina.",
    ],
    correct: 0,
    explanation: "Biljeske navode 2001. godinu kao nastanak Agilnog manifesta.",
  }),
  q({
    id: "agile-8",
    topic: "Agilne metode",
    prompt: "Koja je uloga korisnika u agilnom razvoju prema biljeskama?",
    answers: [
      "Korisnik je ukljucen tijekom cijelog razvojnog ciklusa.",
      "Korisnik se ukljucuje tek nakon pustanja proizvoda u pogon.",
      "Korisnik smije dati zahtjeve samo prije pocetka dizajna sustava.",
      "Korisnik sudjeluje samo u pisanju dokumentacije koda.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika i stalnu suradnju s njim.",
  }),
  q({
    id: "scrum-1",
    topic: "Scrum",
    prompt: "Sto je Scrum?",
    answers: [
      "Razvojni okvir za rjesavanje slozenih i dinamicnih problema.",
      "Tehnika testiranja jedinica u metodi vodopada.",
      "Generator dokumentacije za programski jezik Java.",
      "Metoda bez uloga, dogadjaja, artefakata i pravila.",
    ],
    correct: 0,
    explanation: "Scrum je razvojni okvir, a ne samo tehnika ili postupak.",
  }),
  q({
    id: "scrum-2",
    topic: "Scrum",
    prompt: "Koja tvrdnja o nazivu Scrum je tocna?",
    answers: [
      "Naziv dolazi iz ragbija i naglasava timski rad.",
      "Naziv je kratica za softverski ciklus upravljanja rizikom.",
      "Naziv oznacava dokumentaciju procesa u agilnim projektima.",
      "Naziv se prvi put javlja kao Java alat za dokumentaciju.",
    ],
    correct: 0,
    explanation: "U biljeskama Scrum dolazi iz ragbija i naglasava timski rad.",
  }),
  q({
    id: "scrum-2a",
    topic: "Scrum",
    prompt: "Kada se Scrum prvi put spominje prema biljeskama?",
    answers: [
      "1986. godine.",
      "1970. godine.",
      "2001. godine.",
      "1997. godine.",
    ],
    correct: 0,
    explanation: "Biljeske navode 1986. godinu i clanak The New New Product Development Game.",
  }),
  q({
    id: "scrum-3",
    topic: "Scrum",
    prompt: "Od cega se Scrum sastoji?",
    answers: [
      "Od uloga, dogadjaja, artefakata i pravila.",
      "Od faza analize, dizajna, implementacije i odrzavanja.",
      "Od Kanban kartica, Kanban stupaca i WIP ogranicenja.",
      "Od dokumenta zahtjeva, plana testiranja i JavaDoc tagova.",
    ],
    correct: 0,
    explanation: "Biljeske navode cetiri osnovna dijela Scruma: uloge, dogadjaji, artefakti i pravila.",
  }),
  q({
    id: "scrum-4",
    topic: "Scrum",
    prompt: "Kakav je Scrum tim prema biljeskama?",
    answers: [
      "Mali, samostalan, fleksibilan i prilagodljiv.",
      "Velik, hijerarhijski i strogo specijaliziran.",
      "Bez odgovornosti i bez definiranih uloga.",
      "Sastavljen iskljucivo od krajnjih korisnika.",
    ],
    correct: 0,
    explanation: "Bit Scruma je u malom timu koji moze samostalno raditi i prilagodjavati se.",
  }),
  q({
    id: "scrum-4a",
    topic: "Scrum",
    prompt: "Sto znaci da Scrum koristi preklapajuci model rada?",
    answers: [
      "Da se kroz cijeli tok projekta pomalo radi na vise stvari.",
      "Da se faze moraju strogo zavrsavati jedna prije druge.",
      "Da se svi zadaci rade tek nakon potpunog zavrsetka dokumentacije.",
      "Da se proizvod isporucuje samo nakon zavrsne integracije sustava.",
    ],
    correct: 0,
    explanation: "Biljeske opisuju Scrum kao model u kojem se kroz tok razvoja radi pomalo na vise stvari.",
  }),
  q({
    id: "scrum-4b",
    topic: "Scrum",
    prompt: "Koja tvrdnja najbolje opisuje tezinu Scruma prema biljeskama?",
    answers: [
      "Jednostavan je za razumjeti, ali tezak za savladati.",
      "Tezak je za razumjeti, ali ne zahtijeva praksu.",
      "Jednostavan je zato sto nema uloge, dogadjaje ni pravila.",
      "Tezak je iskljucivo zbog potrebe za hardverskim komponentama.",
    ],
    correct: 0,
    explanation: "Scrum ima jednostavnu osnovnu strukturu, ali kvalitetna primjena nije trivijalna.",
  }),
  q({
    id: "scrum-5",
    topic: "Scrum uloge",
    prompt: "Koje su tri uloge u Scrum timu?",
    answers: [
      "Scrum Master, vlasnik proizvoda i razvojni tim.",
      "Tester, arhitekt i sistemski administrator.",
      "Vlasnik proizvoda, krajnji korisnik i dokumentarist.",
      "Projektni sponzor, voditelj prodaje i analiticar trzista.",
    ],
    correct: 0,
    explanation: "Scrum Team cine Scrum Master, vlasnik proizvoda i razvojni tim.",
  }),
  q({
    id: "scrum-6",
    topic: "Scrum uloge",
    prompt: "Koja je glavna uloga Scrum Mastera?",
    answers: [
      "Osigurati pravilno i neometano odvijanje Scrum procesa.",
      "Odrediti poslovnu viziju i redoslijed svih stavki proizvoda.",
      "Samostalno napisati sav kod i testirati sve jedinice.",
      "Odobriti pustanje proizvoda na trziste umjesto vlasnika proizvoda.",
    ],
    correct: 0,
    explanation: "Scrum Master vodi proces, uklanja prepreke i pomaze timu.",
  }),
  q({
    id: "scrum-6a",
    topic: "Scrum uloge",
    prompt: "Koja aktivnost pripada Scrum Masteru prema biljeskama?",
    answers: [
      "Prati napredak tima i cini ga vidljivim svima ukljucenima u projekt.",
      "Samostalno odredjuje poslovne zahtjeve i redoslijed implementacije.",
      "Donosi zavrsnu odluku zadovoljava li proizvod potrebnu kvalitetu.",
      "Pise korisnicku dokumentaciju namijenjenu krajnjim korisnicima.",
    ],
    correct: 0,
    explanation: "Scrum Master brine o procesu, produktivnosti, uklanjanju prepreka i vidljivosti napretka.",
  }),
  q({
    id: "scrum-7",
    topic: "Scrum uloge",
    prompt: "Sto radi vlasnik proizvoda?",
    answers: [
      "Odredjuje zahtjeve, kljucne znacajke i redoslijed implementacije.",
      "Brine se da dnevni sastanak traje tocno 15 minuta.",
      "Odredjuje WIP ogranicenja na Kanban ploci.",
      "Generira HTML dokumentaciju iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovara za viziju, zahtjeve i prioritete proizvoda.",
  }),
  q({
    id: "scrum-7a",
    topic: "Scrum uloge",
    prompt: "Koja odluka pripada vlasniku proizvoda?",
    answers: [
      "Kada nastaviti razvoj, a kada proizvod pustiti na trziste.",
      "Kako ce razvojni tim tehnicki podijeliti posao na manje zadatke.",
      "Koji ce predstavnik ici na Scrum of Scrums sastanak.",
      "Kako ce se generirati JavaDoc dokumentacija iz komentara.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovoran je za viziju i odluke o razvoju i pustanju proizvoda.",
  }),
  q({
    id: "scrum-8",
    topic: "Scrum uloge",
    prompt: "Koja tvrdnja najbolje opisuje razvojni tim u Scrumu?",
    answers: [
      "Samostalno odlucuje kako podijeliti posao na manje zadatke.",
      "Ceka da vlasnik proizvoda detaljno dodijeli svaki zadatak svakom clanu.",
      "Sudjeluje samo u dokumentiranju zavrsenog proizvoda.",
      "Sastoji se od predstavnika vise Scrum timova.",
    ],
    correct: 0,
    explanation: "Razvojni tim je samoorganizirajuci i odlucuje kako ce razraditi posao.",
  }),
  q({
    id: "scrum-9",
    topic: "Scrum uloge",
    prompt: "Koja je preporucena velicina Scrum razvojnog tima?",
    answers: [
      "Od 3 do 9 clanova, cesto oko 7.",
      "Od 1 do 2 clana, kako bi komunikacija bila minimalna.",
      "Najmanje 20 clanova zbog raspodjele specijalizacija.",
      "Tocno 15 clanova, jer Daily Scrum traje 15 minuta.",
    ],
    correct: 0,
    explanation: "Prevelik tim otezava komunikaciju, a premalen moze smanjiti produktivnost.",
  }),
  q({
    id: "scrum-artifacts-1",
    topic: "Scrum artefakti",
    prompt: "Sto su Scrum artefakti u kontekstu biljeski?",
    answers: [
      "Konkretni radni elementi koji omogucuju transparentnost, uvid i prilagodbu.",
      "Formalne uloge koje odredjuju tko vodi projekt i tko pise kod.",
      "Sastanci koji se odrzavaju na pocetku i kraju svakog sprinta.",
      "Vrste odrzavanja nakon pustanja softvera u pogon.",
    ],
    correct: 0,
    explanation: "Artefakti su elementi poput Product Backloga, Sprint Backloga, inkrementa i grafikona.",
  }),
  q({
    id: "scrum-artifacts-1a",
    topic: "Scrum artefakti",
    prompt: "Zasto su Scrum artefakti dinamicki?",
    answers: [
      "Zato sto se mogu mijenjati kada se promijene zahtjevi, trziste ili tehnologija.",
      "Zato sto uvijek ostaju isti od pocetka do kraja projekta.",
      "Zato sto ih moze mijenjati samo Scrum Master tijekom Daily Scruma.",
      "Zato sto sluze iskljucivo za arhiviranje zavrsenog proizvoda.",
    ],
    correct: 0,
    explanation: "Artefakti prate stvarno stanje rada i mijenjaju se kako se mijenja kontekst projekta.",
  }),
  q({
    id: "scrum-artifacts-2",
    topic: "Scrum artefakti",
    prompt: "Sto definira vizija proizvoda?",
    answers: [
      "Dugorocni cilj proizvoda ili projekta.",
      "Dnevni plan rada razvojnog tima.",
      "Popis gresaka nakon integracijskog testiranja.",
      "Maksimalan broj zadataka u WIP stupcu.",
    ],
    correct: 0,
    explanation: "Vizija proizvoda treba biti jasna, kratka i precizna.",
  }),
  q({
    id: "scrum-artifacts-2a",
    topic: "Scrum artefakti",
    prompt: "Sto je cilj ciklusa u Scrumu?",
    answers: [
      "Cilj koji se treba postici tijekom jednog sprinta implementacijom odabranih stavki.",
      "Dugorocna poslovna vizija cijelog proizvoda za sve buduce verzije.",
      "Popis svih pitanja koja krajnji korisnik ima o proizvodu.",
      "Grafikon koji prikazuje smanjenje preostalog posla kroz vrijeme.",
    ],
    correct: 0,
    explanation: "Cilj ciklusa usmjerava rad jednog sprinta.",
  }),
  q({
    id: "scrum-artifacts-3",
    topic: "Scrum artefakti",
    prompt: "Na koje pitanje odgovara Product Backlog?",
    answers: [
      "Sto je sljedece najvaznije za izraditi?",
      "Je li sustav spreman za stvarnu uporabu?",
      "Kako ce sustav biti strukturiran i izveden?",
      "Sto je tim radio od proslog Scrum of Scrums sastanka?",
    ],
    correct: 0,
    explanation: "Product Backlog je prioritetni popis svega potrebnog za proizvod.",
  }),
  q({
    id: "scrum-artifacts-4",
    topic: "Scrum artefakti",
    prompt: "Tko je odgovoran za sadrzaj, dostupnost i redoslijed stavki Product Backloga?",
    answers: [
      "Vlasnik proizvoda.",
      "Scrum Master.",
      "Razvojni tim.",
      "Krajnji korisnik bez tima.",
    ],
    correct: 0,
    explanation: "Product Owner upravlja prioritetima i sadrzajem Product Backloga.",
  }),
  q({
    id: "scrum-artifacts-5",
    topic: "Scrum artefakti",
    prompt: "Sto je Product Backlog Refinement?",
    answers: [
      "Neprekidno dodavanje detalja, procjena i redoslijeda stavkama Product Backloga.",
      "Zavrsni sastanak na kojem se demonstrira inkrement korisniku.",
      "Grafikon koji se svodi na nulu kad se zadaci zavrse.",
      "Formalna odluka o pustanju proizvoda na trziste.",
    ],
    correct: 0,
    explanation: "Refinement poboljsava i razjasnjava Product Backlog tijekom vremena.",
  }),
  q({
    id: "scrum-artifacts-6",
    topic: "Scrum artefakti",
    prompt: "Sto najbolje opisuje Sprint Backlog?",
    answers: [
      "Plan razvojnog tima za jedan ciklus s odabranim stavkama i planom realizacije.",
      "Dugorocna vizija proizvoda i poslovna svrha projekta.",
      "Popis svih korisnickih pitanja za online dokumentaciju.",
      "Skup zavrsenih inkremenata svih prethodnih ciklusa.",
    ],
    correct: 0,
    explanation: "Sprint Backlog pripada razvojnom timu i pokazuje sto se radi u sprintu.",
  }),
  q({
    id: "scrum-artifacts-6a",
    topic: "Scrum artefakti",
    prompt: "Kome pripada Sprint Backlog?",
    answers: [
      "Iskljucivo razvojnom timu.",
      "Iskljucivo vlasniku proizvoda.",
      "Krajnjim korisnicima i sistemskim administratorima.",
      "Predstavnicima svih timova na Scrum of Scrums sastanku.",
    ],
    correct: 0,
    explanation: "Biljeske navode da je Sprint Backlog plan i vlasnistvo razvojnog tima.",
  }),
  q({
    id: "scrum-artifacts-7",
    topic: "Scrum artefakti",
    prompt: "Sto je inkrement?",
    answers: [
      "Zbroj dovrsenih stavki iz ciklusa koji mora biti upotrebljiv i gotov.",
      "Sastanak na kojem se odredjuje cilj sprinta.",
      "Prioritetni popis svih buducih funkcionalnosti.",
      "Sustavska dokumentacija namijenjena developerima.",
    ],
    correct: 0,
    explanation: "Inkrement je radni rezultat koji na kraju sprinta mora biti gotov.",
  }),
  q({
    id: "scrum-artifacts-8",
    topic: "Scrum artefakti",
    prompt: "Cemu sluzi definicija gotovog?",
    answers: [
      "Odredjuje kada se nesto smatra zavrsenim i koju kvalitetu mora zadovoljiti.",
      "Odredjuje koliko ce trajati Daily Scrum.",
      "Zamjenjuje Product Backlog u timovima s vise clanova.",
      "Opisuje hardverske komponente potrebne za sustav.",
    ],
    correct: 0,
    explanation: "Definicija gotovog daje zajednicki kriterij zavrsenosti i kvalitete.",
  }),
  q({
    id: "scrum-artifacts-9",
    topic: "Scrum artefakti",
    prompt: "Sto prikazuje Burn-down grafikon?",
    answers: [
      "Napredak kroz vrijeme i smanjenje preostalog posla.",
      "Uloge Scrum Mastera, vlasnika proizvoda i tima.",
      "Arhitekturne odluke i odnose modula.",
      "Usporedbu sistemske i korisnicke dokumentacije.",
    ],
    correct: 0,
    explanation: "Burn-down grafikon je vizualni prikaz preostalog posla kroz vrijeme.",
  }),
  q({
    id: "scrum-events-1",
    topic: "Scrum dogadjaji",
    prompt: "Cemu sluze dogadjaji u Scrumu?",
    answers: [
      "Redovitosti rada, kontroli, prilagodbi i transparentnosti.",
      "Zamjeni svih artefakata u projektu.",
      "Ukidanju potrebe za komunikacijom u timu.",
      "Definiranju hardverskih komponenti sustava.",
    ],
    correct: 0,
    explanation: "Dogadjaji su formalne prilike za kontrolu i prilagodbu.",
  }),
  q({
    id: "scrum-events-1a",
    topic: "Scrum dogadjaji",
    prompt: "Sto se dogadja ako se Scrum dogadjaji preskacu?",
    answers: [
      "Smanjuju se transparentnost, kontrola i mogucnost prilagodbe.",
      "Automatski se povecava produktivnost razvojnog tima.",
      "Product Backlog postaje odgovornost Scrum Mastera.",
      "Sprint se produljuje na vise od cetiri tjedna.",
    ],
    correct: 0,
    explanation: "Dogadjaji postoje kako bi tim redovito kontrolirao i prilagodjavao rad.",
  }),
  q({
    id: "scrum-events-1b",
    topic: "Scrum dogadjaji",
    prompt: "Koja tvrdnja vrijedi za trajanje Scrum dogadjaja?",
    answers: [
      "Svaki dogadjaj ima ograniceno maksimalno trajanje.",
      "Dogadjaji nemaju vremensko ogranicenje jer su neformalni.",
      "Samo Daily Scrum ima ogranicenje, ostali dogadjaji nemaju.",
      "Trajanje svakog dogadjaja uvijek je tocno 15 minuta.",
    ],
    correct: 0,
    explanation: "Biljeske navode da svaki Scrum dogadjaj ima maksimalno vremensko trajanje.",
  }),
  q({
    id: "scrum-events-2",
    topic: "Scrum dogadjaji",
    prompt: "Sto je sprint u Scrumu?",
    answers: [
      "Vremenski ogranicen ciklus rada i srce Scruma.",
      "Popis svih stavki proizvoda poredan po prioritetu.",
      "Dokumentacija procesa razvoja proizvoda.",
      "Sastanak predstavnika vise Scrum timova.",
    ],
    correct: 0,
    explanation: "Sprint je osnovni ciklus u kojem se ostvaruje cilj i stvara rezultat.",
  }),
  q({
    id: "scrum-events-3",
    topic: "Scrum dogadjaji",
    prompt: "Koliko obicno traje sprint prema biljeskama?",
    answers: [
      "Od 2 do 4 tjedna.",
      "15 minuta.",
      "Jedan dan.",
      "Od 6 do 12 mjeseci.",
    ],
    correct: 0,
    explanation: "Biljeske navode da sprint traje 2 do 4 tjedna.",
  }),
  q({
    id: "scrum-events-3a",
    topic: "Scrum dogadjaji",
    prompt: "Tko moze otkazati sprint prije isteka predvidjenog vremena?",
    answers: [
      "Samo vlasnik proizvoda.",
      "Bilo koji clan razvojnog tima.",
      "Samo krajnji korisnik.",
      "Predstavnik Kanban tima.",
    ],
    correct: 0,
    explanation: "Biljeske navode da je za otkazivanje sprinta ovlasten samo vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-4",
    topic: "Scrum dogadjaji",
    prompt: "Sto je rezultat Sprint Planninga?",
    answers: [
      "Cilj sprinta i Sprint Backlog.",
      "Prilagodjeni Product Backlog nakon demonstracije.",
      "Popis krivih odgovora nakon kviza.",
      "Dokument arhitekture softvera.",
    ],
    correct: 0,
    explanation: "Planiranje ciklusa zavrsava dogovorom o cilju sprinta i Sprint Backlogu.",
  }),
  q({
    id: "scrum-events-4a",
    topic: "Scrum dogadjaji",
    prompt: "Tko sudjeluje u Sprint Planningu?",
    answers: [
      "Svi clanovi Scrum tima.",
      "Samo Scrum Master.",
      "Samo vlasnik proizvoda i krajnji korisnici.",
      "Samo predstavnici vise Scrum timova.",
    ],
    correct: 0,
    explanation: "Planiranje sprinta ukljucuje cijeli Scrum tim.",
  }),
  q({
    id: "scrum-events-5",
    topic: "Scrum dogadjaji",
    prompt: "Koja tri pitanja se postavljaju na Daily Scrumu?",
    answers: [
      "Sto sam radio jucer, sto cu raditi danas, postoje li prepreke?",
      "Sto je dugorocni cilj, koji je budzet, tko odobrava trziste?",
      "Koji su hardverski zahtjevi, koji je OS, koji je server?",
      "Koji testovi nisu uspjeli, tko ih pise, koji alat generira izvjestaj?",
    ],
    correct: 0,
    explanation: "Daily Scrum sluzi brzom dnevnom uskladjivanju tima.",
  }),
  q({
    id: "scrum-events-6",
    topic: "Scrum dogadjaji",
    prompt: "Sto Daily Scrum nije namijenjen raditi?",
    answers: [
      "Detaljno rjesavati probleme tijekom sastanka.",
      "Poboljsati komunikaciju u razvojnom timu.",
      "Prepoznati prepreke u radu.",
      "Uskladiti rad za taj dan.",
    ],
    correct: 0,
    explanation: "Problemi se mogu raspraviti nakon formalnog dijela, ali Daily Scrum nije sastanak za njihovo detaljno rjesavanje.",
  }),
  q({
    id: "scrum-events-7",
    topic: "Scrum dogadjaji",
    prompt: "Sto je cilj Sprint Reviewa?",
    answers: [
      "Pregledati inkrement i po potrebi prilagoditi Product Backlog.",
      "Analizirati rad tima i dogovoriti poboljsanja procesa.",
      "Svakodnevno odgovoriti na tri pitanja o radu.",
      "Ograniciti broj kartica u Kanban stupcu.",
    ],
    correct: 0,
    explanation: "Sprint Review se bavi pregledom rezultata sprinta i Product Backlogom.",
  }),
  q({
    id: "scrum-events-7a",
    topic: "Scrum dogadjaji",
    prompt: "Tko moze sudjelovati na Sprint Reviewu osim Scrum tima?",
    answers: [
      "Osobe koje pozove vlasnik proizvoda, primjerice dionici i krajnji korisnici.",
      "Samo Scrum Master, bez vlasnika proizvoda i razvojnog tima.",
      "Samo predstavnici drugih Scrum timova.",
      "Samo sistemski administratori koji pisu korisnicku dokumentaciju.",
    ],
    correct: 0,
    explanation: "Sprint Review moze ukljuciti dionike i korisnike koje pozove vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-8",
    topic: "Scrum dogadjaji",
    prompt: "Sto je cilj Sprint Retrospectivea?",
    answers: [
      "Analizirati rad tima i dogovoriti poboljsanja za iduci sprint.",
      "Odabrati stavke Product Backloga za trenutni sprint.",
      "Prikazati smanjenje preostalog posla kroz vrijeme.",
      "Usporediti Scrum i Kanban u tablici.",
    ],
    correct: 0,
    explanation: "Retrospektiva je usmjerena na poboljsanje nacina rada tima.",
  }),
  q({
    id: "scrum-events-8a",
    topic: "Scrum dogadjaji",
    prompt: "Kada se odrzava Sprint Retrospective?",
    answers: [
      "Nakon pregleda ciklusa, a prije planiranja sljedeceg sprinta.",
      "Prije svakog Daily Scruma.",
      "Samo nakon pustanja proizvoda na trziste.",
      "Tijekom faze dizajna sustava u metodi vodopada.",
    ],
    correct: 0,
    explanation: "Retrospektiva zakljucuje sprint s naglaskom na poboljsanje rada za sljedeci sprint.",
  }),
  q({
    id: "kanban-1",
    topic: "Kanban",
    prompt: "Sto znaci rijec Kanban?",
    answers: [
      "Vidljiva kartica.",
      "Gotov inkrement.",
      "Dnevni sastanak.",
      "Dokument zahtjeva.",
    ],
    correct: 0,
    explanation: "Kanban dolazi iz japanskog i doslovno znaci vidljiva kartica.",
  }),
  q({
    id: "kanban-1a",
    topic: "Kanban",
    prompt: "Gdje i kada je razvijen Kanban prema biljeskama?",
    answers: [
      "U Toyoti 1940-ih godina.",
      "U Utahu 2001. godine.",
      "U radu Winstona Roycea 1970. godine.",
      "U Java dokumentaciji 1997. godine.",
    ],
    correct: 0,
    explanation: "Biljeske povezuju Kanban s Toyotom i proizvodnjom upravo na vrijeme.",
  }),
  q({
    id: "kanban-1b",
    topic: "Kanban",
    prompt: "S kojom je proizvodnom idejom povezan Kanban?",
    answers: [
      "Upravo na vrijeme, odnosno Just in Time.",
      "Definicija gotovog.",
      "Sekvencijalni vodopad.",
      "JavaDoc komentari.",
    ],
    correct: 0,
    explanation: "Kanban je razvijen uz JIT pristup smanjenja nepotrebnog posla.",
  }),
  q({
    id: "kanban-2",
    topic: "Kanban",
    prompt: "Koja je osnovna ideja Kanbana?",
    answers: [
      "Vizualizirati tok rada i upravljati njime uz ogranicenje rada u tijeku.",
      "Raditi u fiksnim sprintovima s jasno zadanim ulogama.",
      "Zavrsiti svu dokumentaciju prije prvog retka koda.",
      "Testirati samo nakon integracije svih modula.",
    ],
    correct: 0,
    explanation: "Kanban naglasava vizualizaciju rada, WIP ogranicenja i glatki tok.",
  }),
  q({
    id: "kanban-2a",
    topic: "Kanban",
    prompt: "Koja recenica najbolje izrazava nacelo koje dijele Scrum i Kanban u biljeskama?",
    answers: [
      "Prestani pocinjati, pocni zavrsavati.",
      "Dokumentacija prije funkcionalnog softvera.",
      "Sto vise paralelnog rada, to bolji tok.",
      "Svaka faza mora zavrsiti prije sljedece.",
    ],
    correct: 0,
    explanation: "Biljeske navode naglasak na zavrsavanju zapocetog posla.",
  }),
  q({
    id: "kanban-3",
    topic: "Kanban",
    prompt: "Sto znaci WIP u Kanbanu?",
    answers: [
      "Kolicina posla na kojem se trenutno radi.",
      "Popis svih korisnickih zahtjeva.",
      "Definicija gotovog inkrementa.",
      "Plan testiranja za cijeli sustav.",
    ],
    correct: 0,
    explanation: "WIP je work in progress, odnosno rad u tijeku.",
  }),
  q({
    id: "kanban-4",
    topic: "Kanban",
    prompt: "Zasto Kanban ogranicava WIP?",
    answers: [
      "Da se izbjegne preopterecenje, multitasking i zadrzavanje posla.",
      "Da se sprijeci bilo kakva promjena prioriteta.",
      "Da se sprintovi mogu zakljucati na 2 do 4 tjedna.",
      "Da se dokumentacija proizvoda automatski generira.",
    ],
    correct: 0,
    explanation: "Ogranicenje WIP-a pomaze fokusu, toku i produktivnosti.",
  }),
  q({
    id: "kanban-5",
    topic: "Kanban",
    prompt: "Koje su tri glavne ideje Kanbana iz biljeski?",
    answers: [
      "Vizualizirati rad, ograniciti WIP i unaprijediti tok rada.",
      "Planirati sprint, pregledati sprint i odrzati retrospektivu.",
      "Analizirati zahtjeve, dizajnirati sustav i pustiti ga u pogon.",
      "Napisati kod, generirati JavaDoc i objaviti dokumentaciju.",
    ],
    correct: 0,
    explanation: "To su tri glavna nacela Kanbana navedena u biljeskama.",
  }),
  q({
    id: "kanban-6",
    topic: "Kanban",
    prompt: "Sto je Kanban kartica?",
    answers: [
      "Vizualni prikaz jedne stavke posla i njezina statusa.",
      "Uloga osobe koja odredjuje prioritete proizvoda.",
      "Sastanak koji traje oko 15 minuta.",
      "Dokument o arhitekturi sustava.",
    ],
    correct: 0,
    explanation: "Kanban kartica prikazuje zadatak, odgovornu osobu, rok i slicne podatke.",
  }),
  q({
    id: "kanban-6a",
    topic: "Kanban",
    prompt: "Koje su kljucne komponente Kanbana navedene u biljeskama?",
    answers: [
      "Kanban kartice, Kanban stupci, WIP i Kanban staze sa zadacima.",
      "Scrum Master, vlasnik proizvoda, razvojni tim i Sprint Review.",
      "Dokument zahtjeva, dokument koda, JavaDoc i Doxygen.",
      "Analiza zahtjeva, dizajn sustava, implementacija i odrzavanje.",
    ],
    correct: 0,
    explanation: "Biljeske zasebno navode cetiri kljucne Kanban komponente.",
  }),
  q({
    id: "kanban-7",
    topic: "Kanban",
    prompt: "Kada se u Kanbanu proizvod ili funkcionalnost pusta u rad?",
    answers: [
      "Cim je dovrsena i spremna.",
      "Iskljucivo na kraju sprinta od 2 do 4 tjedna.",
      "Tek nakon svih faza metode vodopada.",
      "Samo nakon Scrum of Scrums sastanka.",
    ],
    correct: 0,
    explanation: "Kanban naglasava kontinuiranu isporuku, bez cekanja kraja sprinta.",
  }),
  q({
    id: "kanban-8",
    topic: "Kanban",
    prompt: "Za kakvo okruzenje je Kanban posebno prikladan?",
    answers: [
      "Za okruzenje s cestim promjenama prioriteta.",
      "Za projekte u kojima su svi zahtjevi potpuno stabilni od pocetka.",
      "Za timove kojima trebaju strogo definirane Scrum uloge.",
      "Za projekte gdje se testiranje radi samo na kraju.",
    ],
    correct: 0,
    explanation: "Kanban je fleksibilan i dobro podnosi promjene prioriteta.",
  }),
  q({
    id: "kanban-9",
    topic: "Kanban",
    prompt: "Koja tvrdnja pripada temeljnim nacelima Kanbana?",
    answers: [
      "Zapoceti s onim sto je poznato i postepeno uvoditi promjene.",
      "Uvesti radikalne promjene odmah na pocetku projekta.",
      "Zamijeniti sve postojece uloge Scrum Masterom.",
      "Zabraniti vodstvo ljudima na nizim razinama.",
    ],
    correct: 0,
    explanation: "Kanban se uvodi postupno i postuje postojece postupke, uloge i zaduzenja.",
  }),
  q({
    id: "kanban-10",
    topic: "Kanban",
    prompt: "Sto znaci praksa 'upravljati tokom' u Kanbanu?",
    answers: [
      "Upravljati poslom tako da se stavke sto brze i glatko zavrsavaju.",
      "Dodjeljivati ljudima sto vise zadataka da stalno budu zauzeti.",
      "Zakljucati sve prioritete do kraja projekta.",
      "Odrzavati samo sastanke za pregled rizika.",
    ],
    correct: 0,
    explanation: "Kanban upravlja tokom rada, ne prividnom zauzetoscu ljudi.",
  }),
  q({
    id: "kanban-11",
    topic: "Kanban",
    prompt: "Sto znaci praksa 'jasno definirati politiku procesa' u Kanbanu?",
    answers: [
      "Proces treba biti jasno opisan i vidljiv kako bi tim mogao donositi odluke o poboljsanjima.",
      "Proces treba ostati nevidljiv kako bi tim bio fleksibilniji.",
      "Politiku procesa smije poznavati samo voditelj projekta.",
      "Politika procesa zamjenjuje potrebu za vizualizacijom toka rada.",
    ],
    correct: 0,
    explanation: "Kanban trazi da pravila procesa budu jasna i svima vidljiva.",
  }),
  q({
    id: "kanban-12",
    topic: "Kanban",
    prompt: "Cemu sluze povratne informacije kao Kanban praksa?",
    answers: [
      "Redovitom uskladjivanju rada i razmjeni znanja.",
      "Zabrani promjena prioriteta tijekom rada.",
      "Automatskom generiranju dokumentacije iz koda.",
      "Otkazivanju sprinta odlukom vlasnika proizvoda.",
    ],
    correct: 0,
    explanation: "Povratne informacije u Kanbanu ukljucuju redovite kratke sastanke i uskladjivanje.",
  }),
  q({
    id: "scrum-kanban-1",
    topic: "Scrum ili Kanban",
    prompt: "Koja je glavna razlika izmedju Scruma i Kanbana?",
    answers: [
      "Scrum radi u vremenski ogranicenim sprintovima, a Kanban u kontinuiranom toku rada.",
      "Scrum nema uloge, a Kanban ima Scrum Mastera i vlasnika proizvoda.",
      "Scrum pusta funkcionalnost cim je gotova, a Kanban ceka kraj sprinta.",
      "Scrum je bez sastanaka, a Kanban zahtijeva Sprint Review.",
    ],
    correct: 0,
    explanation: "Scrum je organiziran oko sprintova, a Kanban oko kontinuiranog toka.",
  }),
  q({
    id: "scrum-kanban-2",
    topic: "Scrum ili Kanban",
    prompt: "U kojem pristupu nema zadanih uloga clanova tima?",
    answers: ["Kanban.", "Scrum.", "Scrum of Scrums.", "Metoda vodopada."],
    correct: 0,
    explanation: "U biljeskama Kanban nema zadane uloge kao Scrum.",
  }),
  q({
    id: "scrum-kanban-3",
    topic: "Scrum ili Kanban",
    prompt: "Koji pristup je prikladniji za rad u blokovima i stabilniji plan?",
    answers: ["Scrum.", "Kanban.", "Doxygen.", "JavaDoc."],
    correct: 0,
    explanation: "Scrum je strukturiraniji i prikladniji kada se posao moze grupirati u cikluse.",
  }),
  q({
    id: "scrumban-1",
    topic: "Scrumban",
    prompt: "Sto je Scrumban?",
    answers: [
      "Hibrid Scruma i Kanbana.",
      "Sastanak predstavnika vise Scrum timova.",
      "Dokumentacija testiranja u metodi vodopada.",
      "Alat za generiranje dokumentacije iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Scrumban kombinira Scrum strukturu s Kanban fleksibilnoscu.",
  }),
  q({
    id: "scrumban-2",
    topic: "Scrumban",
    prompt: "Sto Scrumban preuzima od Scruma?",
    answers: [
      "Strukturu, iterativno planiranje, osvrte, preglede i prioritete.",
      "Potpuno nepostojanje uloga i ciklusa.",
      "Iskljucivo Kanban kartice i WIP ogranicenja.",
      "Dokumentaciju proizvoda i procesa.",
    ],
    correct: 0,
    explanation: "Scrumban zadrzava dio Scrum strukture i planiranja.",
  }),
  q({
    id: "scrumban-3",
    topic: "Scrumban",
    prompt: "Sto Scrumban preuzima od Kanbana?",
    answers: [
      "Fleksibilnost, vizualni prikaz toka rada i ogranicenje preuzetih zadataka.",
      "Strogo definirane Scrum uloge i obavezne sprintove.",
      "Dokument zahtjeva i opis arhitekture sustava.",
      "Korektivno i preventivno odrzavanje.",
    ],
    correct: 0,
    explanation: "Od Kanbana preuzima vizualizaciju, tok rada i ogranicavanje zadataka.",
  }),
  q({
    id: "scrumban-4",
    topic: "Scrumban",
    prompt: "Za koje timove je Scrumban posebno prikladan?",
    answers: [
      "Za timove kojima trebaju i struktura Scruma i fleksibilnost Kanbana.",
      "Za timove koji zele potpuno izbjeci vizualizaciju rada.",
      "Za timove koji rade iskljucivo po vodopadnom modelu.",
      "Za timove bez potrebe za prioritetima i ogranicenjem zadataka.",
    ],
    correct: 0,
    explanation: "Scrumban se koristi i kao prijelaz iz Scruma u Kanban.",
  }),
  q({
    id: "sos-1",
    topic: "Scrum of Scrums",
    prompt: "Kada se koristi Scrum of Scrums?",
    answers: [
      "Kada je projekt prevelik za jedan Scrum tim pa treba uskladiti vise timova.",
      "Kada jedan tim treba odrzati Sprint Retrospective.",
      "Kada Product Backlog nema dovoljno detalja.",
      "Kada se dokumentacija generira iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Scrum of Scrums koordinira rad vise Scrum timova.",
  }),
  q({
    id: "sos-2",
    topic: "Scrum of Scrums",
    prompt: "Tko sudjeluje na Scrum of Scrums sastanku?",
    answers: [
      "Predstavnici svakog Scrum tima.",
      "Svi krajnji korisnici proizvoda.",
      "Samo vlasnik proizvoda i nitko drugi.",
      "Samo sistemski administratori.",
    ],
    correct: 0,
    explanation: "Ne sudjeluju svi clanovi, nego jedan ili vise predstavnika svakog tima.",
  }),
  q({
    id: "sos-3",
    topic: "Scrum of Scrums",
    prompt: "Koje pitanje pripada Scrum of Scrums sastanku?",
    answers: [
      "Sto ce vas tim raditi do iduceg sastanka sto moze utjecati na druge timove?",
      "Koji je programski okvir koristen u dokumentaciji koda?",
      "Koji su poslovni ciljevi dokumenta zahtjeva?",
      "Koji je WIP limit za svaki Kanban stupac?",
    ],
    correct: 0,
    explanation: "Scrum of Scrums se fokusira na ovisnosti i utjecaj rada jednog tima na druge.",
  }),
  q({
    id: "docs-1",
    topic: "Dokumentacija",
    prompt: "Koja je osnovna podjela dokumentacije?",
    answers: [
      "Dokumentacija proizvoda i dokumentacija procesa.",
      "Scrum dokumentacija i Kanban dokumentacija.",
      "Preventivna i adaptivna dokumentacija.",
      "HTML dokumentacija i PDF dokumentacija.",
    ],
    correct: 0,
    explanation: "Biljeske dokumentaciju dijele na dokumentaciju proizvoda i procesa.",
  }),
  q({
    id: "docs-2",
    topic: "Dokumentacija",
    prompt: "Sto opisuje dokumentacija proizvoda?",
    answers: [
      "Nastali proizvod i upute za rukovanje.",
      "Samo raspored sastanaka razvojnog tima.",
      "Samo poslovnu korespondenciju i izvjestaje.",
      "Iskljucivo WIP ogranicenja i Kanban stupce.",
    ],
    correct: 0,
    explanation: "Dokumentacija proizvoda opisuje proizvod i daje upute za rukovanje.",
  }),
  q({
    id: "docs-3",
    topic: "Dokumentacija",
    prompt: "Sto opisuje dokumentacija procesa?",
    answers: [
      "Aktivnosti vezane uz razvoj proizvoda.",
      "Samo nacin koristenja proizvoda od strane krajnjih korisnika.",
      "Samo strukturu koda i komentare JavaDoca.",
      "Samo gotove inkremente u Scrum sprintovima.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati planove, rasporede, izvjestaje i slicne aktivnosti razvoja.",
  }),
  q({
    id: "docs-4",
    topic: "Sistemska dokumentacija",
    prompt: "Sto je sistemska dokumentacija?",
    answers: [
      "Dokumenti koji opisuju sustav, njegove dijelove i temeljnu tehnologiju.",
      "Upute za krajnje korisnike bez tehnickih detalja.",
      "Samo marketinski opis proizvoda.",
      "Popis Kanban kartica za trenutni tok rada.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija je tehnicki orijentirana i opisuje sustav.",
  }),
  q({
    id: "docs-5",
    topic: "Sistemska dokumentacija",
    prompt: "Sto pripada sistemskoj dokumentaciji?",
    answers: [
      "Dokument zahtjeva, opis arhitekture, opis koda i dokumentacija testiranja.",
      "FAQ, video upute i portali za pomoc krajnjim korisnicima.",
      "Samo biljeske sa sastanaka i poslovna korespondencija.",
      "Samo Product Backlog i Sprint Backlog.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija ukljucuje zahtjeve, arhitekturu, kod, validaciju i testiranje.",
  }),
  q({
    id: "docs-6",
    topic: "Sistemska dokumentacija",
    prompt: "Sto opisuje dokument zahtjeva?",
    answers: [
      "Sto proizvod treba raditi i koje funkcionalnosti treba imati.",
      "Koliko je zadataka ostalo u trenutnom sprintu.",
      "Koji su komentari potrebni za JavaDoc tagove.",
      "Kako krajnji korisnik pristupa portalu za pomoc.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva sadrzi funkcionalnosti, poslovna pravila, korisnicke price i slucajeve.",
  }),
  q({
    id: "docs-7",
    topic: "Sistemska dokumentacija",
    prompt: "Sto treba biti navedeno u dokumentu zahtjeva?",
    answers: [
      "Uloge, ciljevi, pretpostavke, korisnicke price, interakcija i pitanja.",
      "Samo popis programskih jezika i verzija alata.",
      "Samo tri pitanja za Daily Scrum.",
      "Samo WIP limit i stupci Kanban ploce.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva treba jasno opisati svrhu, znacajke, ponasanje i kontekst proizvoda.",
  }),
  q({
    id: "docs-8",
    topic: "Sistemska dokumentacija",
    prompt: "Sto navodi dokumentacija arhitekture softvera?",
    answers: [
      "Najvaznije arhitekturne odluke i prikaz rjesenja.",
      "Samo krajnje korisnicke upute za rad.",
      "Samo dnevni plan rada u sprintu.",
      "Samo broj testova koji nisu uspjeli.",
    ],
    correct: 0,
    explanation: "Arhitekturna dokumentacija opisuje odluke, principe, rjesenja i dijagrame.",
  }),
  q({
    id: "docs-9",
    topic: "Sistemska dokumentacija",
    prompt: "Kome je prvenstveno namijenjena dokumentacija o kodu?",
    answers: [
      "Developerima.",
      "Iskljucivo krajnjim korisnicima.",
      "Samo vlasniku proizvoda.",
      "Predstavnicima Scrum of Scrums sastanka.",
    ],
    correct: 0,
    explanation: "Dokumentacija o kodu opisuje nacin rada koda i tehnicke detalje.",
  }),
  q({
    id: "docs-10",
    topic: "Dokumentacija testiranja",
    prompt: "Sto opisuje strategija testiranja?",
    answers: [
      "Opci pristup testiranju.",
      "Sto se testira i u kojem trenutku.",
      "Koji korisnik je odgovoran za funkcionalnost.",
      "Koji je idealni burn-down grafikon.",
    ],
    correct: 0,
    explanation: "Strategija testiranja opisuje pristup, strukturu, resurse i prioritete.",
  }),
  q({
    id: "docs-11",
    topic: "Dokumentacija testiranja",
    prompt: "Sto opisuje plan testiranja?",
    answers: [
      "Sto se treba testirati i kada.",
      "Dugorocnu viziju proizvoda.",
      "Korisnicke video upute.",
      "Redoslijed stavki u Product Backlogu.",
    ],
    correct: 0,
    explanation: "Plan testiranja definira stavke, metode, vremenske okvire, uloge i zaduzenja.",
  }),
  q({
    id: "docs-12",
    topic: "Dokumentacija testiranja",
    prompt: "Sto radi specifikacija testnih slucajeva?",
    answers: [
      "Opisuje postupke kojima se verificira svaka znacajka.",
      "Generira HTML dokumentaciju za Java klase.",
      "Prikazuje preostali posao kroz vrijeme.",
      "Odredjuje tko sudjeluje u Scrum of Scrums sastanku.",
    ],
    correct: 0,
    explanation: "Specifikacije testnih slucajeva povezuju znacajke s postupcima provjere.",
  }),
  q({
    id: "docs-13",
    topic: "Korisnicka dokumentacija",
    prompt: "Kome je namijenjena korisnicka dokumentacija?",
    answers: [
      "Krajnjim korisnicima i sistemskim administratorima.",
      "Samo programerima koji odrzavaju kod.",
      "Samo Scrum Masteru i vlasniku proizvoda.",
      "Samo testnom timu za specifikaciju testova.",
    ],
    correct: 0,
    explanation: "Korisnicka dokumentacija mora biti prilagodjena znanju korisnika.",
  }),
  q({
    id: "docs-14",
    topic: "Korisnicka dokumentacija",
    prompt: "Sto moze sadrzavati online korisnicka dokumentacija?",
    answers: [
      "Cesta pitanja, video upute, ugradjenu pomoc i portale za pomoc.",
      "Samo arhitekturne dijagrame i sigurnosne mjere.",
      "Samo dokument zahtjeva i poslovna pravila.",
      "Samo Sprint Backlog i Daily Scrum zapisnik.",
    ],
    correct: 0,
    explanation: "Online dokumentacija treba pomagati korisniku u koristenju proizvoda.",
  }),
  q({
    id: "docs-14a",
    topic: "Korisnicka dokumentacija",
    prompt: "Zasto je kod korisnicke dokumentacije vazno prikupljati povratne informacije korisnika?",
    answers: [
      "Da bi se dokumentacija mogla stalno azurirati i poboljsavati prema stvarnim potrebama korisnika.",
      "Da bi korisnici mogli mijenjati arhitekturu sustava bez razvojnog tima.",
      "Da bi se izbjeglo pisanje sistemske dokumentacije.",
      "Da bi se Product Backlog mogao zamijeniti korisnickim uputama.",
    ],
    correct: 0,
    explanation: "Povratne informacije pomazu da korisnicka dokumentacija ostane korisna i razumljiva.",
  }),
  q({
    id: "docs-15",
    topic: "Dokumentacija procesa",
    prompt: "Sto pripada dokumentaciji procesa?",
    answers: [
      "Projektni planovi, rasporedi testiranja, izvjestaji, standardi i biljeske sa sastanaka.",
      "Samo upute za krajnje korisnike.",
      "Samo komentari iz izvornog koda.",
      "Samo Kanban kartice i Scrum dogadjaji.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati aktivnosti i organizaciju razvoja.",
  }),
  q({
    id: "docs-15a",
    topic: "Dokumentacija procesa",
    prompt: "Sto su planovi, procjene i rasporedi u dokumentaciji procesa?",
    answers: [
      "Dokumenti koji obicno nastaju prije razvoja, ali se mogu prilagodjavati tijekom izrade softvera.",
      "Komentari u kodu iz kojih JavaDoc generira HTML dokumentaciju.",
      "Popis zadataka u sprintu koji pripada iskljucivo razvojnom timu.",
      "Definicija gotovog koja vrijedi za vise Scrum timova.",
    ],
    correct: 0,
    explanation: "Planovi, procjene i rasporedi pomazu organizirati razvoj i mogu se mijenjati tijekom rada.",
  }),
  q({
    id: "docs-15b",
    topic: "Dokumentacija procesa",
    prompt: "Cemu sluze izvjestaji i metrika u dokumentaciji procesa?",
    answers: [
      "Pracenju koristenja vremena i kadra tijekom razvoja softvera.",
      "Opisivanju parametara i povratnih vrijednosti Java metoda.",
      "Ogranicavanju broja zadataka u Kanban stupcu.",
      "Odredjivanju je li sprint moguce otkazati.",
    ],
    correct: 0,
    explanation: "Izvjestaji i metrika daju uvid u resurse i tijek razvoja.",
  }),
  q({
    id: "docs-16",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja o kolicini dokumentacije je najtocnija?",
    answers: [
      "Treba je biti dovoljno, ali ne prekratko ni preopsezno.",
      "Uvijek mora biti sto opseznija, bez obzira na ponavljanje.",
      "Treba je izbjegavati jer usporava razvoj.",
      "Dokumentacija je konacna cim se proizvod pusti u pogon.",
    ],
    correct: 0,
    explanation: "Premalo dokumentacije stvara greske, a previse stvara ponavljanje i opterecenje.",
  }),
  q({
    id: "docs-16a",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja najbolje opisuje status dokumentacije kroz vrijeme?",
    answers: [
      "Dokumentacija nikad nije konacna, nego se stalno nadopunjuje.",
      "Dokumentacija je zakljucana cim se zavrsi analiza zahtjeva.",
      "Dokumentacija se pise samo nakon pustanja proizvoda u pogon.",
      "Dokumentacija se u agilnim metodama potpuno izbacuje.",
    ],
    correct: 0,
    explanation: "Biljeske navode da se dokumentacija stalno nadopunjuje.",
  }),
  q({
    id: "docs-17",
    topic: "Dokumentacija",
    prompt: "Kakva je kvalitetna dokumentacija?",
    answers: [
      "Precizna, jasna i relevantna.",
      "Sto duza, bez obzira na ponavljanje.",
      "Napisana samo nakon zavrsetka projekta.",
      "Namijenjena iskljucivo voditelju projekta.",
    ],
    correct: 0,
    explanation: "Biljeske naglasavaju preciznost, jasnocu i relevantnost.",
  }),
  q({
    id: "docs-17a",
    topic: "Dokumentacija",
    prompt: "Tko doprinosi sastavljanju dokumentacije prema biljeskama?",
    answers: [
      "Svi clanovi tima koji su na bilo koji nacin sudjelovali u razvoju proizvoda.",
      "Samo osoba koja pise kod.",
      "Samo krajnji korisnici nakon zavrsene isporuke.",
      "Samo Scrum Master tijekom Daily Scruma.",
    ],
    correct: 0,
    explanation: "Dokumentacija je rezultat zajednickog rada i komentara vise sudionika.",
  }),
  q({
    id: "docs-18",
    topic: "Generatori dokumentacije",
    prompt: "Cemu sluze generatori dokumentacije?",
    answers: [
      "Laksem i brzem stvaranju dokumentacije, cesto iz komentara u kodu.",
      "Upravljanju WIP limitima na Kanban ploci.",
      "Odrzavanju dnevnih Scrum sastanaka.",
      "Pretvaranju zahtjeva u arhitekturu sustava.",
    ],
    correct: 0,
    explanation: "Generatori dokumentacije automatiziraju dio izrade dokumentacije.",
  }),
  q({
    id: "docs-19",
    topic: "Generatori dokumentacije",
    prompt: "Sto je Doxygen?",
    answers: [
      "Alat za generiranje dokumentacije, primarno za C++, ali podrzava i druge jezike.",
      "Scrum dogadjaj za pregled inkrementa.",
      "Kanban praksa za ogranicavanje rada u tijeku.",
      "Vrsta korisnicke dokumentacije za FAQ.",
    ],
    correct: 0,
    explanation: "Doxygen generira dokumentaciju iz komentara u kodu.",
  }),
  q({
    id: "docs-19a",
    topic: "Generatori dokumentacije",
    prompt: "Sto Doxygen moze napraviti osim generiranja tekstualne dokumentacije?",
    answers: [
      "Prikazati strukturu koda i odnose medju elementima pomocu automatski generiranih grafova.",
      "Odrzati Sprint Review i prilagoditi Product Backlog.",
      "Ograniciti broj Kanban kartica u stupcu.",
      "Odrediti redoslijed implementacije segmenata proizvoda.",
    ],
    correct: 0,
    explanation: "Biljeske navode da Doxygen moze izvuci strukturu koda i prikazati odnose.",
  }),
  q({
    id: "docs-20",
    topic: "Generatori dokumentacije",
    prompt: "Sto JavaDoc generira?",
    answers: [
      "HTML dokumentaciju za Java kod iz komentara.",
      "Burn-down grafikon za Scrum sprint.",
      "Product Backlog iz korisnickih prica.",
      "Dokument zahtjeva iz Kanban kartica.",
    ],
    correct: 0,
    explanation: "JavaDoc je vezan uz dokumentiranje Java koda.",
  }),
  q({
    id: "docs-20a",
    topic: "Generatori dokumentacije",
    prompt: "Koje dvije vrste komentara se spominju kod JavaDoca?",
    answers: [
      "Komentari na razini klase i komentari na razini clanova klase.",
      "Komentari Product Backloga i komentari Sprint Backloga.",
      "Komentari sistemske dokumentacije i komentari korisnicke dokumentacije.",
      "Komentari WIP-a i komentari Kanban stupaca.",
    ],
    correct: 0,
    explanation: "JavaDoc razlikuje komentare za klasu i za clanove poput atributa i metoda.",
  }),
  q({
    id: "docs-21",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje parametar metode?",
    answers: ["@param", "@return", "@version", "@author"],
    correct: 0,
    explanation: "@param se koristi za opis parametra metode.",
  }),
  q({
    id: "docs-22",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje povratnu vrijednost?",
    answers: ["@return", "@throws", "@author", "@version"],
    correct: 0,
    explanation: "@return opisuje povratnu vrijednost metode.",
  }),
  q({
    id: "docs-23",
    topic: "Generatori dokumentacije",
    prompt: "Koji alati su navedeni kao drugi generatori dokumentacije?",
    answers: [
      "Sphinx, Dr. Explain i PHPDocumentator.",
      "Scrum, Kanban i Scrumban.",
      "Product Backlog, Sprint Backlog i Inkrement.",
      "Waterfall, RAD i DevOps.",
    ],
    correct: 0,
    explanation: "Biljeske navode Sphinx, Dr. Explain i PHPDocumentator kao dodatne alate.",
  }),
];
