const optionIds = ["a", "b", "c", "d"];

function q({ id, topic, prompt, answers, correct, explanation }) {
  return {
    id,
    topic,
    prompt,
    options: answers.map((text, index) => ({ id: optionIds[index], text })),
    correctId: optionIds[correct],
    explanation,
  };
}

export const questions = [
  q({
    id: "metode-1",
    topic: "Metode razvoja",
    prompt: "Što najbolje opisuje metode razvoja softvera?",
    answers: [
      "Organizacijski pristupi prema kojima se planira, razvija i kontrolira rad na softveru.",
      "Skup programskih jezika i biblioteka kojima se implementira sustav.",
      "Tehnike testiranja kojima se provjerava samo završna verzija proizvoda.",
      "Dokumenti koji opisuju arhitekturu, kod i korisničke upute.",
    ],
    correct: 0,
    explanation: "Metode razvoja govore kako se organizira rad na softverskom projektu.",
  }),
  q({
    id: "metode-2",
    topic: "Metode razvoja",
    prompt: "Koja tvrdnja najbolje objašnjava zašto se ne razvija svaki softver isto?",
    answers: [
      "Zato što izbor pristupa ovisi o proizvodu, korisnicima, timu i načinu rada.",
      "Zato što se za svaki softver mora koristiti drukciji programski jezik.",
      "Zato što svaka metoda razvoja potpuno zabranjuje dokumentaciju.",
      "Zato što je testiranje uvijek važnije od planiranja i dizajna sustava.",
    ],
    correct: 0,
    explanation: "Metoda se bira prema kontekstu projekta, a ne postoji jedan univerzalan pristup.",
  }),
  q({
    id: "metode-3",
    topic: "Metode razvoja",
    prompt: "Koji je cilj metode razvoja softvera?",
    answers: [
      "Uciniti razvoj uređenim, učinkovitim i predvidivim.",
      "Ukloniti potrebu za komunikacijom s korisnikom.",
      "Osigurati da se kod piše prije definiranja zahtjeva.",
      "Zamijeniti testiranje detaljnom dokumentacijom.",
    ],
    correct: 0,
    explanation: "U bilješkama je cilj metoda razvoja uređen, učinkovit i predvidiv razvoj.",
  }),
  q({
    id: "metode-4",
    topic: "Metode razvoja",
    prompt: "Koja recenica najbolje opisuje svrhu predmeta iz bilješki?",
    answers: [
      "Naučiti kako se softver planira, razvija, testira, dokumentira i modelira u praksi.",
      "Naučiti isključivo sintaksu programskih jezika potrebnih za implementaciju sustava.",
      "Naučiti samo generirati dokumentaciju iz komentara u izvornom kodu.",
      "Naučiti samo razlike između Scrum i Kanban sastanaka.",
    ],
    correct: 0,
    explanation: "Svrha predmeta je shvatiti prakticni proces nastanka softvera i informacijskih sustava.",
  }),
  q({
    id: "waterfall-1",
    topic: "Vodopad",
    prompt: "Koja tvrdnja najtocnije opisuje metodu vodopada?",
    answers: [
      "Linearan i sekvencijalan model u kojem se faze izvode jedna nakon druge.",
      "Iterativan okvir s kratkim sprintovima i stalnim promjenama prioriteta.",
      "Metoda neprekidne isporuke bez definiranog redoslijeda faza.",
      "Tehnika dokumentiranja koda iz komentara u izvornim datotekama.",
    ],
    correct: 0,
    explanation: "Vodopad je linearan i sekvencijalan model razvoja.",
  }),
  q({
    id: "waterfall-1a",
    topic: "Vodopad",
    prompt: "Koja tvrdnja o nastanku metode vodopada odgovara bilješkama?",
    answers: [
      "Riječ je o jednoj od najstarijih metoda, povezanoj s Winstonom W. Royceom i 1970. godinom.",
      "Nastala je 2001. kao dio Agilnog manifesta.",
      "Prvi put se spominje 1986. u članku o timskom radu i ragbiju.",
      "Razvila ju je Toyota 1940-ih u sklopu proizvodnje upravo na vrijeme.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je metoda vodopada najstarija metoda i povezuju je s Royceom 1970.",
  }),
  q({
    id: "waterfall-2",
    topic: "Vodopad",
    prompt: "Što znači da je vodopad sekvencijalan?",
    answers: [
      "Da svaka faza slijedi nakon prethodne i ne preskace se redoslijed.",
      "Da se sve faze izvode paralelno kako bi se ubrzao razvoj.",
      "Da se zahtjevi definiraju tek nakon implementacije.",
      "Da korisnik sam odlučuje kada se prelazi u iducu fazu bez tima.",
    ],
    correct: 0,
    explanation: "Sekvencijalnost znači rad po unaprijed određenom slijedu.",
  }),
  q({
    id: "waterfall-3",
    topic: "Vodopad",
    prompt: "Za kakve projekte je metoda vodopada najprikladnija?",
    answers: [
      "Za projekte s jasnim i stabilnim zahtjevima koji se ne mijenjaju često.",
      "Za projekte u kojima korisnik svaki dan mijenja prioritete i opseg.",
      "Za projekte bez dokumentacije i bez definirane arhitekture.",
      "Za projekte u kojima se proizvod isporucuje nakon svakog dnevnog sastanka.",
    ],
    correct: 0,
    explanation: "Vodopad bolje funkcionira kada su zahtjevi unaprijed poznati i stabilni.",
  }),
  q({
    id: "waterfall-4",
    topic: "Vodopad",
    prompt: "Koliko faza ima metoda vodopada prema bilješkama?",
    answers: ["6", "4", "5", "7"],
    correct: 0,
    explanation: "Bilješke navode sest faza metode vodopada.",
  }),
  q({
    id: "waterfall-5",
    topic: "Vodopad",
    prompt: "Koji je tocan redoslijed prvih triju faza metode vodopada?",
    answers: [
      "Analiza zahtjeva, dizajn sustava, implementacija i testiranje jedinica.",
      "Dizajn sustava, analiza zahtjeva, integracija i testiranje sustava.",
      "Implementacija, analiza zahtjeva, puštanje u pogon.",
      "Analiza zahtjeva, integracija sustava, dizajn sustava.",
    ],
    correct: 0,
    explanation: "Vodopad prvo definira što sustav treba raditi, zatim kako će biti strukturiran, pa prelazi u kod.",
  }),
  q({
    id: "waterfall-6",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara analiza zahtjeva?",
    answers: [
      "Što sustav treba raditi?",
      "Kako će se moduli spojiti u cjelinu?",
      "Je li sustav spreman za stvarnu uporabu?",
      "Kako se preostali posao smanjuje kroz vrijeme?",
    ],
    correct: 0,
    explanation: "Analiza zahtjeva definira potrebe, zahtjeve i funkcionalnosti sustava.",
  }),
  q({
    id: "waterfall-7",
    topic: "Vodopad",
    prompt: "Tko sudjeluje u fazi analize zahtjeva?",
    answers: [
      "Naručitelj softvera i razvojni tim.",
      "Samo razvojni tim bez naručitelja.",
      "Samo krajnji korisnici nakon isporuke.",
      "Scrum Master i predstavnici više Scrum timova.",
    ],
    correct: 0,
    explanation: "U analizi zahtjeva sudjeluju naručitelj i razvojni tim kako bi se razumio problem.",
  }),
  q({
    id: "waterfall-8",
    topic: "Vodopad",
    prompt: "Koji je rezultat faze analize zahtjeva?",
    answers: [
      "Dokument sa zahtjevima.",
      "Arhitektura sustava.",
      "Skup testiranih modula.",
      "Burn-down grafikon.",
    ],
    correct: 0,
    explanation: "Dokument sa zahtjevima je osnova za daljnji razvoj.",
  }),
  q({
    id: "waterfall-9",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara dizajn sustava?",
    answers: [
      "Kako će sustav biti strukturiran i izveden?",
      "Koje su greške ostale nakon isporuke?",
      "Što je sljedeće najvažnije za izraditi?",
      "Koji član tima preuzima koji zadatak u sprintu?",
    ],
    correct: 0,
    explanation: "Dizajn sustava pretvara zahtjeve u strukturu pogodnu za implementaciju.",
  }),
  q({
    id: "waterfall-10",
    topic: "Vodopad",
    prompt: "Što je rezultat faze dizajna sustava?",
    answers: [
      "Arhitektura sustava.",
      "Dokument sa zahtjevima.",
      "Popis testova koji su neuspjeli.",
      "Korisnička dokumentacija.",
    ],
    correct: 0,
    explanation: "U PDF-u je rezultat faze dizajna sustava arhitektura sustava.",
  }),
  q({
    id: "waterfall-11",
    topic: "Vodopad",
    prompt: "Kako treba razumjeti hardverske komponente u dizajnu sustava?",
    answers: [
      "Kao tehničku osnovu na kojoj sustav radi, ako je relevantna za taj projekt.",
      "Kao obavezne fizicke dijelove bez kojih softver ne može postojati.",
      "Kao graficke elemente korisničkog sučelja koje treba dizajnirati.",
      "Kao Scrum artefakte koji opisuju stanje zadataka.",
    ],
    correct: 0,
    explanation: "Ako hardver nije bitan za projekt, fokus dizajna ostaje na strukturi i arhitekturi softvera.",
  }),
  q({
    id: "waterfall-12",
    topic: "Vodopad",
    prompt: "Što se događa u fazi implementacije i testiranja jedinica?",
    answers: [
      "Plan sustava prelazi u programski kod, a jedinice se zasebno testiraju.",
      "Sustav se isporucuje naručitelju nakon pozitivnog testiranja.",
      "Moduli se povezuju i testira se samo cijeli sustav.",
      "Definiraju se korisničke price i poslovna pravila.",
    ],
    correct: 0,
    explanation: "U toj fazi sustav se razvija po manjim cjelinama i svaka se provjerava zasebno.",
  }),
  q({
    id: "waterfall-13",
    topic: "Vodopad",
    prompt: "Koji je krajnji rezultat implementacije i testiranja jedinica?",
    answers: [
      "Skup modula koji su testirani kao jedinice.",
      "Prilagodjeni Product Backlog.",
      "Arhitektura sustava i hardverski zahtjevi.",
      "Korisničke upute za krajnje korisnike.",
    ],
    correct: 0,
    explanation: "PDF navodi da je rezultat te faze skup testiranih modula.",
  }),
  q({
    id: "waterfall-14",
    topic: "Vodopad",
    prompt: "Što je cilj integracije i testiranja sustava?",
    answers: [
      "Provjeriti rade li jedinice zajedno kao cjelovit sustav.",
      "Odrediti dugorocnu viziju proizvoda.",
      "Napisati dokument zahtjeva prije početka razvoja.",
      "Ograniciti WIP na Kanban ploci.",
    ],
    correct: 0,
    explanation: "Moduli se povezuju u sustav i testira se cjelina.",
  }),
  q({
    id: "waterfall-15",
    topic: "Vodopad",
    prompt: "Što znači da je integracija inkrementalna?",
    answers: [
      "Da se provodi u više koraka, postupnim povezivanjem dijelova.",
      "Da se cijeli sustav spaja odjednom bez medjukoraka.",
      "Da se proizvod isporucuje svaki dan nakon Daily Scruma.",
      "Da se zahtjevi mijenjaju nakon svake korisničke price.",
    ],
    correct: 0,
    explanation: "Inkrementalna integracija znači povezivanje u postupnim koracima.",
  }),
  q({
    id: "waterfall-16",
    topic: "Vodopad",
    prompt: "Kada se provodi puštanje u pogon?",
    answers: [
      "Nakon što su rezultati testiranja pozitivni.",
      "Prije analize zahtjeva ako korisnik trazi prototip.",
      "Prije integracije modula kako bi se ubrzao projekt.",
      "Tijekom svakog Product Backlog Refinementa.",
    ],
    correct: 0,
    explanation: "Puštanje u pogon dolazi nakon uspjesnog testiranja.",
  }),
  q({
    id: "waterfall-17",
    topic: "Vodopad",
    prompt: "Koja faza počinje nakon što je sustav pusten u uporabu?",
    answers: [
      "Održavanje.",
      "Dizajn sustava.",
      "Analiza zahtjeva.",
      "Sprint Planning.",
    ],
    correct: 0,
    explanation: "Održavanje počinje nakon isporuke ili puštanja sustava u uporabu.",
  }),
  q({
    id: "waterfall-18",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja znači dodavanje i poboljšavanje funkcionalnosti?",
    answers: [
      "Usavrsavanje.",
      "Korektivno održavanje.",
      "Adaptivno održavanje.",
      "Preventivno održavanje.",
    ],
    correct: 0,
    explanation: "Usavrsavanje se odnosi na nadogradnju funkcionalnosti i nove verzije.",
  }),
  q({
    id: "waterfall-19",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja se odnosi na ispravljanje grešaka koje nisu ranije otkrivene?",
    answers: [
      "Korektivno održavanje.",
      "Preventivno održavanje.",
      "Adaptivno održavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Korektivno održavanje ispravlja greške i nedostatke.",
  }),
  q({
    id: "waterfall-20",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja služi sprječavanju predvidivih buducih grešaka?",
    answers: [
      "Preventivno održavanje.",
      "Korektivno održavanje.",
      "Adaptivno održavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Preventivno održavanje pokušava spriječiti probleme prije nego nastanu.",
  }),
  q({
    id: "waterfall-21",
    topic: "Vodopad",
    prompt: "Koja je prednost metode vodopada?",
    answers: [
      "Faze su jasno definirane i lako ih je pratiti.",
      "Promjene zahtjeva se uvode bez troska u bilo kojoj fazi.",
      "Testiranje je kontinuirano tijekom cijelog razvoja.",
      "Nema potrebe za dokumentacijom jer je tim samoorganiziran.",
    ],
    correct: 0,
    explanation: "Jedna od prednosti vodopada je preglednost i jasno definirane faze.",
  }),
  q({
    id: "waterfall-22",
    topic: "Vodopad",
    prompt: "Koji je važan nedostatak metode vodopada?",
    answers: [
      "Promjene je teško uvoditi kada projekt odmakne.",
      "Zahtjevi su potpuno nevidljivi do kraja projekta.",
      "Metoda nema redoslijed faza.",
      "Testiranje počinje prije definiranja zahtjeva.",
    ],
    correct: 0,
    explanation: "Vodopad je slabije prilagodljiv promjenama.",
  }),
  q({
    id: "waterfall-23",
    topic: "Vodopad",
    prompt: "Zašto vodopad nije prikladan za kompleksne i dugotrajne projekte?",
    answers: [
      "Zato što je slabo fleksibilan i teško prihvaca naknadne promjene zahtjeva.",
      "Zato što nema definirane faze pa se razvoj ne može pratiti.",
      "Zato što ne koristi nikakvu dokumentaciju tijekom razvoja.",
      "Zato što zahtijeva da se proizvod isporucuje nakon svakog dnevnog sastanka.",
    ],
    correct: 0,
    explanation: "Kod dugih i kompleksnih projekata zahtjevi se cesce mijenjaju, a vodopad na to slabo reagira.",
  }),
  q({
    id: "agile-1",
    topic: "Agilne metode",
    prompt: "Što najbolje opisuje agilne metode?",
    answers: [
      "Fleksibilan i iterativan pristup koji naglasava korisnika, suradnju i prilagodbu.",
      "Linearan pristup u kojem se promjene zahtjeva izbjegavaju nakon početka razvoja.",
      "Skup alata za automatsko generiranje dokumentacije iz komentara u kodu.",
      "Metoda održavanja kojom se sprječavaju buduće greške.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika, fleksibilnost i ceste prilagodbe.",
  }),
  q({
    id: "agile-2",
    topic: "Agilne metode",
    prompt: "Zašto agilne metode omogucuju ranije otkrivanje grešaka?",
    answers: [
      "Zbog čestih provjera, testiranja i prilagodbi tijekom razvoja.",
      "Zato što se testiranje radi tek nakon puštanja u pogon.",
      "Zato što korisnik nije uključen dok proizvod nije gotov.",
      "Zato što se dokumentacija piše umjesto testiranja.",
    ],
    correct: 0,
    explanation: "Česta testiranja i povratne informacije smanjuju rizik kasnog otkrivanja problema.",
  }),
  q({
    id: "agile-3",
    topic: "Agilne metode",
    prompt: "Što je Agilni manifest?",
    answers: [
      "Skup temeljnih vrijednosti i principa na kojima se temelji agilni razvoj.",
      "Popis svih zadataka koje razvojni tim planira izvršiti u sprintu.",
      "Grafikon koji prikazuje smanjenje preostalog posla kroz vrijeme.",
      "Dokument koji opisuje hardverske komponente sustava.",
    ],
    correct: 0,
    explanation: "Agilni manifest daje osnovni način razmisljanja za agilni razvoj.",
  }),
  q({
    id: "agile-4",
    topic: "Agilne metode",
    prompt: "Koja vrijednost pripada Agilnom manifestu?",
    answers: [
      "Pojedinci i interakcija važniji su od procesa i alata.",
      "Procesi i alati važniji su od komunikacije u timu.",
      "Opsezna dokumentacija važnija je od funkcionalnog softvera.",
      "Unaprijed zadani plan važniji je od odgovora na promjene.",
    ],
    correct: 0,
    explanation: "Manifest daje prednost ljudima i komunikaciji nad procesima i alatima.",
  }),
  q({
    id: "agile-5",
    topic: "Agilne metode",
    prompt: "Što Agilni manifest stavlja ispred opsezne dokumentacije?",
    answers: [
      "Funkcionalan softver.",
      "Formalni ugovor.",
      "Plan testiranja.",
      "Arhitekturu sustava.",
    ],
    correct: 0,
    explanation: "Jedna od vrijednosti manifesta je funkcionalan softver ispred opsezne dokumentacije.",
  }),
  q({
    id: "agile-6",
    topic: "Agilne metode",
    prompt: "Koji je odnos agilnih metoda prema promjenama?",
    answers: [
      "Promjene se prihvacaju i na njih se nastoji brzo reagirati.",
      "Promjene se blokiraju nakon analize zahtjeva.",
      "Promjene su dopustene samo nakon puštanja u pogon.",
      "Promjene su zamjena za testiranje i dokumentaciju.",
    ],
    correct: 0,
    explanation: "Agilni pristup daje prednost odgovoru na promjene pred krutim praćenjem plana.",
  }),
  q({
    id: "agile-7",
    topic: "Agilne metode",
    prompt: "Kada je nastao Agilni manifest prema bilješkama?",
    answers: [
      "2001. godine.",
      "1970. godine.",
      "1986. godine.",
      "1940-ih godina.",
    ],
    correct: 0,
    explanation: "Bilješke navode 2001. godinu kao nastanak Agilnog manifesta.",
  }),
  q({
    id: "agile-8",
    topic: "Agilne metode",
    prompt: "Koja je uloga korisnika u agilnom razvoju prema bilješkama?",
    answers: [
      "Korisnik je uključen tijekom cijelog razvojnog ciklusa.",
      "Korisnik se uključuje tek nakon puštanja proizvoda u pogon.",
      "Korisnik smije dati zahtjeve samo prije početka dizajna sustava.",
      "Korisnik sudjeluje samo u pisanju dokumentacije koda.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika i stalnu suradnju s njim.",
  }),
  q({
    id: "scrum-1",
    topic: "Scrum",
    prompt: "Što je Scrum?",
    answers: [
      "Razvojni okvir za rješavanje slozenih i dinamicnih problema.",
      "Tehnika testiranja jedinica u metodi vodopada.",
      "Generator dokumentacije za programski jezik Java.",
      "Metoda bez uloga, događaja, artefakata i pravila.",
    ],
    correct: 0,
    explanation: "Scrum je razvojni okvir, a ne samo tehnika ili postupak.",
  }),
  q({
    id: "scrum-2",
    topic: "Scrum",
    prompt: "Koja tvrdnja o nazivu Scrum je tocna?",
    answers: [
      "Naziv dolazi iz ragbija i naglasava timski rad.",
      "Naziv je kratica za softverski ciklus upravljanja rizikom.",
      "Naziv oznacava dokumentaciju procesa u agilnim projektima.",
      "Naziv se prvi put javlja kao Java alat za dokumentaciju.",
    ],
    correct: 0,
    explanation: "U bilješkama Scrum dolazi iz ragbija i naglasava timski rad.",
  }),
  q({
    id: "scrum-2a",
    topic: "Scrum",
    prompt: "Kada se Scrum prvi put spominje prema bilješkama?",
    answers: [
      "1986. godine.",
      "1970. godine.",
      "2001. godine.",
      "1997. godine.",
    ],
    correct: 0,
    explanation: "Bilješke navode 1986. godinu i članak The New New Product Development Game.",
  }),
  q({
    id: "scrum-3",
    topic: "Scrum",
    prompt: "Od cega se Scrum sastoji?",
    answers: [
      "Od uloga, događaja, artefakata i pravila.",
      "Od faza analize, dizajna, implementacije i održavanja.",
      "Od Kanban kartica, Kanban stupaca i WIP ograničenja.",
      "Od dokumenta zahtjeva, plana testiranja i JavaDoc tagova.",
    ],
    correct: 0,
    explanation: "Bilješke navode četiri osnovna dijela Scruma: uloge, događaji, artefakti i pravila.",
  }),
  q({
    id: "scrum-4",
    topic: "Scrum",
    prompt: "Kakav je Scrum tim prema bilješkama?",
    answers: [
      "Mali, samostalan, fleksibilan i prilagodljiv.",
      "Velik, hijerarhijski i strogo specijaliziran.",
      "Bez odgovornosti i bez definiranih uloga.",
      "Sastavljen isključivo od krajnjih korisnika.",
    ],
    correct: 0,
    explanation: "Bit Scruma je u malom timu koji može samostalno raditi i prilagođavati se.",
  }),
  q({
    id: "scrum-4a",
    topic: "Scrum",
    prompt: "Što znači da Scrum koristi preklapajući model rada?",
    answers: [
      "Da se kroz cijeli tok projekta pomalo radi na više stvari.",
      "Da se faze moraju strogo završavati jedna prije druge.",
      "Da se svi zadaci rade tek nakon potpunog završetka dokumentacije.",
      "Da se proizvod isporucuje samo nakon završne integracije sustava.",
    ],
    correct: 0,
    explanation: "Bilješke opisuju Scrum kao model u kojem se kroz tok razvoja radi pomalo na više stvari.",
  }),
  q({
    id: "scrum-4b",
    topic: "Scrum",
    prompt: "Koja tvrdnja najbolje opisuje tezinu Scruma prema bilješkama?",
    answers: [
      "Jednostavan je za razumjeti, ali tezak za savladati.",
      "Tezak je za razumjeti, ali ne zahtijeva praksu.",
      "Jednostavan je zato što nema uloge, događaje ni pravila.",
      "Tezak je isključivo zbog potrebe za hardverskim komponentama.",
    ],
    correct: 0,
    explanation: "Scrum ima jednostavnu osnovnu strukturu, ali kvalitetna primjena nije trivijalna.",
  }),
  q({
    id: "scrum-5",
    topic: "Scrum uloge",
    prompt: "Koje su tri uloge u Scrum timu?",
    answers: [
      "Scrum Master, vlasnik proizvoda i razvojni tim.",
      "Tester, arhitekt i sistemski administrator.",
      "Vlasnik proizvoda, krajnji korisnik i dokumentarist.",
      "Projektni sponzor, voditelj prodaje i analiticar tržišta.",
    ],
    correct: 0,
    explanation: "Scrum Team cine Scrum Master, vlasnik proizvoda i razvojni tim.",
  }),
  q({
    id: "scrum-6",
    topic: "Scrum uloge",
    prompt: "Koja je glavna uloga Scrum Mastera?",
    answers: [
      "Osigurati pravilno i neometano odvijanje Scrum procesa.",
      "Odrediti poslovnu viziju i redoslijed svih stavki proizvoda.",
      "Samostalno napisati sav kod i testirati sve jedinice.",
      "Odobriti puštanje proizvoda na tržište umjesto vlasnika proizvoda.",
    ],
    correct: 0,
    explanation: "Scrum Master vodi proces, uklanja prepreke i pomaze timu.",
  }),
  q({
    id: "scrum-6a",
    topic: "Scrum uloge",
    prompt: "Koja aktivnost pripada Scrum Masteru prema bilješkama?",
    answers: [
      "Prati napredak tima i cini ga vidljivim svima uključenima u projekt.",
      "Samostalno određuje poslovne zahtjeve i redoslijed implementacije.",
      "Donosi završnu odluku zadovoljava li proizvod potrebnu kvalitetu.",
      "Piše korisničku dokumentaciju namijenjenu krajnjim korisnicima.",
    ],
    correct: 0,
    explanation: "Scrum Master brine o procesu, produktivnosti, uklanjanju prepreka i vidljivosti napretka.",
  }),
  q({
    id: "scrum-7",
    topic: "Scrum uloge",
    prompt: "Što radi vlasnik proizvoda?",
    answers: [
      "Određuje zahtjeve, ključne značajke i redoslijed implementacije.",
      "Brine se da dnevni sastanak traje točno 15 minuta.",
      "Određuje WIP ograničenja na Kanban ploci.",
      "Generira HTML dokumentaciju iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovara za viziju, zahtjeve i prioritete proizvoda.",
  }),
  q({
    id: "scrum-7a",
    topic: "Scrum uloge",
    prompt: "Koja odluka pripada vlasniku proizvoda?",
    answers: [
      "Kada nastaviti razvoj, a kada proizvod pustiti na tržište.",
      "Kako će razvojni tim tehnički podijeliti posao na manje zadatke.",
      "Koji će predstavnik ici na Scrum of Scrums sastanak.",
      "Kako će se generirati JavaDoc dokumentacija iz komentara.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovoran je za viziju i odluke o razvoju i pustanju proizvoda.",
  }),
  q({
    id: "scrum-8",
    topic: "Scrum uloge",
    prompt: "Koja tvrdnja najbolje opisuje razvojni tim u Scrumu?",
    answers: [
      "Samostalno odlučuje kako podijeliti posao na manje zadatke.",
      "Ceka da vlasnik proizvoda detaljno dodijeli svaki zadatak svakom članu.",
      "Sudjeluje samo u dokumentiranju završenog proizvoda.",
      "Sastoji se od predstavnika više Scrum timova.",
    ],
    correct: 0,
    explanation: "Razvojni tim je samoorganizirajuci i odlučuje kako će razraditi posao.",
  }),
  q({
    id: "scrum-9",
    topic: "Scrum uloge",
    prompt: "Koja je preporucena velicina Scrum razvojnog tima?",
    answers: [
      "Od 3 do 9 članova, često oko 7.",
      "Od 1 do 2 člana, kako bi komunikacija bila minimalna.",
      "Najmanje 20 članova zbog raspodjele specijalizacija.",
      "Tocno 15 članova, jer Daily Scrum traje 15 minuta.",
    ],
    correct: 0,
    explanation: "Prevelik tim otezava komunikaciju, a premalen može smanjiti produktivnost.",
  }),
  q({
    id: "scrum-artifacts-1",
    topic: "Scrum artefakti",
    prompt: "Što su Scrum artefakti u kontekstu bilješki?",
    answers: [
      "Konkretni radni elementi koji omogucuju transparentnost, uvid i prilagodbu.",
      "Formalne uloge koje određuju tko vodi projekt i tko piše kod.",
      "Sastanci koji se održavaju na početku i kraju svakog sprinta.",
      "Vrste održavanja nakon puštanja softvera u pogon.",
    ],
    correct: 0,
    explanation: "Artefakti su elementi poput Product Backloga, Sprint Backloga, inkrementa i grafikona.",
  }),
  q({
    id: "scrum-artifacts-1a",
    topic: "Scrum artefakti",
    prompt: "Zašto su Scrum artefakti dinamicki?",
    answers: [
      "Zato što se mogu mijenjati kada se promijene zahtjevi, tržište ili tehnologija.",
      "Zato što uvijek ostaju isti od početka do kraja projekta.",
      "Zato što ih može mijenjati samo Scrum Master tijekom Daily Scruma.",
      "Zato što služe isključivo za arhiviranje završenog proizvoda.",
    ],
    correct: 0,
    explanation: "Artefakti prate stvarno stanje rada i mijenjaju se kako se mijenja kontekst projekta.",
  }),
  q({
    id: "scrum-artifacts-2",
    topic: "Scrum artefakti",
    prompt: "Što definira vizija proizvoda?",
    answers: [
      "Dugorocni cilj proizvoda ili projekta.",
      "Dnevni plan rada razvojnog tima.",
      "Popis grešaka nakon integracijskog testiranja.",
      "Maksimalan broj zadataka u WIP stupcu.",
    ],
    correct: 0,
    explanation: "Vizija proizvoda treba biti jasna, kratka i precizna.",
  }),
  q({
    id: "scrum-artifacts-2a",
    topic: "Scrum artefakti",
    prompt: "Što je cilj ciklusa u Scrumu?",
    answers: [
      "Cilj koji se treba postici tijekom jednog sprinta implementacijom odabranih stavki.",
      "Dugorocna poslovna vizija cijelog proizvoda za sve buduće verzije.",
      "Popis svih pitanja koja krajnji korisnik ima o proizvodu.",
      "Grafikon koji prikazuje smanjenje preostalog posla kroz vrijeme.",
    ],
    correct: 0,
    explanation: "Cilj ciklusa usmjerava rad jednog sprinta.",
  }),
  q({
    id: "scrum-artifacts-3",
    topic: "Scrum artefakti",
    prompt: "Na koje pitanje odgovara Product Backlog?",
    answers: [
      "Što je sljedeće najvažnije za izraditi?",
      "Je li sustav spreman za stvarnu uporabu?",
      "Kako će sustav biti strukturiran i izveden?",
      "Što je tim radio od prošlog Scrum of Scrums sastanka?",
    ],
    correct: 0,
    explanation: "Product Backlog je prioritetni popis svega potrebnog za proizvod.",
  }),
  q({
    id: "scrum-artifacts-4",
    topic: "Scrum artefakti",
    prompt: "Tko je odgovoran za sadržaj, dostupnost i redoslijed stavki Product Backloga?",
    answers: [
      "Vlasnik proizvoda.",
      "Scrum Master.",
      "Razvojni tim.",
      "Krajnji korisnik bez tima.",
    ],
    correct: 0,
    explanation: "Product Owner upravlja prioritetima i sadržajem Product Backloga.",
  }),
  q({
    id: "scrum-artifacts-5",
    topic: "Scrum artefakti",
    prompt: "Što je Product Backlog Refinement?",
    answers: [
      "Neprekidno dodavanje detalja, procjena i redoslijeda stavkama Product Backloga.",
      "Završni sastanak na kojem se demonstrira inkrement korisniku.",
      "Grafikon koji se svodi na nulu kad se zadaci završe.",
      "Formalna odluka o pustanju proizvoda na tržište.",
    ],
    correct: 0,
    explanation: "Refinement poboljšava i razjasnjava Product Backlog tijekom vremena.",
  }),
  q({
    id: "scrum-artifacts-6",
    topic: "Scrum artefakti",
    prompt: "Što najbolje opisuje Sprint Backlog?",
    answers: [
      "Plan razvojnog tima za jedan ciklus s odabranim stavkama i planom realizacije.",
      "Dugorocna vizija proizvoda i poslovna svrha projekta.",
      "Popis svih korisničih pitanja za online dokumentaciju.",
      "Skup završenih inkremenata svih prethodnih ciklusa.",
    ],
    correct: 0,
    explanation: "Sprint Backlog pripada razvojnom timu i pokazuje što se radi u sprintu.",
  }),
  q({
    id: "scrum-artifacts-6a",
    topic: "Scrum artefakti",
    prompt: "Kome pripada Sprint Backlog?",
    answers: [
      "Isključivo razvojnom timu.",
      "Isključivo vlasniku proizvoda.",
      "Krajnjim korisnicima i sistemskim administratorima.",
      "Predstavnicima svih timova na Scrum of Scrums sastanku.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je Sprint Backlog plan i vlasnistvo razvojnog tima.",
  }),
  q({
    id: "scrum-artifacts-7",
    topic: "Scrum artefakti",
    prompt: "Što je inkrement?",
    answers: [
      "Zbroj dovrsenih stavki iz ciklusa koji mora biti upotrebljiv i gotov.",
      "Sastanak na kojem se određuje cilj sprinta.",
      "Prioritetni popis svih buducih funkcionalnosti.",
      "Sustavska dokumentacija namijenjena developerima.",
    ],
    correct: 0,
    explanation: "Inkrement je radni rezultat koji na kraju sprinta mora biti gotov.",
  }),
  q({
    id: "scrum-artifacts-8",
    topic: "Scrum artefakti",
    prompt: "Čemu služi definicija gotovog?",
    answers: [
      "Određuje kada se nesto smatra završenim i koju kvalitetu mora zadovoljiti.",
      "Određuje koliko će trajati Daily Scrum.",
      "Zamjenjuje Product Backlog u timovima s više članova.",
      "Opisuje hardverske komponente potrebne za sustav.",
    ],
    correct: 0,
    explanation: "Definicija gotovog daje zajednicki kriterij završenosti i kvalitete.",
  }),
  q({
    id: "scrum-artifacts-9",
    topic: "Scrum artefakti",
    prompt: "Što prikazuje Burn-down grafikon?",
    answers: [
      "Napredak kroz vrijeme i smanjenje preostalog posla.",
      "Uloge Scrum Mastera, vlasnika proizvoda i tima.",
      "Arhitekturne odluke i odnose modula.",
      "Usporedbu sistemske i korisničke dokumentacije.",
    ],
    correct: 0,
    explanation: "Burn-down grafikon je vizualni prikaz preostalog posla kroz vrijeme.",
  }),
  q({
    id: "scrum-events-1",
    topic: "Scrum događaji",
    prompt: "Čemu služe događaji u Scrumu?",
    answers: [
      "Redovitosti rada, kontroli, prilagodbi i transparentnosti.",
      "Zamjeni svih artefakata u projektu.",
      "Ukidanju potrebe za komunikacijom u timu.",
      "Definiranju hardverskih komponenti sustava.",
    ],
    correct: 0,
    explanation: "Događaji su formalne prilike za kontrolu i prilagodbu.",
  }),
  q({
    id: "scrum-events-1a",
    topic: "Scrum događaji",
    prompt: "Što se događa ako se Scrum događaji preskaču?",
    answers: [
      "Smanjuju se transparentnost, kontrola i mogućnost prilagodbe.",
      "Automatski se povećava produktivnost razvojnog tima.",
      "Product Backlog postaje odgovornost Scrum Mastera.",
      "Sprint se produljuje na više od četiri tjedna.",
    ],
    correct: 0,
    explanation: "Događaji postoje kako bi tim redovito kontrolirao i prilagođavao rad.",
  }),
  q({
    id: "scrum-events-1b",
    topic: "Scrum događaji",
    prompt: "Koja tvrdnja vrijedi za trajanje Scrum događaja?",
    answers: [
      "Svaki događaj ima ograničeno maksimalno trajanje.",
      "Događaji nemaju vremensko ograničenje jer su neformalni.",
      "Samo Daily Scrum ima ograničenje, ostali događaji nemaju.",
      "Trajanje svakog događaja uvijek je točno 15 minuta.",
    ],
    correct: 0,
    explanation: "Bilješke navode da svaki Scrum događaj ima maksimalno vremensko trajanje.",
  }),
  q({
    id: "scrum-events-2",
    topic: "Scrum događaji",
    prompt: "Što je sprint u Scrumu?",
    answers: [
      "Vremenski ograničen ciklus rada i srce Scruma.",
      "Popis svih stavki proizvoda poredan po prioritetu.",
      "Dokumentacija procesa razvoja proizvoda.",
      "Sastanak predstavnika više Scrum timova.",
    ],
    correct: 0,
    explanation: "Sprint je osnovni ciklus u kojem se ostvaruje cilj i stvara rezultat.",
  }),
  q({
    id: "scrum-events-3",
    topic: "Scrum događaji",
    prompt: "Koliko obično traje sprint prema bilješkama?",
    answers: [
      "Od 2 do 4 tjedna.",
      "15 minuta.",
      "Jedan dan.",
      "Od 6 do 12 mjeseci.",
    ],
    correct: 0,
    explanation: "Bilješke navode da sprint traje 2 do 4 tjedna.",
  }),
  q({
    id: "scrum-events-3a",
    topic: "Scrum događaji",
    prompt: "Tko može otkazati sprint prije isteka predviđenog vremena?",
    answers: [
      "Samo vlasnik proizvoda.",
      "Bilo koji član razvojnog tima.",
      "Samo krajnji korisnik.",
      "Predstavnik Kanban tima.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je za otkazivanje sprinta ovlasten samo vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-4",
    topic: "Scrum događaji",
    prompt: "Što je rezultat Sprint Planninga?",
    answers: [
      "Cilj sprinta i Sprint Backlog.",
      "Prilagodjeni Product Backlog nakon demonstracije.",
      "Popis krivih odgovora nakon kviza.",
      "Dokument arhitekture softvera.",
    ],
    correct: 0,
    explanation: "Planiranje ciklusa završava dogovorom o cilju sprinta i Sprint Backlogu.",
  }),
  q({
    id: "scrum-events-4a",
    topic: "Scrum događaji",
    prompt: "Tko sudjeluje u Sprint Planningu?",
    answers: [
      "Svi članovi Scrum tima.",
      "Samo Scrum Master.",
      "Samo vlasnik proizvoda i krajnji korisnici.",
      "Samo predstavnici više Scrum timova.",
    ],
    correct: 0,
    explanation: "Planiranje sprinta uključuje cijeli Scrum tim.",
  }),
  q({
    id: "scrum-events-5",
    topic: "Scrum događaji",
    prompt: "Koja tri pitanja se postavljaju na Daily Scrumu?",
    answers: [
      "Što sam radio jucer, što cu raditi danas, postoje li prepreke?",
      "Što je dugorocni cilj, koji je budzet, tko odobrava tržište?",
      "Koji su hardverski zahtjevi, koji je OS, koji je server?",
      "Koji testovi nisu uspjeli, tko ih piše, koji alat generira izvještaj?",
    ],
    correct: 0,
    explanation: "Daily Scrum služi brzom dnevnom usklađivanju tima.",
  }),
  q({
    id: "scrum-events-6",
    topic: "Scrum događaji",
    prompt: "Što Daily Scrum nije namijenjen raditi?",
    answers: [
      "Detaljno rješavati probleme tijekom sastanka.",
      "Poboljsati komunikaciju u razvojnom timu.",
      "Prepoznati prepreke u radu.",
      "Uskladiti rad za taj dan.",
    ],
    correct: 0,
    explanation: "Problemi se mogu raspraviti nakon formalnog dijela, ali Daily Scrum nije sastanak za njihovo detaljno rješavanje.",
  }),
  q({
    id: "scrum-events-7",
    topic: "Scrum događaji",
    prompt: "Što je cilj Sprint Reviewa?",
    answers: [
      "Pregledati inkrement i po potrebi prilagoditi Product Backlog.",
      "Analizirati rad tima i dogovoriti poboljšanja procesa.",
      "Svakodnevno odgovoriti na tri pitanja o radu.",
      "Ograniciti broj kartica u Kanban stupcu.",
    ],
    correct: 0,
    explanation: "Sprint Review se bavi pregledom rezultata sprinta i Product Backlogom.",
  }),
  q({
    id: "scrum-events-7a",
    topic: "Scrum događaji",
    prompt: "Tko može sudjelovati na Sprint Reviewu osim Scrum tima?",
    answers: [
      "Osobe koje pozove vlasnik proizvoda, primjerice dionici i krajnji korisnici.",
      "Samo Scrum Master, bez vlasnika proizvoda i razvojnog tima.",
      "Samo predstavnici drugih Scrum timova.",
      "Samo sistemski administratori koji pisu korisničku dokumentaciju.",
    ],
    correct: 0,
    explanation: "Sprint Review može uključiti dionike i korisnike koje pozove vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-8",
    topic: "Scrum događaji",
    prompt: "Što je cilj Sprint Retrospectivea?",
    answers: [
      "Analizirati rad tima i dogovoriti poboljšanja za iduci sprint.",
      "Odabrati stavke Product Backloga za trenutni sprint.",
      "Prikazati smanjenje preostalog posla kroz vrijeme.",
      "Usporediti Scrum i Kanban u tablici.",
    ],
    correct: 0,
    explanation: "Retrospektiva je usmjerena na poboljšanje načina rada tima.",
  }),
  q({
    id: "scrum-events-8a",
    topic: "Scrum događaji",
    prompt: "Kada se održava Sprint Retrospective?",
    answers: [
      "Nakon pregleda ciklusa, a prije planiranja sljedećeg sprinta.",
      "Prije svakog Daily Scruma.",
      "Samo nakon puštanja proizvoda na tržište.",
      "Tijekom faze dizajna sustava u metodi vodopada.",
    ],
    correct: 0,
    explanation: "Retrospektiva zaključuje sprint s naglaskom na poboljšanje rada za sljedeći sprint.",
  }),
  q({
    id: "kanban-1",
    topic: "Kanban",
    prompt: "Što znači riječ Kanban?",
    answers: [
      "Vidljiva kartica.",
      "Gotov inkrement.",
      "Dnevni sastanak.",
      "Dokument zahtjeva.",
    ],
    correct: 0,
    explanation: "Kanban dolazi iz japanskog i doslovno znači vidljiva kartica.",
  }),
  q({
    id: "kanban-1a",
    topic: "Kanban",
    prompt: "Gdje i kada je razvijen Kanban prema bilješkama?",
    answers: [
      "U Toyoti 1940-ih godina.",
      "U Utahu 2001. godine.",
      "U radu Winstona Roycea 1970. godine.",
      "U Java dokumentaciji 1997. godine.",
    ],
    correct: 0,
    explanation: "Bilješke povezuju Kanban s Toyotom i proizvodnjom upravo na vrijeme.",
  }),
  q({
    id: "kanban-1b",
    topic: "Kanban",
    prompt: "S kojom je proizvodnom idejom povezan Kanban?",
    answers: [
      "Upravo na vrijeme, odnosno Just in Time.",
      "Definicija gotovog.",
      "Sekvencijalni vodopad.",
      "JavaDoc komentari.",
    ],
    correct: 0,
    explanation: "Kanban je razvijen uz JIT pristup smanjenja nepotrebnog posla.",
  }),
  q({
    id: "kanban-2",
    topic: "Kanban",
    prompt: "Koja je osnovna ideja Kanbana?",
    answers: [
      "Vizualizirati tok rada i upravljati njime uz ograničenje rada u tijeku.",
      "Raditi u fiksnim sprintovima s jasno zadanim ulogama.",
      "Završiti svu dokumentaciju prije prvog retka koda.",
      "Testirati samo nakon integracije svih modula.",
    ],
    correct: 0,
    explanation: "Kanban naglasava vizualizaciju rada, WIP ograničenja i glatki tok.",
  }),
  q({
    id: "kanban-2a",
    topic: "Kanban",
    prompt: "Koja recenica najbolje izrazava načelo koje dijele Scrum i Kanban u bilješkama?",
    answers: [
      "Prestani pocinjati, počni završavati.",
      "Dokumentacija prije funkcionalnog softvera.",
      "Što više paralelnog rada, to bolji tok.",
      "Svaka faza mora završiti prije sljedeće.",
    ],
    correct: 0,
    explanation: "Bilješke navode naglasak na završavanju zapocetog posla.",
  }),
  q({
    id: "kanban-3",
    topic: "Kanban",
    prompt: "Što znači WIP u Kanbanu?",
    answers: [
      "Količina posla na kojem se trenutno radi.",
      "Popis svih korisničih zahtjeva.",
      "Definicija gotovog inkrementa.",
      "Plan testiranja za cijeli sustav.",
    ],
    correct: 0,
    explanation: "WIP je work in progrešs, odnosno rad u tijeku.",
  }),
  q({
    id: "kanban-4",
    topic: "Kanban",
    prompt: "Zašto Kanban ogranicava WIP?",
    answers: [
      "Da se izbjegne preopterećenje, multitasking i zadržavanje posla.",
      "Da se spriječi bilo kakva promjena prioriteta.",
      "Da se sprintovi mogu zaključati na 2 do 4 tjedna.",
      "Da se dokumentacija proizvoda automatski generira.",
    ],
    correct: 0,
    explanation: "Ogranicenje WIP-a pomaze fokusu, toku i produktivnosti.",
  }),
  q({
    id: "kanban-5",
    topic: "Kanban",
    prompt: "Koje su tri glavne ideje Kanbana iz bilješki?",
    answers: [
      "Vizualizirati rad, ograniciti WIP i unaprijediti tok rada.",
      "Planirati sprint, pregledati sprint i održati retrospektivu.",
      "Analizirati zahtjeve, dizajnirati sustav i pustiti ga u pogon.",
      "Napisati kod, generirati JavaDoc i objaviti dokumentaciju.",
    ],
    correct: 0,
    explanation: "To su tri glavna načela Kanbana navedena u bilješkama.",
  }),
  q({
    id: "kanban-6",
    topic: "Kanban",
    prompt: "Što je Kanban kartica?",
    answers: [
      "Vizualni prikaz jedne stavke posla i njezina statusa.",
      "Uloga osobe koja određuje prioritete proizvoda.",
      "Sastanak koji traje oko 15 minuta.",
      "Dokument o arhitekturi sustava.",
    ],
    correct: 0,
    explanation: "Kanban kartica prikazuje zadatak, odgovornu osobu, rok i slicne podatke.",
  }),
  q({
    id: "kanban-6a",
    topic: "Kanban",
    prompt: "Koje su ključne komponente Kanbana navedene u bilješkama?",
    answers: [
      "Kanban kartice, Kanban stupci, WIP i Kanban staze sa zadacima.",
      "Scrum Master, vlasnik proizvoda, razvojni tim i Sprint Review.",
      "Dokument zahtjeva, dokument koda, JavaDoc i Doxygen.",
      "Analiza zahtjeva, dizajn sustava, implementacija i održavanje.",
    ],
    correct: 0,
    explanation: "Bilješke zasebno navode četiri ključne Kanban komponente.",
  }),
  q({
    id: "kanban-7",
    topic: "Kanban",
    prompt: "Kada se u Kanbanu proizvod ili funkcionalnost pusta u rad?",
    answers: [
      "Čim je dovrsena i spremna.",
      "Isključivo na kraju sprinta od 2 do 4 tjedna.",
      "Tek nakon svih faza metode vodopada.",
      "Samo nakon Scrum of Scrums sastanka.",
    ],
    correct: 0,
    explanation: "Kanban naglasava kontinuiranu isporuku, bez čekanja kraja sprinta.",
  }),
  q({
    id: "kanban-8",
    topic: "Kanban",
    prompt: "Za kakvo okruzenje je Kanban posebno prikladan?",
    answers: [
      "Za okruzenje s cestim promjenama prioriteta.",
      "Za projekte u kojima su svi zahtjevi potpuno stabilni od početka.",
      "Za timove kojima trebaju strogo definirane Scrum uloge.",
      "Za projekte gdje se testiranje radi samo na kraju.",
    ],
    correct: 0,
    explanation: "Kanban je fleksibilan i dobro podnosi promjene prioriteta.",
  }),
  q({
    id: "kanban-9",
    topic: "Kanban",
    prompt: "Koja tvrdnja pripada temeljnim nacelima Kanbana?",
    answers: [
      "Zapoceti s onim što je poznato i postepeno uvoditi promjene.",
      "Uvesti radikalne promjene odmah na početku projekta.",
      "Zamijeniti sve postojece uloge Scrum Masterom.",
      "Zabraniti vodstvo ljudima na nizim razinama.",
    ],
    correct: 0,
    explanation: "Kanban se uvodi postupno i postuje postojece postupke, uloge i zaduzenja.",
  }),
  q({
    id: "kanban-10",
    topic: "Kanban",
    prompt: "Što znači praksa 'upravljati tokom' u Kanbanu?",
    answers: [
      "Upravljati poslom tako da se stavke što brze i glatko završavaju.",
      "Dodjeljivati ljudima što više zadataka da stalno budu zauzeti.",
      "Zaključati sve prioritete do kraja projekta.",
      "Odrzavati samo sastanke za pregled rizika.",
    ],
    correct: 0,
    explanation: "Kanban upravlja tokom rada, ne prividnom zauzetoscu ljudi.",
  }),
  q({
    id: "kanban-11",
    topic: "Kanban",
    prompt: "Što znači praksa 'jasno definirati politiku procesa' u Kanbanu?",
    answers: [
      "Proces treba biti jasno opisan i vidljiv kako bi tim mogao donositi odluke o poboljšanjima.",
      "Proces treba ostati nevidljiv kako bi tim bio fleksibilniji.",
      "Politiku procesa smije poznavati samo voditelj projekta.",
      "Politika procesa zamjenjuje potrebu za vizualizacijom toka rada.",
    ],
    correct: 0,
    explanation: "Kanban trazi da pravila procesa budu jasna i svima vidljiva.",
  }),
  q({
    id: "kanban-12",
    topic: "Kanban",
    prompt: "Čemu služe povratne informacije kao Kanban praksa?",
    answers: [
      "Redovitom usklađivanju rada i razmjeni znanja.",
      "Zabrani promjena prioriteta tijekom rada.",
      "Automatskom generiranju dokumentacije iz koda.",
      "Otkazivanju sprinta odlukom vlasnika proizvoda.",
    ],
    correct: 0,
    explanation: "Povratne informacije u Kanbanu uključuju redovite kratke sastanke i usklađivanje.",
  }),
  q({
    id: "scrum-kanban-1",
    topic: "Scrum ili Kanban",
    prompt: "Koja je glavna razlika između Scruma i Kanbana?",
    answers: [
      "Scrum radi u vremenski ograničenim sprintovima, a Kanban u kontinuiranom toku rada.",
      "Scrum nema uloge, a Kanban ima Scrum Mastera i vlasnika proizvoda.",
      "Scrum pusta funkcionalnost čim je gotova, a Kanban ceka kraj sprinta.",
      "Scrum je bez sastanaka, a Kanban zahtijeva Sprint Review.",
    ],
    correct: 0,
    explanation: "Scrum je organiziran oko sprintova, a Kanban oko kontinuiranog toka.",
  }),
  q({
    id: "scrum-kanban-2",
    topic: "Scrum ili Kanban",
    prompt: "U kojem pristupu nema zadanih uloga članova tima?",
    answers: ["Kanban.", "Scrum.", "Scrum of Scrums.", "Metoda vodopada."],
    correct: 0,
    explanation: "U bilješkama Kanban nema zadane uloge kao Scrum.",
  }),
  q({
    id: "scrum-kanban-3",
    topic: "Scrum ili Kanban",
    prompt: "Koji pristup je prikladniji za rad u blokovima i stabilniji plan?",
    answers: ["Scrum.", "Kanban.", "Doxygen.", "JavaDoc."],
    correct: 0,
    explanation: "Scrum je strukturiraniji i prikladniji kada se posao može grupirati u cikluse.",
  }),
  q({
    id: "scrumban-1",
    topic: "Scrumban",
    prompt: "Što je Scrumban?",
    answers: [
      "Hibrid Scruma i Kanbana.",
      "Sastanak predstavnika više Scrum timova.",
      "Dokumentacija testiranja u metodi vodopada.",
      "Alat za generiranje dokumentacije iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Scrumban kombinira Scrum strukturu s Kanban fleksibilnoscu.",
  }),
  q({
    id: "scrumban-2",
    topic: "Scrumban",
    prompt: "Što Scrumban preuzima od Scruma?",
    answers: [
      "Strukturu, iterativno planiranje, osvrte, preglede i prioritete.",
      "Potpuno nepostojanje uloga i ciklusa.",
      "Isključivo Kanban kartice i WIP ograničenja.",
      "Dokumentaciju proizvoda i procesa.",
    ],
    correct: 0,
    explanation: "Scrumban zadrzava dio Scrum strukture i planiranja.",
  }),
  q({
    id: "scrumban-3",
    topic: "Scrumban",
    prompt: "Što Scrumban preuzima od Kanbana?",
    answers: [
      "Fleksibilnost, vizualni prikaz toka rada i ograničenje preuzetih zadataka.",
      "Strogo definirane Scrum uloge i obavezne sprintove.",
      "Dokument zahtjeva i opis arhitekture sustava.",
      "Korektivno i preventivno održavanje.",
    ],
    correct: 0,
    explanation: "Od Kanbana preuzima vizualizaciju, tok rada i ograničavanje zadataka.",
  }),
  q({
    id: "scrumban-4",
    topic: "Scrumban",
    prompt: "Za koje timove je Scrumban posebno prikladan?",
    answers: [
      "Za timove kojima trebaju i struktura Scruma i fleksibilnost Kanbana.",
      "Za timove koji zele potpuno izbjeci vizualizaciju rada.",
      "Za timove koji rade isključivo po vodopadnom modelu.",
      "Za timove bez potrebe za prioritetima i ograničenjem zadataka.",
    ],
    correct: 0,
    explanation: "Scrumban se koristi i kao prijelaz iz Scruma u Kanban.",
  }),
  q({
    id: "sos-1",
    topic: "Scrum of Scrums",
    prompt: "Kada se koristi Scrum of Scrums?",
    answers: [
      "Kada je projekt prevelik za jedan Scrum tim pa treba uskladiti više timova.",
      "Kada jedan tim treba održati Sprint Retrospective.",
      "Kada Product Backlog nema dovoljno detalja.",
      "Kada se dokumentacija generira iz komentara u kodu.",
    ],
    correct: 0,
    explanation: "Scrum of Scrums koordinira rad više Scrum timova.",
  }),
  q({
    id: "sos-2",
    topic: "Scrum of Scrums",
    prompt: "Tko sudjeluje na Scrum of Scrums sastanku?",
    answers: [
      "Predstavnici svakog Scrum tima.",
      "Svi krajnji korisnici proizvoda.",
      "Samo vlasnik proizvoda i nitko drugi.",
      "Samo sistemski administratori.",
    ],
    correct: 0,
    explanation: "Ne sudjeluju svi članovi, nego jedan ili više predstavnika svakog tima.",
  }),
  q({
    id: "sos-3",
    topic: "Scrum of Scrums",
    prompt: "Koje pitanje pripada Scrum of Scrums sastanku?",
    answers: [
      "Što će vas tim raditi do idućeg sastanka što može utjecati na druge timove?",
      "Koji je programski okvir koristen u dokumentaciji koda?",
      "Koji su poslovni ciljevi dokumenta zahtjeva?",
      "Koji je WIP limit za svaki Kanban stupac?",
    ],
    correct: 0,
    explanation: "Scrum of Scrums se fokusira na ovisnosti i utjecaj rada jednog tima na druge.",
  }),
  q({
    id: "docs-1",
    topic: "Dokumentacija",
    prompt: "Koja je osnovna podjela dokumentacije?",
    answers: [
      "Dokumentacija proizvoda i dokumentacija procesa.",
      "Scrum dokumentacija i Kanban dokumentacija.",
      "Preventivna i adaptivna dokumentacija.",
      "HTML dokumentacija i PDF dokumentacija.",
    ],
    correct: 0,
    explanation: "Bilješke dokumentaciju dijele na dokumentaciju proizvoda i procesa.",
  }),
  q({
    id: "docs-2",
    topic: "Dokumentacija",
    prompt: "Što opisuje dokumentacija proizvoda?",
    answers: [
      "Nastali proizvod i upute za rukovanje.",
      "Samo raspored sastanaka razvojnog tima.",
      "Samo poslovnu korespondenciju i izvještaje.",
      "Isključivo WIP ograničenja i Kanban stupce.",
    ],
    correct: 0,
    explanation: "Dokumentacija proizvoda opisuje proizvod i daje upute za rukovanje.",
  }),
  q({
    id: "docs-3",
    topic: "Dokumentacija",
    prompt: "Što opisuje dokumentacija procesa?",
    answers: [
      "Aktivnosti vezane uz razvoj proizvoda.",
      "Samo način korištenja proizvoda od strane krajnjih korisnika.",
      "Samo strukturu koda i komentare JavaDoca.",
      "Samo gotove inkremente u Scrum sprintovima.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati planove, rasporede, izvještaje i slicne aktivnosti razvoja.",
  }),
  q({
    id: "docs-4",
    topic: "Sistemska dokumentacija",
    prompt: "Što je sistemska dokumentacija?",
    answers: [
      "Dokumenti koji opisuju sustav, njegove dijelove i temeljnu tehnologiju.",
      "Upute za krajnje korisnike bez tehničkih detalja.",
      "Samo marketinski opis proizvoda.",
      "Popis Kanban kartica za trenutni tok rada.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija je tehnički orijentirana i opisuje sustav.",
  }),
  q({
    id: "docs-5",
    topic: "Sistemska dokumentacija",
    prompt: "Što pripada sistemskoj dokumentaciji?",
    answers: [
      "Dokument zahtjeva, opis arhitekture, opis koda i dokumentacija testiranja.",
      "FAQ, video upute i portali za pomoć krajnjim korisnicima.",
      "Samo bilješke sa sastanaka i poslovna korespondencija.",
      "Samo Product Backlog i Sprint Backlog.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija uključuje zahtjeve, arhitekturu, kod, validaciju i testiranje.",
  }),
  q({
    id: "docs-6",
    topic: "Sistemska dokumentacija",
    prompt: "Što opisuje dokument zahtjeva?",
    answers: [
      "Što proizvod treba raditi i koje funkcionalnosti treba imati.",
      "Koliko je zadataka ostalo u trenutnom sprintu.",
      "Koji su komentari potrebni za JavaDoc tagove.",
      "Kako krajnji korisnik pristupa portalu za pomoć.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva sadrzi funkcionalnosti, poslovna pravila, korisničke price i slučajeve.",
  }),
  q({
    id: "docs-7",
    topic: "Sistemska dokumentacija",
    prompt: "Što treba biti navedeno u dokumentu zahtjeva?",
    answers: [
      "Uloge, ciljevi, pretpostavke, korisničke price, interakcija i pitanja.",
      "Samo popis programskih jezika i verzija alata.",
      "Samo tri pitanja za Daily Scrum.",
      "Samo WIP limit i stupci Kanban ploce.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva treba jasno opisati svrhu, značajke, ponasanje i kontekst proizvoda.",
  }),
  q({
    id: "docs-8",
    topic: "Sistemska dokumentacija",
    prompt: "Što navodi dokumentacija arhitekture softvera?",
    answers: [
      "Najvažnije arhitekturne odluke i prikaz rješenja.",
      "Samo krajnje korisničke upute za rad.",
      "Samo dnevni plan rada u sprintu.",
      "Samo broj testova koji nisu uspjeli.",
    ],
    correct: 0,
    explanation: "Arhitekturna dokumentacija opisuje odluke, principe, rješenja i dijagrame.",
  }),
  q({
    id: "docs-9",
    topic: "Sistemska dokumentacija",
    prompt: "Kome je prvenstveno namijenjena dokumentacija o kodu?",
    answers: [
      "Developerima.",
      "Isključivo krajnjim korisnicima.",
      "Samo vlasniku proizvoda.",
      "Predstavnicima Scrum of Scrums sastanka.",
    ],
    correct: 0,
    explanation: "Dokumentacija o kodu opisuje način rada koda i tehničke detalje.",
  }),
  q({
    id: "docs-10",
    topic: "Dokumentacija testiranja",
    prompt: "Što opisuje strategija testiranja?",
    answers: [
      "Opci pristup testiranju.",
      "Što se testira i u kojem trenutku.",
      "Koji korisnik je odgovoran za funkcionalnost.",
      "Koji je idealni burn-down grafikon.",
    ],
    correct: 0,
    explanation: "Strategija testiranja opisuje pristup, strukturu, resurse i prioritete.",
  }),
  q({
    id: "docs-11",
    topic: "Dokumentacija testiranja",
    prompt: "Što opisuje plan testiranja?",
    answers: [
      "Što se treba testirati i kada.",
      "Dugorocnu viziju proizvoda.",
      "Korisničke video upute.",
      "Redoslijed stavki u Product Backlogu.",
    ],
    correct: 0,
    explanation: "Plan testiranja definira stavke, metode, vremenske okvire, uloge i zaduzenja.",
  }),
  q({
    id: "docs-12",
    topic: "Dokumentacija testiranja",
    prompt: "Što radi specifikacija testnih slučajeva?",
    answers: [
      "Opisuje postupke kojima se verificira svaka znacajka.",
      "Generira HTML dokumentaciju za Java klase.",
      "Prikazuje preostali posao kroz vrijeme.",
      "Određuje tko sudjeluje u Scrum of Scrums sastanku.",
    ],
    correct: 0,
    explanation: "Specifikacije testnih slučajeva povezuju značajke s postupcima provjere.",
  }),
  q({
    id: "docs-13",
    topic: "Korisnička dokumentacija",
    prompt: "Kome je namijenjena korisnička dokumentacija?",
    answers: [
      "Krajnjim korisnicima i sistemskim administratorima.",
      "Samo programerima koji održavaju kod.",
      "Samo Scrum Masteru i vlasniku proizvoda.",
      "Samo testnom timu za specifikaciju testova.",
    ],
    correct: 0,
    explanation: "Korisnička dokumentacija mora biti prilagođena znanju korisnika.",
  }),
  q({
    id: "docs-14",
    topic: "Korisnička dokumentacija",
    prompt: "Što može sadržavati online korisnička dokumentacija?",
    answers: [
      "Česta pitanja, video upute, ugrađenu pomoć i portale za pomoć.",
      "Samo arhitekturne dijagrame i sigurnosne mjere.",
      "Samo dokument zahtjeva i poslovna pravila.",
      "Samo Sprint Backlog i Daily Scrum zapisnik.",
    ],
    correct: 0,
    explanation: "Online dokumentacija treba pomagati korisniku u korištenju proizvoda.",
  }),
  q({
    id: "docs-14a",
    topic: "Korisnička dokumentacija",
    prompt: "Zašto je kod korisničke dokumentacije važno prikupljati povratne informacije korisnika?",
    answers: [
      "Da bi se dokumentacija mogla stalno ažurirati i poboljšavati prema stvarnim potrebama korisnika.",
      "Da bi korisnici mogli mijenjati arhitekturu sustava bez razvojnog tima.",
      "Da bi se izbjeglo pisanje sistemske dokumentacije.",
      "Da bi se Product Backlog mogao zamijeniti korisničkim uputama.",
    ],
    correct: 0,
    explanation: "Povratne informacije pomažu da korisnička dokumentacija ostane korisna i razumljiva.",
  }),
  q({
    id: "docs-15",
    topic: "Dokumentacija procesa",
    prompt: "Što pripada dokumentaciji procesa?",
    answers: [
      "Projektni planovi, rasporedi testiranja, izvještaji, standardi i bilješke sa sastanaka.",
      "Samo upute za krajnje korisnike.",
      "Samo komentari iz izvornog koda.",
      "Samo Kanban kartice i Scrum događaji.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati aktivnosti i organizaciju razvoja.",
  }),
  q({
    id: "docs-15a",
    topic: "Dokumentacija procesa",
    prompt: "Što su planovi, procjene i rasporedi u dokumentaciji procesa?",
    answers: [
      "Dokumenti koji obično nastaju prije razvoja, ali se mogu prilagođavati tijekom izrade softvera.",
      "Komentari u kodu iz kojih JavaDoc generira HTML dokumentaciju.",
      "Popis zadataka u sprintu koji pripada isključivo razvojnom timu.",
      "Definicija gotovog koja vrijedi za više Scrum timova.",
    ],
    correct: 0,
    explanation: "Planovi, procjene i rasporedi pomažu organizirati razvoj i mogu se mijenjati tijekom rada.",
  }),
  q({
    id: "docs-15b",
    topic: "Dokumentacija procesa",
    prompt: "Čemu služe izvještaji i metrika u dokumentaciji procesa?",
    answers: [
      "Praćenju korištenja vremena i kadra tijekom razvoja softvera.",
      "Opisivanju parametara i povratnih vrijednosti Java metoda.",
      "Ogranicavanju broja zadataka u Kanban stupcu.",
      "Odredjivanju je li sprint moguće otkazati.",
    ],
    correct: 0,
    explanation: "Izvještaji i metrika daju uvid u resurse i tijek razvoja.",
  }),
  q({
    id: "docs-16",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja o količini dokumentacije je najtočnija?",
    answers: [
      "Treba je biti dovoljno, ali ne prekratko ni preopsežno.",
      "Uvijek mora biti što opsežnija, bez obzira na ponavljanje.",
      "Treba je izbjegavati jer usporava razvoj.",
      "Dokumentacija je konačna čim se proizvod pusti u pogon.",
    ],
    correct: 0,
    explanation: "Premalo dokumentacije stvara greške, a previše stvara ponavljanje i opterećenje.",
  }),
  q({
    id: "docs-16a",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja najbolje opisuje status dokumentacije kroz vrijeme?",
    answers: [
      "Dokumentacija nikad nije konačna, nego se stalno nadopunjuje.",
      "Dokumentacija je zaključana čim se završi analiza zahtjeva.",
      "Dokumentacija se piše samo nakon puštanja proizvoda u pogon.",
      "Dokumentacija se u agilnim metodama potpuno izbacuje.",
    ],
    correct: 0,
    explanation: "Bilješke navode da se dokumentacija stalno nadopunjuje.",
  }),
  q({
    id: "docs-17",
    topic: "Dokumentacija",
    prompt: "Kakva je kvalitetna dokumentacija?",
    answers: [
      "Precizna, jasna i relevantna.",
      "Što duza, bez obzira na ponavljanje.",
      "Napisana samo nakon završetka projekta.",
      "Namijenjena isključivo voditelju projekta.",
    ],
    correct: 0,
    explanation: "Bilješke naglasavaju preciznost, jasnocu i relevantnost.",
  }),
  q({
    id: "docs-17a",
    topic: "Dokumentacija",
    prompt: "Tko doprinosi sastavljanju dokumentacije prema bilješkama?",
    answers: [
      "Svi članovi tima koji su na bilo koji način sudjelovali u razvoju proizvoda.",
      "Samo osoba koja piše kod.",
      "Samo krajnji korisnici nakon završene isporuke.",
      "Samo Scrum Master tijekom Daily Scruma.",
    ],
    correct: 0,
    explanation: "Dokumentacija je rezultat zajednickog rada i komentara više sudionika.",
  }),
  q({
    id: "docs-18",
    topic: "Generatori dokumentacije",
    prompt: "Čemu služe generatori dokumentacije?",
    answers: [
      "Laksem i brzem stvaranju dokumentacije, često iz komentara u kodu.",
      "Upravljanju WIP limitima na Kanban ploci.",
      "Odrzavanju dnevnih Scrum sastanaka.",
      "Pretvaranju zahtjeva u arhitekturu sustava.",
    ],
    correct: 0,
    explanation: "Generatori dokumentacije automatiziraju dio izrade dokumentacije.",
  }),
  q({
    id: "docs-19",
    topic: "Generatori dokumentacije",
    prompt: "Što je Doxygen?",
    answers: [
      "Alat za generiranje dokumentacije, primarno za C++, ali podržava i druge jezike.",
      "Scrum događaj za pregled inkrementa.",
      "Kanban praksa za ograničavanje rada u tijeku.",
      "Vrsta korisničke dokumentacije za FAQ.",
    ],
    correct: 0,
    explanation: "Doxygen generira dokumentaciju iz komentara u kodu.",
  }),
  q({
    id: "docs-19a",
    topic: "Generatori dokumentacije",
    prompt: "Što Doxygen može napraviti osim generiranja tekstualne dokumentacije?",
    answers: [
      "Prikazati strukturu koda i odnose medju elementima pomoću automatski generiranih grafova.",
      "Održati Sprint Review i prilagoditi Product Backlog.",
      "Ograniciti broj Kanban kartica u stupcu.",
      "Odrediti redoslijed implementacije segmenata proizvoda.",
    ],
    correct: 0,
    explanation: "Bilješke navode da Doxygen može izvuci strukturu koda i prikazati odnose.",
  }),
  q({
    id: "docs-20",
    topic: "Generatori dokumentacije",
    prompt: "Što JavaDoc generira?",
    answers: [
      "HTML dokumentaciju za Java kod iz komentara.",
      "Burn-down grafikon za Scrum sprint.",
      "Product Backlog iz korisničkih priča.",
      "Dokument zahtjeva iz Kanban kartica.",
    ],
    correct: 0,
    explanation: "JavaDoc je vezan uz dokumentiranje Java koda.",
  }),
  q({
    id: "docs-20a",
    topic: "Generatori dokumentacije",
    prompt: "Koje dvije vrste komentara se spominju kod JavaDoca?",
    answers: [
      "Komentari na razini klase i komentari na razini članova klase.",
      "Komentari Product Backloga i komentari Sprint Backloga.",
      "Komentari sistemske dokumentacije i komentari korisničke dokumentacije.",
      "Komentari WIP-a i komentari Kanban stupaca.",
    ],
    correct: 0,
    explanation: "JavaDoc razlikuje komentare za klasu i za članove poput atributa i metoda.",
  }),
  q({
    id: "docs-21",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje parametar metode?",
    answers: ["@param", "@return", "@version", "@author"],
    correct: 0,
    explanation: "@param se koristi za opis parametra metode.",
  }),
  q({
    id: "docs-22",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje povratnu vrijednost?",
    answers: ["@return", "@throws", "@author", "@version"],
    correct: 0,
    explanation: "@return opisuje povratnu vrijednost metode.",
  }),
  q({
    id: "docs-23",
    topic: "Generatori dokumentacije",
    prompt: "Koji alati su navedeni kao drugi generatori dokumentacije?",
    answers: [
      "Sphinx, Dr. Explain i PHPDocumentator.",
      "Scrum, Kanban i Scrumban.",
      "Product Backlog, Sprint Backlog i Inkrement.",
      "Waterfall, RAD i DevOps.",
    ],
    correct: 0,
    explanation: "Bilješke navode Sphinx, Dr. Explain i PHPDocumentator kao dodatne alate.",
  }),
];
