const optionIds = ["a", "b", "c", "d"];

function source({ title, page, hint }) {
  return {
    title,
    page,
    pdfPage: page <= 36 ? page - 10 : page - 26,
    hint,
  };
}

const sources = {
  metode: source({
    title: "1. Metode razvoja softvera",
    page: 11,
    hint: "Uvod u svrhu odabira metode razvoja.",
  }),
  waterfallIntro: source({
    title: "1.1. Metoda vodopada",
    page: 11,
    hint: "Osnovna ideja, redoslijed i prikladnost metode vodopada.",
  }),
  waterfallRequirements: source({
    title: "1.1. Metoda vodopada - Analiza zahtjeva",
    page: 12,
    hint: "Prva faza u kojoj se definiraju zahtjevi i funkcionalnosti.",
  }),
  waterfallDesign: source({
    title: "1.1. Metoda vodopada - Dizajn sustava",
    page: 12,
    hint: "Faza u kojoj se zahtjevi pretvaraju u arhitekturu sustava.",
  }),
  waterfallImplementation: source({
    title: "1.1. Metoda vodopada - Implementacija i testiranje jedinica",
    page: 12,
    hint: "Faza izrade programskog koda i zasebnog testiranja jedinica.",
  }),
  waterfallIntegration: source({
    title: "1.1. Metoda vodopada - Integracija i testiranje sustava",
    page: 13,
    hint: "Faza povezivanja modula i provjere cjelovitog sustava.",
  }),
  waterfallRelease: source({
    title: "1.1. Metoda vodopada - Puštanje u pogon",
    page: 13,
    hint: "Isporuka sustava nakon pozitivnih rezultata testiranja.",
  }),
  waterfallMaintenance: source({
    title: "1.1. Metoda vodopada - Održavanje",
    page: 13,
    hint: "Rad nakon isporuke: greške, prilagodbe, usavršavanje i prevencija.",
  }),
  waterfallProsCons: source({
    title: "1.1. Metoda vodopada - Prednosti i nedostaci",
    page: 14,
    hint: "Prednosti jasnog slijeda i slabosti kod promjena zahtjeva.",
  }),
  agile: source({
    title: "1.2. Agilne metode",
    page: 14,
    hint: "Agilni manifest, vrijednosti i iterativni razvoj.",
  }),
  scrum: source({
    title: "1.2.1. Scrum",
    page: 15,
    hint: "Scrum kao razvojni okvir, njegove uloge, događaji i artefakti.",
  }),
  scrumRoles: source({
    title: "1.2.1.1. Uloge u Scrum timu",
    page: 16,
    hint: "Scrum Master, vlasnik proizvoda i razvojni tim.",
  }),
  scrumArtifacts: source({
    title: "1.2.1.2. Artefakti",
    page: 17,
    hint: "Product Backlog, Sprint Backlog, inkrement, definicija gotovog i burn-down grafikon.",
  }),
  scrumEvents: source({
    title: "1.2.1.3. Događaji u Scrumu",
    page: 20,
    hint: "Sprint, planiranje, Daily Scrum, review i retrospektiva.",
  }),
  kanban: source({
    title: "1.2.2. Kanban",
    page: 25,
    hint: "Vizualizacija rada, WIP ograničenja, tok rada i Kanban ploča.",
  }),
  scrumKanban: source({
    title: "1.2.2. Scrum ili Kanban",
    page: 32,
    hint: "Usporedba sprintova, kontinuiranog toka, uloga i promjena.",
  }),
  scrumban: source({
    title: "1.2.3. Scrumban",
    page: 34,
    hint: "Hibrid Scruma i Kanbana.",
  }),
  scrumOfScrums: source({
    title: "1.2.4. Scrum of Scrums",
    page: 35,
    hint: "Koordinacija više Scrum timova.",
  }),
  docs: source({
    title: "3. Dokumentacija",
    page: 53,
    hint: "Podjela dokumentacije proizvoda i procesa.",
  }),
  systemDocs: source({
    title: "3.1.1. Sistemska dokumentacija",
    page: 53,
    hint: "Zahtjevi, arhitektura, kod, validacija i testiranje.",
  }),
  userDocs: source({
    title: "3.1.2. Korisnička dokumentacija",
    page: 55,
    hint: "Upute za krajnje korisnike i sistemske administratore.",
  }),
  processDocs: source({
    title: "3.1.3. Dokumentacija procesa",
    page: 54,
    hint: "Planovi, rasporedi, izvještaji, standardi i bilješke razvoja.",
  }),
  docQuality: source({
    title: "3.2. Kvaliteta dokumentacije",
    page: 56,
    hint: "Dokumentacija treba biti jasna, precizna, relevantna i stalno nadopunjavana.",
  }),
  docGenerators: source({
    title: "3.3. Generatori dokumentacije",
    page: 56,
    hint: "Doxygen, JavaDoc i drugi alati za generiranje dokumentacije.",
  }),
};

function sourceForQuestion(id, topic) {
  if (id.startsWith("waterfall-6") || id === "waterfall-7" || id === "waterfall-8") {
    return sources.waterfallRequirements;
  }
  if (id === "waterfall-9" || id === "waterfall-10" || id === "waterfall-11") {
    return sources.waterfallDesign;
  }
  if (id === "waterfall-12" || id === "waterfall-13") {
    return sources.waterfallImplementation;
  }
  if (id === "waterfall-14" || id === "waterfall-15") {
    return sources.waterfallIntegration;
  }
  if (id === "waterfall-16") {
    return sources.waterfallRelease;
  }
  if (id === "waterfall-17" || id === "waterfall-18" || id === "waterfall-19" || id === "waterfall-20") {
    return sources.waterfallMaintenance;
  }
  if (id === "waterfall-21" || id === "waterfall-22" || id === "waterfall-23") {
    return sources.waterfallProsCons;
  }
  if (id.startsWith("waterfall-")) {
    return sources.waterfallIntro;
  }
  if (id.startsWith("agile-")) {
    return sources.agile;
  }
  if (id.startsWith("scrum-artifacts-")) {
    return sources.scrumArtifacts;
  }
  if (id.startsWith("scrum-events-")) {
    return sources.scrumEvents;
  }
  if (id.startsWith("scrum-kanban-")) {
    return sources.scrumKanban;
  }
  if (id.startsWith("scrum-") && topic === "Scrum uloge") {
    return sources.scrumRoles;
  }
  if (id.startsWith("scrum-")) {
    return sources.scrum;
  }
  if (id.startsWith("kanban-")) {
    return sources.kanban;
  }
  if (id.startsWith("scrumban-")) {
    return sources.scrumban;
  }
  if (id.startsWith("sos-")) {
    return sources.scrumOfScrums;
  }
  if (topic === "Sistemska dokumentacija" || topic === "Dokumentacija testiranja") {
    return sources.systemDocs;
  }
  if (topic === "Korisnička dokumentacija") {
    return sources.userDocs;
  }
  if (topic === "Dokumentacija procesa") {
    return sources.processDocs;
  }
  if (topic === "Generatori dokumentacije") {
    return sources.docGenerators;
  }
  if (id === "docs-16" || id === "docs-16a" || id === "docs-17" || id === "docs-17a") {
    return sources.docQuality;
  }
  if (id.startsWith("docs-")) {
    return sources.docs;
  }
  return sources.metode;
}

function q({ id, topic, prompt, answers, correct, explanation, source: explicitSource }) {
  return {
    id,
    topic,
    prompt,
    options: answers.map((text, index) => ({ id: optionIds[index], text })),
    correctId: optionIds[correct],
    explanation,
    source: explicitSource ?? sourceForQuestion(id, topic),
  };
}

export const questions = [
  q({
    id: "metode-1",
    topic: "Metode razvoja",
    prompt: "Što najbolje opisuje metode razvoja softvera?",
    answers: [
      "Organizacijski pristupi prema kojima se planira, razvija i kontrolira rad na softveru.",
      "Skup pravila kojima se određuje samo redoslijed pisanja programskog koda.",
      "Tehnički postupci kojima se razvoj svodi prvenstveno na testiranje gotovog sustava.",
      "Dokumentacijski okvir kojim se opisuje proizvod nakon što je razvoj završen.",
    ],
    correct: 0,
    explanation: "Metode razvoja govore kako se organizira rad na softverskom projektu.",
  }),
  q({
    id: "metode-2",
    topic: "Metode razvoja",
    prompt: "Koja tvrdnja najbolje objašnjava zašto se ne razvija svaki softver isto?",
    answers: [
      "Zato što izbor pristupa ovisi o proizvodu, korisnicima, timu i načinu rada.",
      "Zato što se metoda bira prvenstveno prema tome koliko brzo tim želi početi pisati kod.",
      "Zato što svaki projekt ima isti proces, ali se mijenja samo količina dokumentacije.",
      "Zato što je izbor metode određen isključivo tehnologijom u kojoj se sustav implementira.",
    ],
    correct: 0,
    explanation: "Metoda se bira prema kontekstu projekta, a ne postoji jedan univerzalan pristup.",
  }),
  q({
    id: "metode-3",
    topic: "Metode razvoja",
    prompt: "Koji je cilj metode razvoja softvera?",
    answers: [
      "Uciniti razvoj uređenim, učinkovitim i predvidivim.",
      "Urediti razvoj tako da se sve odluke donesu tek nakon implementacije.",
      "Učiniti razvoj predvidivim tako da se promjene zahtjeva uvijek blokiraju.",
      "Smanjiti razvoj na pisanje dokumentacije prije bilo kakve provjere softvera.",
    ],
    correct: 0,
    explanation: "U bilješkama je cilj metoda razvoja uređen, učinkovit i predvidiv razvoj.",
  }),
  q({
    id: "metode-4",
    topic: "Metode razvoja",
    prompt: "Koja recenica najbolje opisuje svrhu predmeta iz bilješki?",
    answers: [
      "Naučiti kako se softver planira, razvija, testira, dokumentira i modelira u praksi.",
      "Naučiti kako se softver planira i dokumentira, ali bez naglaska na testiranje i modeliranje.",
      "Naučiti kako se softver razvija kroz metode, ali bez povezivanja s praktičnim radom na sustavu.",
      "Naučiti primarno alate za dokumentiranje koda, uz manji naglasak na razvojni proces.",
    ],
    correct: 0,
    explanation: "Svrha predmeta je shvatiti prakticni proces nastanka softvera i informacijskih sustava.",
  }),
  q({
    id: "waterfall-1",
    topic: "Vodopad",
    prompt: "Koja tvrdnja najtocnije opisuje metodu vodopada?",
    answers: [
      "Linearan i sekvencijalan model u kojem se faze izvode jedna nakon druge.",
      "Linearan model u kojem se faze mogu često vraćati unatrag bez većeg utjecaja na plan.",
      "Sekvencijalan model u kojem se implementacija započinje prije potpunog definiranja zahtjeva.",
      "Model s jasno definiranim fazama, ali s kontinuiranom isporukom nakon svake male promjene.",
    ],
    correct: 0,
    explanation: "Vodopad je linearan i sekvencijalan model razvoja.",
  }),
  q({
    id: "waterfall-1a",
    topic: "Vodopad",
    prompt: "Koja tvrdnja o nastanku metode vodopada odgovara bilješkama?",
    answers: [
      "Riječ je o jednoj od najstarijih metoda, povezanoj s Winstonom W. Royceom i 1970. godinom.",
      "Riječ je o starijoj metodi povezanoj s Royceom, ali se u bilješkama smješta nakon agilnih metoda.",
      "Riječ je o modelu koji je nastao kao reakcija na Scrum i iterativni razvoj.",
      "Riječ je o metodi koja se razvila iz proizvodnog toka, ali se u softveru koristi tek za dokumentaciju.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je metoda vodopada najstarija metoda i povezuju je s Royceom 1970.",
  }),
  q({
    id: "waterfall-2",
    topic: "Vodopad",
    prompt: "Što znači da je vodopad sekvencijalan?",
    answers: [
      "Da svaka faza slijedi nakon prethodne i ne preskace se redoslijed.",
      "Da se faze izvode redom, ali se nakon svake iteracije vraćaju na početak.",
      "Da se faze mogu djelomično preklapati, ali uvijek moraju završiti u istom sprintu.",
      "Da redoslijed postoji, ali se faze smiju preskakati ako su zahtjevi dovoljno jasni.",
    ],
    correct: 0,
    explanation: "Sekvencijalnost znači rad po unaprijed određenom slijedu.",
  }),
  q({
    id: "waterfall-3",
    topic: "Vodopad",
    prompt: "Za kakve projekte je metoda vodopada najprikladnija?",
    answers: [
      "Za projekte s jasnim i stabilnim zahtjevima koji se ne mijenjaju često.",
      "Za projekte u kojima su zahtjevi djelomično poznati, ali se očekuju česte promjene opsega.",
      "Za projekte u kojima se arhitektura planira naknadno, nakon prve isporuke korisniku.",
      "Za projekte u kojima tim želi često isporučivati male inkremente bez fiksnog slijeda faza.",
    ],
    correct: 0,
    explanation: "Vodopad bolje funkcionira kada su zahtjevi unaprijed poznati i stabilni.",
  }),
  q({
    id: "waterfall-4",
    topic: "Vodopad",
    prompt: "Koliko faza ima metoda vodopada prema bilješkama?",
    answers: ["6", "4", "5", "7"],
    correct: 0,
    explanation: "Bilješke navode sest faza metode vodopada.",
  }),
  q({
    id: "waterfall-5",
    topic: "Vodopad",
    prompt: "Koji je tocan redoslijed prvih triju faza metode vodopada?",
    answers: [
      "Analiza zahtjeva, dizajn sustava, implementacija i testiranje jedinica.",
      "Dizajn sustava, analiza zahtjeva, integracija i testiranje sustava.",
      "Implementacija, analiza zahtjeva, puštanje u pogon.",
      "Analiza zahtjeva, integracija sustava, dizajn sustava.",
    ],
    correct: 0,
    explanation: "Vodopad prvo definira što sustav treba raditi, zatim kako će biti strukturiran, pa prelazi u kod.",
  }),
  q({
    id: "waterfall-6",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara analiza zahtjeva?",
    answers: [
      "Što sustav treba raditi?",
      "Kako će zahtjevi biti pretvoreni u arhitekturu sustava?",
      "Jesu li implementirane jedinice ispravno povezane u cjelinu?",
      "Koje promjene treba napraviti nakon što je sustav već u uporabi?",
    ],
    correct: 0,
    explanation: "Analiza zahtjeva definira potrebe, zahtjeve i funkcionalnosti sustava.",
  }),
  q({
    id: "waterfall-7",
    topic: "Vodopad",
    prompt: "Tko sudjeluje u fazi analize zahtjeva?",
    answers: [
      "Naručitelj softvera i razvojni tim.",
      "Samo razvojni tim bez naručitelja.",
      "Naručitelj i testni tim tek nakon što je sustav implementiran.",
      "Razvojni tim i korisnici tek u fazi puštanja u pogon.",
    ],
    correct: 0,
    explanation: "U analizi zahtjeva sudjeluju naručitelj i razvojni tim kako bi se razumio problem.",
  }),
  q({
    id: "waterfall-8",
    topic: "Vodopad",
    prompt: "Koji je rezultat faze analize zahtjeva?",
    answers: [
      "Dokument sa zahtjevima.",
      "Arhitektura sustava.",
      "Skup testiranih modula.",
      "Plan integracije i isporuke sustava.",
    ],
    correct: 0,
    explanation: "Dokument sa zahtjevima je osnova za daljnji razvoj.",
  }),
  q({
    id: "waterfall-9",
    topic: "Vodopad",
    prompt: "Na koje pitanje odgovara dizajn sustava?",
    answers: [
      "Kako će sustav biti strukturiran i izveden?",
      "Što sustav treba raditi iz perspektive zahtjeva korisnika?",
      "Jesu li pojedine programske jedinice ispravno implementirane?",
      "Koje prilagodbe treba napraviti nakon puštanja sustava u rad?",
    ],
    correct: 0,
    explanation: "Dizajn sustava pretvara zahtjeve u strukturu pogodnu za implementaciju.",
  }),
  q({
    id: "waterfall-10",
    topic: "Vodopad",
    prompt: "Što je rezultat faze dizajna sustava?",
    answers: [
      "Arhitektura sustava.",
      "Dokument sa zahtjevima.",
      "Skup implementiranih i jedinicno testiranih modula.",
      "Plan održavanja nakon puštanja u pogon.",
    ],
    correct: 0,
    explanation: "U PDF-u je rezultat faze dizajna sustava arhitektura sustava.",
  }),
  q({
    id: "waterfall-11",
    topic: "Vodopad",
    prompt: "Kako treba razumjeti hardverske komponente u dizajnu sustava?",
    answers: [
      "Kao tehničku osnovu na kojoj sustav radi, ako je relevantna za taj projekt.",
      "Kao obavezne fizicke dijelove bez kojih softver ne može postojati.",
      "Kao dijelove arhitekture koji se uvijek moraju zasebno implementirati u kodu.",
      "Kao popis korisničkih funkcionalnosti koje se tek trebaju definirati u zahtjevima.",
    ],
    correct: 0,
    explanation: "Ako hardver nije bitan za projekt, fokus dizajna ostaje na strukturi i arhitekturi softvera.",
  }),
  q({
    id: "waterfall-12",
    topic: "Vodopad",
    prompt: "Što se događa u fazi implementacije i testiranja jedinica?",
    answers: [
      "Plan sustava prelazi u programski kod, a jedinice se zasebno testiraju.",
      "Zahtjevi se pretvaraju u arhitekturu sustava, a kod se piše tek kasnije.",
      "Moduli se povezuju u cjelinu prije nego što se pojedinačno provjere.",
      "Gotov sustav se isporučuje korisniku nakon završnog prihvatnog testiranja.",
    ],
    correct: 0,
    explanation: "U toj fazi sustav se razvija po manjim cjelinama i svaka se provjerava zasebno.",
  }),
  q({
    id: "waterfall-13",
    topic: "Vodopad",
    prompt: "Koji je krajnji rezultat implementacije i testiranja jedinica?",
    answers: [
      "Skup modula koji su testirani kao jedinice.",
      "Arhitekturni model koji tek opisuje buduću strukturu sustava.",
      "Skup modula koji su povezani, ali nisu prethodno zasebno provjereni.",
      "Integrirani sustav koji je već spreman za puštanje u pogon.",
    ],
    correct: 0,
    explanation: "PDF navodi da je rezultat te faze skup testiranih modula.",
  }),
  q({
    id: "waterfall-14",
    topic: "Vodopad",
    prompt: "Što je cilj integracije i testiranja sustava?",
    answers: [
      "Provjeriti rade li jedinice zajedno kao cjelovit sustav.",
      "Provjeriti svaku jedinicu izolirano prije nego se poveže s drugima.",
      "Pretvoriti dokument zahtjeva u arhitekturni opis sustava.",
      "Isporučiti sustav korisniku bez dodatnog povezivanja modula.",
    ],
    correct: 0,
    explanation: "Moduli se povezuju u sustav i testira se cjelina.",
  }),
  q({
    id: "waterfall-15",
    topic: "Vodopad",
    prompt: "Što znači da je integracija inkrementalna?",
    answers: [
      "Da se provodi u više koraka, postupnim povezivanjem dijelova.",
      "Da se cijeli sustav spaja odjednom bez medjukoraka.",
      "Da se svaka jedinica testira samo izolirano i nikad kao dio cjeline.",
      "Da se svaka faza razvoja preskače čim se pronađe prva greška.",
    ],
    correct: 0,
    explanation: "Inkrementalna integracija znači povezivanje u postupnim koracima.",
  }),
  q({
    id: "waterfall-16",
    topic: "Vodopad",
    prompt: "Kada se provodi puštanje u pogon?",
    answers: [
      "Nakon što su rezultati testiranja pozitivni.",
      "Nakon implementacije jedinica, ali prije integracije u cjelovit sustav.",
      "Nakon analize zahtjeva, čim je dokument zahtjeva prihvaćen.",
      "Nakon dizajna sustava, prije pisanja programskog koda.",
    ],
    correct: 0,
    explanation: "Puštanje u pogon dolazi nakon uspjesnog testiranja.",
  }),
  q({
    id: "waterfall-17",
    topic: "Vodopad",
    prompt: "Koja faza počinje nakon što je sustav pusten u uporabu?",
    answers: [
      "Održavanje.",
      "Dizajn sustava.",
      "Integracija i završno testiranje.",
      "Integracija i testiranje sustava.",
    ],
    correct: 0,
    explanation: "Održavanje počinje nakon isporuke ili puštanja sustava u uporabu.",
  }),
  q({
    id: "waterfall-18",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja znači dodavanje i poboljšavanje funkcionalnosti?",
    answers: [
      "Usavrsavanje.",
      "Korektivno održavanje.",
      "Adaptivno održavanje.",
      "Preventivno održavanje.",
    ],
    correct: 0,
    explanation: "Usavrsavanje se odnosi na nadogradnju funkcionalnosti i nove verzije.",
  }),
  q({
    id: "waterfall-19",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja se odnosi na ispravljanje grešaka koje nisu ranije otkrivene?",
    answers: [
      "Korektivno održavanje.",
      "Preventivno održavanje.",
      "Adaptivno održavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Korektivno održavanje ispravlja greške i nedostatke.",
  }),
  q({
    id: "waterfall-20",
    topic: "Vodopad",
    prompt: "Koja vrsta održavanja služi sprječavanju predvidivih buducih grešaka?",
    answers: [
      "Preventivno održavanje.",
      "Korektivno održavanje.",
      "Adaptivno održavanje.",
      "Usavrsavanje.",
    ],
    correct: 0,
    explanation: "Preventivno održavanje pokušava spriječiti probleme prije nego nastanu.",
  }),
  q({
    id: "waterfall-21",
    topic: "Vodopad",
    prompt: "Koja je prednost metode vodopada?",
    answers: [
      "Faze su jasno definirane i lako ih je pratiti.",
      "Promjene zahtjeva se mogu uvoditi, ali samo ako ne mijenjaju već završene faze.",
      "Testiranje je jednostavnije jer se planira nakon što su prethodne faze jasno završene.",
      "Dokumentacija je manja jer se većina znanja prenosi kroz svakodnevnu komunikaciju.",
    ],
    correct: 0,
    explanation: "Jedna od prednosti vodopada je preglednost i jasno definirane faze.",
  }),
  q({
    id: "waterfall-22",
    topic: "Vodopad",
    prompt: "Koji je važan nedostatak metode vodopada?",
    answers: [
      "Promjene je teško uvoditi kada projekt odmakne.",
      "Promjene je lako uvoditi, ali samo ako se dodaju nakon puštanja u pogon.",
      "Zahtjevi se definiraju rano, pa kasne promjene mogu poremetiti već završene faze.",
      "Testiranje dolazi nakon implementacije, pa se dio problema može otkriti relativno kasno.",
    ],
    correct: 0,
    explanation: "Vodopad je slabije prilagodljiv promjenama.",
  }),
  q({
    id: "waterfall-23",
    topic: "Vodopad",
    prompt: "Zašto vodopad nije prikladan za kompleksne i dugotrajne projekte?",
    answers: [
      "Zato što je slabo fleksibilan i teško prihvaca naknadne promjene zahtjeva.",
      "Zato što zahtijeva stabilne zahtjeve, a kod dugih projekata zahtjevi se često mijenjaju.",
      "Zato što se problemi mogu kasno pojaviti ako se stvarna provjera dogodi tek nakon više faza.",
      "Zato što jasne faze smanjuju fleksibilnost kada se projektni kontekst promijeni.",
    ],
    correct: 0,
    explanation: "Kod dugih i kompleksnih projekata zahtjevi se cesce mijenjaju, a vodopad na to slabo reagira.",
  }),
  q({
    id: "agile-1",
    topic: "Agilne metode",
    prompt: "Što najbolje opisuje agilne metode?",
    answers: [
      "Fleksibilan i iterativan pristup koji naglasava korisnika, suradnju i prilagodbu.",
      "Pristup u kojem se razvoj dijeli na kraće cikluse, ali se promjene prihvaćaju samo na početku projekta.",
      "Pristup u kojem korisnik daje povratne informacije, ali tek nakon završne isporuke.",
      "Pristup u kojem je dokumentacija važnija od ranog dobivanja funkcionalnog softvera.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika, fleksibilnost i ceste prilagodbe.",
  }),
  q({
    id: "agile-2",
    topic: "Agilne metode",
    prompt: "Zašto agilne metode omogucuju ranije otkrivanje grešaka?",
    answers: [
      "Zbog čestih provjera, testiranja i prilagodbi tijekom razvoja.",
      "Zato što se veći dio testiranja planira tek na kraju, ali su zahtjevi detaljnije opisani.",
      "Zato što se korisnik uključuje povremeno, uglavnom radi potvrde završne verzije.",
      "Zato što se greške dokumentiraju ranije, iako se ispravljaju tek nakon završetka ciklusa.",
    ],
    correct: 0,
    explanation: "Česta testiranja i povratne informacije smanjuju rizik kasnog otkrivanja problema.",
  }),
  q({
    id: "agile-3",
    topic: "Agilne metode",
    prompt: "Što je Agilni manifest?",
    answers: [
      "Skup temeljnih vrijednosti i principa na kojima se temelji agilni razvoj.",
      "Skup konkretnih Scrum pravila koja propisuju sve uloge, događaje i artefakte.",
      "Popis preporučenih tehnika za planiranje ciklusa i praćenje rada tima.",
      "Dokument koji detaljno propisuje kako se mora voditi svaki agilni projekt.",
    ],
    correct: 0,
    explanation: "Agilni manifest daje osnovni način razmisljanja za agilni razvoj.",
  }),
  q({
    id: "agile-4",
    topic: "Agilne metode",
    prompt: "Koja vrijednost pripada Agilnom manifestu?",
    answers: [
      "Pojedinci i interakcija važniji su od procesa i alata.",
      "Procesi i alati važniji su od komunikacije u timu.",
      "Opsezna dokumentacija važnija je od funkcionalnog softvera.",
      "Unaprijed zadani plan važniji je od odgovora na promjene.",
    ],
    correct: 0,
    explanation: "Manifest daje prednost ljudima i komunikaciji nad procesima i alatima.",
  }),
  q({
    id: "agile-5",
    topic: "Agilne metode",
    prompt: "Što Agilni manifest stavlja ispred opsezne dokumentacije?",
    answers: [
      "Funkcionalan softver.",
      "Detaljno razrađenu specifikaciju bez isporučenog proizvoda.",
      "Dokumentaciju koja je dovoljna samo ako zamjenjuje demonstraciju proizvoda.",
      "Potpuni plan razvoja koji se ne mijenja tijekom iteracija.",
    ],
    correct: 0,
    explanation: "Jedna od vrijednosti manifesta je funkcionalan softver ispred opsezne dokumentacije.",
  }),
  q({
    id: "agile-6",
    topic: "Agilne metode",
    prompt: "Koji je odnos agilnih metoda prema promjenama?",
    answers: [
      "Promjene se prihvacaju i na njih se nastoji brzo reagirati.",
      "Promjene se prihvaćaju, ali samo između velikih projektnih faza.",
      "Promjene se toleriraju ako ne utječu na već dogovoreni plan isporuke.",
      "Promjene se bilježe tijekom razvoja, ali se u pravilu implementiraju tek u idućem projektu.",
    ],
    correct: 0,
    explanation: "Agilni pristup daje prednost odgovoru na promjene pred krutim praćenjem plana.",
  }),
  q({
    id: "agile-7",
    topic: "Agilne metode",
    prompt: "Kada je nastao Agilni manifest prema bilješkama?",
    answers: [
      "2001. godine.",
      "1970. godine.",
      "1986. godine.",
      "1940-ih godina.",
    ],
    correct: 0,
    explanation: "Bilješke navode 2001. godinu kao nastanak Agilnog manifesta.",
  }),
  q({
    id: "agile-8",
    topic: "Agilne metode",
    prompt: "Koja je uloga korisnika u agilnom razvoju prema bilješkama?",
    answers: [
      "Korisnik je uključen tijekom cijelog razvojnog ciklusa.",
      "Korisnik je uključen uglavnom na početku, kako bi se zahtjevi mogli zaključati.",
      "Korisnik se uključuje nakon svake veće faze, ali ne tijekom same implementacije.",
      "Korisnik daje povratne informacije, ali ih tim razmatra tek nakon završne isporuke.",
    ],
    correct: 0,
    explanation: "Agilne metode u prvi plan stavljaju korisnika i stalnu suradnju s njim.",
  }),
  q({
    id: "scrum-1",
    topic: "Scrum",
    prompt: "Što je Scrum?",
    answers: [
      "Razvojni okvir za rješavanje slozenih i dinamicnih problema.",
      "Agilna metoda koja propisuje kontinuirani tok bez sprintova i zadanih uloga.",
      "Linearni model razvoja u kojem se faze završavaju jedna za drugom.",
      "Skup praksi za organizaciju rada bez formalnih događaja i artefakata.",
    ],
    correct: 0,
    explanation: "Scrum je razvojni okvir, a ne samo tehnika ili postupak.",
  }),
  q({
    id: "scrum-2",
    topic: "Scrum",
    prompt: "Koja tvrdnja o nazivu Scrum je tocna?",
    answers: [
      "Naziv dolazi iz ragbija i naglasava timski rad.",
      "Naziv dolazi iz sportskog konteksta, ali u Scrumu primarno označava formalni sastanak.",
      "Naziv se koristi zato što opisuje rad u kratkim ciklusima s potpuno fiksnim zadacima.",
      "Naziv označava tehniku kojom vlasnik proizvoda samostalno raspoređuje posao timu.",
    ],
    correct: 0,
    explanation: "U bilješkama Scrum dolazi iz ragbija i naglasava timski rad.",
  }),
  q({
    id: "scrum-2a",
    topic: "Scrum",
    prompt: "Kada se Scrum prvi put spominje prema bilješkama?",
    answers: [
      "1986. godine.",
      "1970. godine.",
      "2001. godine.",
      "1997. godine.",
    ],
    correct: 0,
    explanation: "Bilješke navode 1986. godinu i članak The New New Product Development Game.",
  }),
  q({
    id: "scrum-3",
    topic: "Scrum",
    prompt: "Od cega se Scrum sastoji?",
    answers: [
      "Od uloga, događaja, artefakata i pravila.",
      "Od sprintova, Product Backloga i Daily Scruma, ali bez posebnih uloga.",
      "Od uloga i događaja, dok se artefakti definiraju tek ako ih tim sam uvede.",
      "Od vlasnika proizvoda, razvojnog tima i plana isporuke, ali bez formalnih pravila.",
    ],
    correct: 0,
    explanation: "Bilješke navode četiri osnovna dijela Scruma: uloge, događaji, artefakti i pravila.",
  }),
  q({
    id: "scrum-4",
    topic: "Scrum",
    prompt: "Kakav je Scrum tim prema bilješkama?",
    answers: [
      "Mali, samostalan, fleksibilan i prilagodljiv.",
      "Mali i fleksibilan, ali s voditeljem koji svakodnevno dodjeljuje zadatke članovima.",
      "Samostalan, ali bez jasne odgovornosti za rezultat sprinta.",
      "Prilagodljiv, ali uglavnom organiziran oko odvojenih specijaliziranih podtimova.",
    ],
    correct: 0,
    explanation: "Bit Scruma je u malom timu koji može samostalno raditi i prilagođavati se.",
  }),
  q({
    id: "scrum-4a",
    topic: "Scrum",
    prompt: "Što znači da Scrum koristi preklapajući model rada?",
    answers: [
      "Da se kroz cijeli tok projekta pomalo radi na više stvari.",
      "Da se zahtjevi, dizajn i implementacija mogu djelomično nadovezivati unutar iterativnog rada.",
      "Da tim radi paralelno na više stavki, ali bez zajedničkog cilja ciklusa.",
      "Da se faze formalno preklapaju, ali se rezultat provjerava tek na kraju projekta.",
    ],
    correct: 0,
    explanation: "Bilješke opisuju Scrum kao model u kojem se kroz tok razvoja radi pomalo na više stvari.",
  }),
  q({
    id: "scrum-4b",
    topic: "Scrum",
    prompt: "Koja tvrdnja najbolje opisuje tezinu Scruma prema bilješkama?",
    answers: [
      "Jednostavan je za razumjeti, ali tezak za savladati.",
      "Jednostavan je za razumjeti jer ima malo elemenata, ali zahtijeva disciplinu u primjeni.",
      "Težak je za savladati zato što se njegove uloge i događaji stalno mijenjaju.",
      "Jednostavan je za primjenu čim tim formalno uvede sprintove i Daily Scrum.",
    ],
    correct: 0,
    explanation: "Scrum ima jednostavnu osnovnu strukturu, ali kvalitetna primjena nije trivijalna.",
  }),
  q({
    id: "scrum-5",
    topic: "Scrum uloge",
    prompt: "Koje su tri uloge u Scrum timu?",
    answers: [
      "Scrum Master, vlasnik proizvoda i razvojni tim.",
      "Scrum Master, vlasnik proizvoda i krajnji korisnici.",
      "Vlasnik proizvoda, voditelj projekta i razvojni tim.",
      "Scrum Master, razvojni tim i predstavnici drugih Scrum timova.",
    ],
    correct: 0,
    explanation: "Scrum Team cine Scrum Master, vlasnik proizvoda i razvojni tim.",
  }),
  q({
    id: "scrum-6",
    topic: "Scrum uloge",
    prompt: "Koja je glavna uloga Scrum Mastera?",
    answers: [
      "Osigurati pravilno i neometano odvijanje Scrum procesa.",
      "Odrediti poslovnu viziju i redoslijed svih stavki proizvoda.",
      "Dodjeljivati zadatke članovima razvojnog tima tijekom svakog sprinta.",
      "Donositi konačne odluke o tome koje funkcionalnosti ulaze u proizvod.",
    ],
    correct: 0,
    explanation: "Scrum Master vodi proces, uklanja prepreke i pomaze timu.",
  }),
  q({
    id: "scrum-6a",
    topic: "Scrum uloge",
    prompt: "Koja aktivnost pripada Scrum Masteru prema bilješkama?",
    answers: [
      "Prati napredak tima i cini ga vidljivim svima uključenima u projekt.",
      "Samostalno određuje poslovne zahtjeve i redoslijed implementacije.",
      "Preuzima tehničko planiranje zadataka umjesto razvojnog tima.",
      "Odobrava kada se proizvod smije pustiti na tržište.",
    ],
    correct: 0,
    explanation: "Scrum Master brine o procesu, produktivnosti, uklanjanju prepreka i vidljivosti napretka.",
  }),
  q({
    id: "scrum-7",
    topic: "Scrum uloge",
    prompt: "Što radi vlasnik proizvoda?",
    answers: [
      "Određuje zahtjeve, ključne značajke i redoslijed implementacije.",
      "Brine se da dnevni sastanak traje točno 15 minuta.",
      "Odlučuje kako će razvojni tim tehnički razlomiti posao na zadatke.",
      "Uklanja procesne prepreke i pazi da se Scrum pravilno provodi.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovara za viziju, zahtjeve i prioritete proizvoda.",
  }),
  q({
    id: "scrum-7a",
    topic: "Scrum uloge",
    prompt: "Koja odluka pripada vlasniku proizvoda?",
    answers: [
      "Kada nastaviti razvoj, a kada proizvod pustiti na tržište.",
      "Kako će razvojni tim tehnički podijeliti posao na manje zadatke.",
      "Kako će Scrum Master ukloniti prepreke tijekom sprinta.",
      "Koji će član razvojnog tima implementirati svaku pojedinu stavku.",
    ],
    correct: 0,
    explanation: "Vlasnik proizvoda odgovoran je za viziju i odluke o razvoju i pustanju proizvoda.",
  }),
  q({
    id: "scrum-8",
    topic: "Scrum uloge",
    prompt: "Koja tvrdnja najbolje opisuje razvojni tim u Scrumu?",
    answers: [
      "Samostalno odlučuje kako podijeliti posao na manje zadatke.",
      "Odlučuje što je poslovno najvažnije za proizvod i kojim redoslijedom se radi.",
      "Prati Scrum proces i uklanja prepreke umjesto da razvija inkrement.",
      "Prima od vlasnika proizvoda detaljan tehnički raspored rada po članovima.",
    ],
    correct: 0,
    explanation: "Razvojni tim je samoorganizirajuci i odlučuje kako će razraditi posao.",
  }),
  q({
    id: "scrum-9",
    topic: "Scrum uloge",
    prompt: "Koja je preporucena velicina Scrum razvojnog tima?",
    answers: [
      "Od 3 do 9 članova, često oko 7.",
      "Od 3 do 9 članova, ali samo ako svaki član ima jednu usku specijalizaciju.",
      "Oko 7 članova, ali bez ograničenja ako tim ima dobrog Scrum Mastera.",
      "Najmanje 10 članova, jer se uloge moraju jasno podijeliti po specijalizacijama.",
    ],
    correct: 0,
    explanation: "Prevelik tim otezava komunikaciju, a premalen može smanjiti produktivnost.",
  }),
  q({
    id: "scrum-artifacts-1",
    topic: "Scrum artefakti",
    prompt: "Što su Scrum artefakti u kontekstu bilješki?",
    answers: [
      "Konkretni radni elementi koji omogucuju transparentnost, uvid i prilagodbu.",
      "Elementi Scruma koji prikazuju stanje rada, ali ne služe za prilagodbu procesa.",
      "Dokumenti koji se izrađuju samo na početku projekta i kasnije se ne mijenjaju.",
      "Sastanci na kojima tim provjerava rad, ali bez konkretnih radnih zapisa.",
    ],
    correct: 0,
    explanation: "Artefakti su elementi poput Product Backloga, Sprint Backloga, inkrementa i grafikona.",
  }),
  q({
    id: "scrum-artifacts-1a",
    topic: "Scrum artefakti",
    prompt: "Zašto su Scrum artefakti dinamicki?",
    answers: [
      "Zato što se mogu mijenjati kada se promijene zahtjevi, tržište ili tehnologija.",
      "Zato što ih razvojni tim ažurira samo nakon završetka svih sprintova.",
      "Zato što ih Scrum Master mijenja neovisno o zahtjevima i tržištu.",
      "Zato što se koriste za praćenje rada, ali se njihov sadržaj ne smije prilagođavati.",
    ],
    correct: 0,
    explanation: "Artefakti prate stvarno stanje rada i mijenjaju se kako se mijenja kontekst projekta.",
  }),
  q({
    id: "scrum-artifacts-2",
    topic: "Scrum artefakti",
    prompt: "Što definira vizija proizvoda?",
    answers: [
      "Dugorocni cilj proizvoda ili projekta.",
      "Cilj jednog sprinta koji se ostvaruje kroz odabrane stavke.",
      "Popis odabranih stavki za jedan sprint.",
      "Kriterij prema kojem se stavka smatra završenom.",
    ],
    correct: 0,
    explanation: "Vizija proizvoda treba biti jasna, kratka i precizna.",
  }),
  q({
    id: "scrum-artifacts-2a",
    topic: "Scrum artefakti",
    prompt: "Što je cilj ciklusa u Scrumu?",
    answers: [
      "Cilj koji se treba postici tijekom jednog sprinta implementacijom odabranih stavki.",
      "Dugorocna poslovna vizija cijelog proizvoda za sve buduće verzije.",
      "Ukupan popis svih stavki koje bi proizvod jednog dana mogao sadržavati.",
      "Kriterij koji definira kada se pojedina stavka smatra gotovom.",
    ],
    correct: 0,
    explanation: "Cilj ciklusa usmjerava rad jednog sprinta.",
  }),
  q({
    id: "scrum-artifacts-3",
    topic: "Scrum artefakti",
    prompt: "Na koje pitanje odgovara Product Backlog?",
    answers: [
      "Što je sljedeće najvažnije za izraditi?",
      "Koje odabrane stavke razvojni tim planira završiti u ovom sprintu?",
      "Koji je minimalni kriterij da se stavka smatra dovršenom?",
      "Koliko je rada preostalo kroz vrijeme unutar trenutnog ciklusa?",
    ],
    correct: 0,
    explanation: "Product Backlog je prioritetni popis svega potrebnog za proizvod.",
  }),
  q({
    id: "scrum-artifacts-4",
    topic: "Scrum artefakti",
    prompt: "Tko je odgovoran za sadržaj, dostupnost i redoslijed stavki Product Backloga?",
    answers: [
      "Vlasnik proizvoda.",
      "Razvojni tim, jer on odlučuje koje stavke imaju najveću poslovnu vrijednost.",
      "Scrum Master, jer on održava redoslijed stavki i uklanja prepreke.",
      "Cijeli Scrum tim jednako, bez jedne osobe odgovorne za prioritet.",
    ],
    correct: 0,
    explanation: "Product Owner upravlja prioritetima i sadržajem Product Backloga.",
  }),
  q({
    id: "scrum-artifacts-5",
    topic: "Scrum artefakti",
    prompt: "Što je Product Backlog Refinement?",
    answers: [
      "Neprekidno dodavanje detalja, procjena i redoslijeda stavkama Product Backloga.",
      "Planiranje sprinta u kojem se iz Product Backloga biraju stavke za trenutni ciklus.",
      "Pregled inkrementa na kraju sprinta radi prilagodbe Product Backloga.",
      "Dnevno ažuriranje preostalog rada kako bi se vidio napredak sprinta.",
    ],
    correct: 0,
    explanation: "Refinement poboljšava i razjasnjava Product Backlog tijekom vremena.",
  }),
  q({
    id: "scrum-artifacts-6",
    topic: "Scrum artefakti",
    prompt: "Što najbolje opisuje Sprint Backlog?",
    answers: [
      "Plan razvojnog tima za jedan ciklus s odabranim stavkama i planom realizacije.",
      "Dugorocna vizija proizvoda i poslovna svrha projekta.",
      "Ukupan prioritetni popis svih stavki koje proizvod može trebati.",
      "Kriterij kvalitete koji određuje kada je stavka završena.",
    ],
    correct: 0,
    explanation: "Sprint Backlog pripada razvojnom timu i pokazuje što se radi u sprintu.",
  }),
  q({
    id: "scrum-artifacts-6a",
    topic: "Scrum artefakti",
    prompt: "Kome pripada Sprint Backlog?",
    answers: [
      "Isključivo razvojnom timu.",
      "Isključivo vlasniku proizvoda.",
      "Cijelom Scrum timu, ali ga vlasnik proizvoda mijenja bez razvojnog tima.",
      "Scrum Masteru, jer on raspoređuje zadatke članovima tima.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je Sprint Backlog plan i vlasnistvo razvojnog tima.",
  }),
  q({
    id: "scrum-artifacts-7",
    topic: "Scrum artefakti",
    prompt: "Što je inkrement?",
    answers: [
      "Zbroj dovrsenih stavki iz ciklusa koji mora biti upotrebljiv i gotov.",
      "Plan odabranih stavki koje razvojni tim tek namjerava napraviti u sprintu.",
      "Popis svih funkcionalnosti proizvoda poredan po poslovnoj vrijednosti.",
      "Dogovoreni kriterij prema kojem se provjerava je li stavka završena.",
    ],
    correct: 0,
    explanation: "Inkrement je radni rezultat koji na kraju sprinta mora biti gotov.",
  }),
  q({
    id: "scrum-artifacts-8",
    topic: "Scrum artefakti",
    prompt: "Čemu služi definicija gotovog?",
    answers: [
      "Određuje kada se nesto smatra završenim i koju kvalitetu mora zadovoljiti.",
      "Određuje koliko će trajati Daily Scrum.",
      "Opisuje cilj koji razvojni tim želi postići u jednom sprintu.",
      "Poredava sve buduće stavke proizvoda po poslovnoj vrijednosti.",
    ],
    correct: 0,
    explanation: "Definicija gotovog daje zajednicki kriterij završenosti i kvalitete.",
  }),
  q({
    id: "scrum-artifacts-9",
    topic: "Scrum artefakti",
    prompt: "Što prikazuje Burn-down grafikon?",
    answers: [
      "Napredak kroz vrijeme i smanjenje preostalog posla.",
      "Popis stavki koje vlasnik proizvoda tek treba prioritetizirati.",
      "Kriterije po kojima tim odlučuje je li stavka završena.",
      "Plan stavki koje razvojni tim preuzima za trenutni sprint.",
    ],
    correct: 0,
    explanation: "Burn-down grafikon je vizualni prikaz preostalog posla kroz vrijeme.",
  }),
  q({
    id: "scrum-events-1",
    topic: "Scrum događaji",
    prompt: "Čemu služe događaji u Scrumu?",
    answers: [
      "Redovitosti rada, kontroli, prilagodbi i transparentnosti.",
      "Redovitosti rada, ali bez potrebe za formalnom kontrolom i prilagodbom.",
      "Usklađivanju tima samo na početku i kraju projekta.",
      "Zamjeni artefakata kada tim ne želi voditi Product Backlog.",
    ],
    correct: 0,
    explanation: "Događaji su formalne prilike za kontrolu i prilagodbu.",
  }),
  q({
    id: "scrum-events-1a",
    topic: "Scrum događaji",
    prompt: "Što se događa ako se Scrum događaji preskaču?",
    answers: [
      "Smanjuju se transparentnost, kontrola i mogućnost prilagodbe.",
      "Tim i dalje radi, ali gubi redovite prilike za inspekciju i prilagodbu.",
      "Sprint može završiti, ali se teže otkrivaju problemi u toku rada.",
      "Artefakti ostaju isti, ali se smanjuje potreba za komunikacijom u timu.",
    ],
    correct: 0,
    explanation: "Događaji postoje kako bi tim redovito kontrolirao i prilagođavao rad.",
  }),
  q({
    id: "scrum-events-1b",
    topic: "Scrum događaji",
    prompt: "Koja tvrdnja vrijedi za trajanje Scrum događaja?",
    answers: [
      "Svaki događaj ima ograničeno maksimalno trajanje.",
      "Događaji nemaju vremensko ograničenje jer su neformalni.",
      "Samo Daily Scrum ima ograničenje, ostali događaji nemaju.",
      "Trajanje svakog događaja uvijek je točno 15 minuta.",
    ],
    correct: 0,
    explanation: "Bilješke navode da svaki Scrum događaj ima maksimalno vremensko trajanje.",
  }),
  q({
    id: "scrum-events-2",
    topic: "Scrum događaji",
    prompt: "Što je sprint u Scrumu?",
    answers: [
      "Vremenski ograničen ciklus rada i srce Scruma.",
      "Popis svih stavki proizvoda poredan po prioritetu.",
      "Sastanak na kojem se dogovara što će se raditi u sljedećem ciklusu.",
      "Rezultat završenog rada koji mora biti upotrebljiv na kraju ciklusa.",
    ],
    correct: 0,
    explanation: "Sprint je osnovni ciklus u kojem se ostvaruje cilj i stvara rezultat.",
  }),
  q({
    id: "scrum-events-3",
    topic: "Scrum događaji",
    prompt: "Koliko obično traje sprint prema bilješkama?",
    answers: [
      "Od 2 do 4 tjedna.",
      "Do mjesec dana, ali najčešće kao kraći vremenski ograničen ciklus.",
      "Jedan radni dan, jer se plan provjerava na Daily Scrumu.",
      "Od 6 do 12 mjeseci, ako je projekt dovoljno složen.",
    ],
    correct: 0,
    explanation: "Bilješke navode da sprint traje 2 do 4 tjedna.",
  }),
  q({
    id: "scrum-events-3a",
    topic: "Scrum događaji",
    prompt: "Tko može otkazati sprint prije isteka predviđenog vremena?",
    answers: [
      "Samo vlasnik proizvoda.",
      "Scrum Master, ako procijeni da tim neće završiti sve stavke.",
      "Razvojni tim, ako zaključi da je Sprint Backlog prevelik.",
      "Cijeli Scrum tim zajedničkim dogovorom bez posebne odgovornosti vlasnika.",
    ],
    correct: 0,
    explanation: "Bilješke navode da je za otkazivanje sprinta ovlasten samo vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-4",
    topic: "Scrum događaji",
    prompt: "Što je rezultat Sprint Planninga?",
    answers: [
      "Cilj sprinta i Sprint Backlog.",
      "Prilagodjeni Product Backlog nakon demonstracije.",
      "Inkrement i odluka o puštanju proizvoda na tržište.",
      "Popis prepreka iz Daily Scruma i plan njihovog uklanjanja.",
    ],
    correct: 0,
    explanation: "Planiranje ciklusa završava dogovorom o cilju sprinta i Sprint Backlogu.",
  }),
  q({
    id: "scrum-events-4a",
    topic: "Scrum događaji",
    prompt: "Tko sudjeluje u Sprint Planningu?",
    answers: [
      "Svi članovi Scrum tima.",
      "Samo Scrum Master.",
      "Vlasnik proizvoda i razvojni tim, dok Scrum Master sudjeluje samo ako postoji problem.",
      "Razvojni tim, dok vlasnik proizvoda samo naknadno potvrđuje odabrane stavke.",
    ],
    correct: 0,
    explanation: "Planiranje sprinta uključuje cijeli Scrum tim.",
  }),
  q({
    id: "scrum-events-5",
    topic: "Scrum događaji",
    prompt: "Koja tri pitanja se postavljaju na Daily Scrumu?",
    answers: [
      "Što sam radio jucer, što cu raditi danas, postoje li prepreke?",
      "Što je cilj sprinta, koje stavke ulaze u sprint, tko ih odobrava?",
      "Što je završeno u inkrementu, što treba pokazati korisniku, što mijenjamo u Backlogu?",
      "Što je dobro funkcioniralo, što nije, što ćemo poboljšati u sljedećem sprintu?",
    ],
    correct: 0,
    explanation: "Daily Scrum služi brzom dnevnom usklađivanju tima.",
  }),
  q({
    id: "scrum-events-6",
    topic: "Scrum događaji",
    prompt: "Što Daily Scrum nije namijenjen raditi?",
    answers: [
      "Detaljno rješavati probleme tijekom sastanka.",
      "Poboljsati komunikaciju u razvojnom timu.",
      "Prepoznati prepreke u radu.",
      "Brzo uskladiti plan rada za taj dan.",
    ],
    correct: 0,
    explanation: "Problemi se mogu raspraviti nakon formalnog dijela, ali Daily Scrum nije sastanak za njihovo detaljno rješavanje.",
  }),
  q({
    id: "scrum-events-7",
    topic: "Scrum događaji",
    prompt: "Što je cilj Sprint Reviewa?",
    answers: [
      "Pregledati inkrement i po potrebi prilagoditi Product Backlog.",
      "Analizirati rad tima i dogovoriti poboljšanja procesa.",
      "Odabrati stavke koje će razvojni tim preuzeti u idući sprint.",
      "Procijeniti preostali rad i ažurirati Burn-down grafikon.",
    ],
    correct: 0,
    explanation: "Sprint Review se bavi pregledom rezultata sprinta i Product Backlogom.",
  }),
  q({
    id: "scrum-events-7a",
    topic: "Scrum događaji",
    prompt: "Tko može sudjelovati na Sprint Reviewu osim Scrum tima?",
    answers: [
      "Osobe koje pozove vlasnik proizvoda, primjerice dionici i krajnji korisnici.",
      "Samo Scrum Master, bez vlasnika proizvoda i razvojnog tima.",
      "Samo razvojni tim, jer se inkrement ne pokazuje izvan tima.",
      "Samo vlasnik proizvoda i Scrum Master, jer razvojni tim tada ne sudjeluje.",
    ],
    correct: 0,
    explanation: "Sprint Review može uključiti dionike i korisnike koje pozove vlasnik proizvoda.",
  }),
  q({
    id: "scrum-events-8",
    topic: "Scrum događaji",
    prompt: "Što je cilj Sprint Retrospectivea?",
    answers: [
      "Analizirati rad tima i dogovoriti poboljšanja za iduci sprint.",
      "Odabrati stavke Product Backloga za trenutni sprint.",
      "Pregledati gotov inkrement s dionicima i prilagoditi Product Backlog.",
      "Svaki dan uskladiti što je napravljeno, što slijedi i postoje li prepreke.",
    ],
    correct: 0,
    explanation: "Retrospektiva je usmjerena na poboljšanje načina rada tima.",
  }),
  q({
    id: "scrum-events-8a",
    topic: "Scrum događaji",
    prompt: "Kada se održava Sprint Retrospective?",
    answers: [
      "Nakon pregleda ciklusa, a prije planiranja sljedećeg sprinta.",
      "Na početku sprinta, odmah nakon što se odabere Sprint Backlog.",
      "Tijekom Sprint Reviewa, kao dio demonstracije inkrementa dionicima.",
      "Svaki dan nakon Daily Scruma, ako postoje prepreke u radu.",
    ],
    correct: 0,
    explanation: "Retrospektiva zaključuje sprint s naglaskom na poboljšanje rada za sljedeći sprint.",
  }),
  q({
    id: "kanban-1",
    topic: "Kanban",
    prompt: "Što znači riječ Kanban?",
    answers: [
      "Vidljiva kartica.",
      "Radna kartica.",
      "Signalna ploča.",
      "Kartica toka.",
    ],
    correct: 0,
    explanation: "Kanban dolazi iz japanskog i doslovno znači vidljiva kartica.",
  }),
  q({
    id: "kanban-1a",
    topic: "Kanban",
    prompt: "Gdje i kada je razvijen Kanban prema bilješkama?",
    answers: [
      "U Toyoti 1940-ih godina.",
      "U japanskoj proizvodnji, ali tek kao softverska agilna metoda 2001. godine.",
      "U proizvodnom okruženju nakon razvoja Scruma, kao odgovor na sprintove.",
      "U Toyoti 1970-ih, paralelno s prvim opisom metode vodopada.",
    ],
    correct: 0,
    explanation: "Bilješke povezuju Kanban s Toyotom i proizvodnjom upravo na vrijeme.",
  }),
  q({
    id: "kanban-1b",
    topic: "Kanban",
    prompt: "S kojom je proizvodnom idejom povezan Kanban?",
    answers: [
      "Upravo na vrijeme, odnosno Just in Time.",
      "Dugoročno planiranje velikih zaliha unaprijed.",
      "Isporuka u fiksnim vremenskim kutijama bez promjene opsega.",
      "Planiranje rada tako da se sav posao započne što ranije.",
    ],
    correct: 0,
    explanation: "Kanban je razvijen uz JIT pristup smanjenja nepotrebnog posla.",
  }),
  q({
    id: "kanban-2",
    topic: "Kanban",
    prompt: "Koja je osnovna ideja Kanbana?",
    answers: [
      "Vizualizirati tok rada i upravljati njime uz ograničenje rada u tijeku.",
      "Raditi u fiksnim sprintovima s jasno zadanim ulogama.",
      "Vizualizirati rad, ali bez ograničenja količine posla koji je istovremeno otvoren.",
      "Upravljati tokom tako da se novi zadaci započinju čim se pojave, bez čekanja kapaciteta.",
    ],
    correct: 0,
    explanation: "Kanban naglasava vizualizaciju rada, WIP ograničenja i glatki tok.",
  }),
  q({
    id: "kanban-2a",
    topic: "Kanban",
    prompt: "Koja recenica najbolje izrazava načelo koje dijele Scrum i Kanban u bilješkama?",
    answers: [
      "Prestani pocinjati, počni završavati.",
      "Započni što više stavki kako bi se povećala iskorištenost tima.",
      "Planiraj sve zadatke unaprijed kako bi se izbjegle promjene toka.",
      "Završi planiranje prije nego se počne vizualizirati rad.",
    ],
    correct: 0,
    explanation: "Bilješke navode naglasak na završavanju zapocetog posla.",
  }),
  q({
    id: "kanban-3",
    topic: "Kanban",
    prompt: "Što znači WIP u Kanbanu?",
    answers: [
      "Količina posla na kojem se trenutno radi.",
      "Ukupan broj zadataka koji čekaju u Product Backlogu.",
      "Broj završenih zadataka u zadnjem ciklusu.",
      "Maksimalan broj ljudi koji smije raditi u jednom stupcu.",
    ],
    correct: 0,
    explanation: "WIP je work in progrešs, odnosno rad u tijeku.",
  }),
  q({
    id: "kanban-4",
    topic: "Kanban",
    prompt: "Zašto Kanban ogranicava WIP?",
    answers: [
      "Da se izbjegne preopterećenje, multitasking i zadržavanje posla.",
      "Da svi članovi tima imaju što više paralelnih zadataka u svakom trenutku.",
      "Da se novi posao ne povlači dok postojeći posao nije dovoljno pomaknut kroz tok.",
      "Da se prioriteti ne mogu promijeniti dok se ne završi cijeli projekt.",
    ],
    correct: 0,
    explanation: "Ogranicenje WIP-a pomaze fokusu, toku i produktivnosti.",
  }),
  q({
    id: "kanban-5",
    topic: "Kanban",
    prompt: "Koje su tri glavne ideje Kanbana iz bilješki?",
    answers: [
      "Vizualizirati rad, ograniciti WIP i unaprijediti tok rada.",
      "Vizualizirati rad, planirati sprint i pregledati inkrement.",
      "Ograničiti WIP, definirati uloge i raditi u fiksnim ciklusima.",
      "Unaprijediti tok rada, ali bez eksplicitnog ograničenja rada u tijeku.",
    ],
    correct: 0,
    explanation: "To su tri glavna načela Kanbana navedena u bilješkama.",
  }),
  q({
    id: "kanban-6",
    topic: "Kanban",
    prompt: "Što je Kanban kartica?",
    answers: [
      "Vizualni prikaz jedne stavke posla i njezina statusa.",
      "Stupac koji ograničava koliko posla smije biti u tijeku.",
      "Pravilo kojim se određuje kada stavka smije prijeći u iduću fazu.",
      "Zbirni prikaz cijelog toka rada na razini ploče.",
    ],
    correct: 0,
    explanation: "Kanban kartica prikazuje zadatak, odgovornu osobu, rok i slicne podatke.",
  }),
  q({
    id: "kanban-6a",
    topic: "Kanban",
    prompt: "Koje su ključne komponente Kanbana navedene u bilješkama?",
    answers: [
      "Kanban kartice, Kanban stupci, WIP i Kanban staze sa zadacima.",
      "Kanban kartice, sprintovi, vlasnik proizvoda i definicija gotovog.",
      "Kanban ploča, Daily Scrum, WIP i retrospektiva.",
      "Kanban stupci, vizija proizvoda, Sprint Backlog i inkrement.",
    ],
    correct: 0,
    explanation: "Bilješke zasebno navode četiri ključne Kanban komponente.",
  }),
  q({
    id: "kanban-7",
    topic: "Kanban",
    prompt: "Kada se u Kanbanu proizvod ili funkcionalnost pusta u rad?",
    answers: [
      "Čim je dovrsena i spremna.",
      "Isključivo na kraju sprinta od 2 do 4 tjedna.",
      "Kada se napuni planirani paket funkcionalnosti za sljedeći ciklus.",
      "Kada vlasnik proizvoda zaključa popis stavki za trenutni sprint.",
    ],
    correct: 0,
    explanation: "Kanban naglasava kontinuiranu isporuku, bez čekanja kraja sprinta.",
  }),
  q({
    id: "kanban-8",
    topic: "Kanban",
    prompt: "Za kakvo okruzenje je Kanban posebno prikladan?",
    answers: [
      "Za okruzenje s cestim promjenama prioriteta.",
      "Za projekte u kojima su svi zahtjevi potpuno stabilni od početka.",
      "Za timove koji moraju raditi u fiksnim sprintovima s unaprijed zaključanim opsegom.",
      "Za projekte gdje je važno prvo završiti sve faze prije isporuke.",
    ],
    correct: 0,
    explanation: "Kanban je fleksibilan i dobro podnosi promjene prioriteta.",
  }),
  q({
    id: "kanban-9",
    topic: "Kanban",
    prompt: "Koja tvrdnja pripada temeljnim nacelima Kanbana?",
    answers: [
      "Zapoceti s onim što je poznato i postepeno uvoditi promjene.",
      "Uvesti radikalne promjene odmah na početku projekta.",
      "Zamijeniti postojeći proces potpuno novim pravilima prije prve Kanban ploče.",
      "Uvesti promjene samo nakon što se svi zadaci završe i tok zaustavi.",
    ],
    correct: 0,
    explanation: "Kanban se uvodi postupno i postuje postojece postupke, uloge i zaduzenja.",
  }),
  q({
    id: "kanban-10",
    topic: "Kanban",
    prompt: "Što znači praksa 'upravljati tokom' u Kanbanu?",
    answers: [
      "Upravljati poslom tako da se stavke što brze i glatko završavaju.",
      "Dodjeljivati ljudima što više zadataka da stalno budu zauzeti.",
      "Povećavati broj započetih stavki kako bi ploča stalno bila popunjena.",
      "Pratiti samo završene zadatke, a ne mjesta gdje posao zapinje.",
    ],
    correct: 0,
    explanation: "Kanban upravlja tokom rada, ne prividnom zauzetoscu ljudi.",
  }),
  q({
    id: "kanban-11",
    topic: "Kanban",
    prompt: "Što znači praksa 'jasno definirati politiku procesa' u Kanbanu?",
    answers: [
      "Proces treba biti jasno opisan i vidljiv kako bi tim mogao donositi odluke o poboljšanjima.",
      "Proces treba ostati nevidljiv kako bi tim bio fleksibilniji.",
      "Politiku procesa smije poznavati samo voditelj projekta.",
      "Politika procesa zamjenjuje potrebu za vizualizacijom toka rada.",
    ],
    correct: 0,
    explanation: "Kanban trazi da pravila procesa budu jasna i svima vidljiva.",
  }),
  q({
    id: "kanban-12",
    topic: "Kanban",
    prompt: "Čemu služe povratne informacije kao Kanban praksa?",
    answers: [
      "Redovitom usklađivanju rada i razmjeni znanja.",
      "Zabrani promjena prioriteta tijekom rada.",
      "Povremenoj provjeri toka rada bez utjecaja na način rada tima.",
      "Zamjeni vizualizacije rada sastancima na kojima se usmeno prati stanje.",
    ],
    correct: 0,
    explanation: "Povratne informacije u Kanbanu uključuju redovite kratke sastanke i usklađivanje.",
  }),
  q({
    id: "scrum-kanban-1",
    topic: "Scrum ili Kanban",
    prompt: "Koja je glavna razlika između Scruma i Kanbana?",
    answers: [
      "Scrum radi u vremenski ograničenim sprintovima, a Kanban u kontinuiranom toku rada.",
      "Scrum i Kanban oba koriste tok rada, ali Scrum nema vremenski ograničene cikluse.",
      "Kanban radi u sprintovima kada ima WIP limit, a Scrum isporučuje čim je stavka gotova.",
      "Scrum ima definirane uloge i događaje, dok Kanban primarno naglašava vizualni tok i WIP.",
    ],
    correct: 0,
    explanation: "Scrum je organiziran oko sprintova, a Kanban oko kontinuiranog toka.",
  }),
  q({
    id: "scrum-kanban-2",
    topic: "Scrum ili Kanban",
    prompt: "U kojem pristupu nema zadanih uloga članova tima?",
    answers: [
      "Kanban.",
      "Scrum, jer uvijek propisuje Scrum Mastera, vlasnika proizvoda i razvojni tim.",
      "Scrumban, jer obavezno zadržava sve Scrum uloge bez promjena.",
      "Scrum of Scrums, jer okuplja predstavnike više već postojećih Scrum timova.",
    ],
    correct: 0,
    explanation: "U bilješkama Kanban nema zadane uloge kao Scrum.",
  }),
  q({
    id: "scrum-kanban-3",
    topic: "Scrum ili Kanban",
    prompt: "Koji pristup je prikladniji za rad u blokovima i stabilniji plan?",
    answers: [
      "Scrum.",
      "Kanban, jer je primarno usmjeren na kontinuirani tok i promjene prioriteta.",
      "Scrumban, jer potpuno ukida planiranje ciklusa i radi samo po povlačenju kartica.",
      "Scrum of Scrums, jer je to okvir za koordinaciju više timova, a ne osnovni način rada jednog tima.",
    ],
    correct: 0,
    explanation: "Scrum je strukturiraniji i prikladniji kada se posao može grupirati u cikluse.",
  }),
  q({
    id: "scrumban-1",
    topic: "Scrumban",
    prompt: "Što je Scrumban?",
    answers: [
      "Hibrid Scruma i Kanbana.",
      "Scrum prilagođen velikom broju timova kroz sastanke predstavnika.",
      "Kanban s dodanim elementima planiranja i pregleda, ali bez ikakve Scrum strukture.",
      "Scrum u kojem se zadržavaju sprintovi, ali se potpuno uklanjaju WIP ograničenja.",
    ],
    correct: 0,
    explanation: "Scrumban kombinira Scrum strukturu s Kanban fleksibilnoscu.",
  }),
  q({
    id: "scrumban-2",
    topic: "Scrumban",
    prompt: "Što Scrumban preuzima od Scruma?",
    answers: [
      "Strukturu, iterativno planiranje, osvrte, preglede i prioritete.",
      "Potpuno nepostojanje uloga i ciklusa.",
      "Samo vizualnu ploču i ograničenje rada u tijeku.",
      "Kontinuiranu isporuku bez planiranja ciklusa i bez pregleda rada.",
    ],
    correct: 0,
    explanation: "Scrumban zadrzava dio Scrum strukture i planiranja.",
  }),
  q({
    id: "scrumban-3",
    topic: "Scrumban",
    prompt: "Što Scrumban preuzima od Kanbana?",
    answers: [
      "Fleksibilnost, vizualni prikaz toka rada i ograničenje preuzetih zadataka.",
      "Strogo definirane Scrum uloge i obavezne sprintove.",
      "Planiranje sprinta, pregled ciklusa i retrospektivu.",
      "Potpuno fiksan redoslijed faza i završnu isporuku nakon testiranja.",
    ],
    correct: 0,
    explanation: "Od Kanbana preuzima vizualizaciju, tok rada i ograničavanje zadataka.",
  }),
  q({
    id: "scrumban-4",
    topic: "Scrumban",
    prompt: "Za koje timove je Scrumban posebno prikladan?",
    answers: [
      "Za timove kojima trebaju i struktura Scruma i fleksibilnost Kanbana.",
      "Za timove koji zele potpuno izbjeci vizualizaciju rada.",
      "Za timove koji žele zadržati sprintove, ali bez ikakvog upravljanja tokom rada.",
      "Za timove koji žele kontinuirani tok, ali bez prioriteta i povratnih informacija.",
    ],
    correct: 0,
    explanation: "Scrumban se koristi i kao prijelaz iz Scruma u Kanban.",
  }),
  q({
    id: "sos-1",
    topic: "Scrum of Scrums",
    prompt: "Kada se koristi Scrum of Scrums?",
    answers: [
      "Kada je projekt prevelik za jedan Scrum tim pa treba uskladiti više timova.",
      "Kada više Scrum timova radi na povezanom proizvodu i moraju uskladiti ovisnosti.",
      "Kada jedan Scrum tim ima previše članova pa Daily Scrum traje dulje od očekivanog.",
      "Kada vlasnik proizvoda želi objediniti Product Backlog bez predstavnika timova.",
    ],
    correct: 0,
    explanation: "Scrum of Scrums koordinira rad više Scrum timova.",
  }),
  q({
    id: "sos-2",
    topic: "Scrum of Scrums",
    prompt: "Tko sudjeluje na Scrum of Scrums sastanku?",
    answers: [
      "Predstavnici svakog Scrum tima.",
      "Svi članovi svih Scrum timova, kako bi svatko izravno izvijestio o svom radu.",
      "Samo Scrum Masteri, jer razvojni timovi ne sudjeluju u koordinaciji.",
      "Samo vlasnici proizvoda, jer se razgovara isključivo o prioritetima Backloga.",
    ],
    correct: 0,
    explanation: "Ne sudjeluju svi članovi, nego jedan ili više predstavnika svakog tima.",
  }),
  q({
    id: "sos-3",
    topic: "Scrum of Scrums",
    prompt: "Koje pitanje pripada Scrum of Scrums sastanku?",
    answers: [
      "Što će vas tim raditi do idućeg sastanka što može utjecati na druge timove?",
      "Što sam ja osobno radio jučer i što ću osobno raditi danas?",
      "Koje stavke Product Backloga ulaze u idući sprint jednog tima?",
      "Koju definiciju gotovog koristi razvojni tim za jednu stavku?",
    ],
    correct: 0,
    explanation: "Scrum of Scrums se fokusira na ovisnosti i utjecaj rada jednog tima na druge.",
  }),
  q({
    id: "docs-1",
    topic: "Dokumentacija",
    prompt: "Koja je osnovna podjela dokumentacije?",
    answers: [
      "Dokumentacija proizvoda i dokumentacija procesa.",
      "Sistemska dokumentacija i korisnička dokumentacija kao jedine dvije glavne skupine.",
      "Dokumentacija zahtjeva i dokumentacija testiranja kao potpuna podjela.",
      "Online dokumentacija i tiskana dokumentacija kao osnovna teorijska podjela.",
    ],
    correct: 0,
    explanation: "Bilješke dokumentaciju dijele na dokumentaciju proizvoda i procesa.",
  }),
  q({
    id: "docs-2",
    topic: "Dokumentacija",
    prompt: "Što opisuje dokumentacija proizvoda?",
    answers: [
      "Nastali proizvod i upute za rukovanje.",
      "Aktivnosti, rasporede, izvještaje i organizaciju rada tijekom razvoja.",
      "Samo interne odluke tima koje nisu povezane s korištenjem proizvoda.",
      "Isključivo metriku vremena i kadra potrošenog na projekt.",
    ],
    correct: 0,
    explanation: "Dokumentacija proizvoda opisuje proizvod i daje upute za rukovanje.",
  }),
  q({
    id: "docs-3",
    topic: "Dokumentacija",
    prompt: "Što opisuje dokumentacija procesa?",
    answers: [
      "Aktivnosti vezane uz razvoj proizvoda.",
      "Gotov proizvod i upute za njegovo korištenje.",
      "Isključivo tehničku strukturu izvornog koda.",
      "Samo korisničke upute prilagođene krajnjim korisnicima.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati planove, rasporede, izvještaje i slicne aktivnosti razvoja.",
  }),
  q({
    id: "docs-4",
    topic: "Sistemska dokumentacija",
    prompt: "Što je sistemska dokumentacija?",
    answers: [
      "Dokumenti koji opisuju sustav, njegove dijelove i temeljnu tehnologiju.",
      "Upute za krajnje korisnike bez tehničkih detalja.",
      "Dokumenti koji opisuju samo raspored aktivnosti tijekom projekta.",
      "Dokumenti koji prate razvojni proces, ali ne opisuju sam proizvod.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija je tehnički orijentirana i opisuje sustav.",
  }),
  q({
    id: "docs-5",
    topic: "Sistemska dokumentacija",
    prompt: "Što pripada sistemskoj dokumentaciji?",
    answers: [
      "Dokument zahtjeva, opis arhitekture, opis koda i dokumentacija testiranja.",
      "FAQ, video upute i portali za pomoć krajnjim korisnicima.",
      "Projektni planovi, rasporedi testiranja i izvještaji o napretku.",
      "Projektni planovi, procjene, izvještaji i metrika razvoja.",
    ],
    correct: 0,
    explanation: "Sistemska dokumentacija uključuje zahtjeve, arhitekturu, kod, validaciju i testiranje.",
  }),
  q({
    id: "docs-6",
    topic: "Sistemska dokumentacija",
    prompt: "Što opisuje dokument zahtjeva?",
    answers: [
      "Što proizvod treba raditi i koje funkcionalnosti treba imati.",
      "Kako je sustav tehnički podijeljen na komponente i module.",
      "Koji su testni slučajevi već izvedeni i s kojim rezultatima.",
      "Kako korisnik nakon isporuke koristi gotovu funkcionalnost.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva sadrzi funkcionalnosti, poslovna pravila, korisničke price i slučajeve.",
  }),
  q({
    id: "docs-7",
    topic: "Sistemska dokumentacija",
    prompt: "Što treba biti navedeno u dokumentu zahtjeva?",
    answers: [
      "Uloge, ciljevi, pretpostavke, korisničke price, interakcija i pitanja.",
      "Samo arhitekturni dijagrami i opis korištene tehnologije.",
      "Samo rezultati testiranja i popis pronađenih grešaka.",
      "Samo upute za instalaciju i svakodnevno korištenje proizvoda.",
    ],
    correct: 0,
    explanation: "Dokument zahtjeva treba jasno opisati svrhu, značajke, ponasanje i kontekst proizvoda.",
  }),
  q({
    id: "docs-8",
    topic: "Sistemska dokumentacija",
    prompt: "Što navodi dokumentacija arhitekture softvera?",
    answers: [
      "Najvažnije arhitekturne odluke i prikaz rješenja.",
      "Samo krajnje korisničke upute za rad.",
      "Popis funkcionalnosti koje proizvod mora imati iz perspektive zahtjeva.",
      "Postupke kojima se provjerava ispravnost pojedinih značajki.",
    ],
    correct: 0,
    explanation: "Arhitekturna dokumentacija opisuje odluke, principe, rješenja i dijagrame.",
  }),
  q({
    id: "docs-9",
    topic: "Sistemska dokumentacija",
    prompt: "Kome je prvenstveno namijenjena dokumentacija o kodu?",
    answers: [
      "Developerima.",
      "Projektnim voditeljima kojima treba samo pregled rokova i statusa razvoja.",
      "Krajnjim korisnicima, ali samo ako dokumentacija ne sadrži tehničke detalje.",
      "Sistemskim administratorima, dok developerima primarno služi korisnička dokumentacija.",
    ],
    correct: 0,
    explanation: "Dokumentacija o kodu opisuje način rada koda i tehničke detalje.",
  }),
  q({
    id: "docs-10",
    topic: "Dokumentacija testiranja",
    prompt: "Što opisuje strategija testiranja?",
    answers: [
      "Opci pristup testiranju.",
      "Što se testira i u kojem trenutku.",
      "Konkretne korake kojima se provjerava svaka pojedina značajka.",
      "Završni popis pronađenih grešaka nakon provedbe svih testova.",
    ],
    correct: 0,
    explanation: "Strategija testiranja opisuje pristup, strukturu, resurse i prioritete.",
  }),
  q({
    id: "docs-11",
    topic: "Dokumentacija testiranja",
    prompt: "Što opisuje plan testiranja?",
    answers: [
      "Što se treba testirati i kada.",
      "Opći pristup i prioritete testiranja bez konkretnih rokova.",
      "Postupke kojima se pojedina značajka verificira.",
      "Tehničku arhitekturu sustava koji će se testirati.",
    ],
    correct: 0,
    explanation: "Plan testiranja definira stavke, metode, vremenske okvire, uloge i zaduzenja.",
  }),
  q({
    id: "docs-12",
    topic: "Dokumentacija testiranja",
    prompt: "Što radi specifikacija testnih slučajeva?",
    answers: [
      "Opisuje postupke kojima se verificira svaka znacajka.",
      "Definira što se treba testirati i u kojem vremenskom okviru.",
      "Opisuje opći pristup testiranju i raspoložive resurse.",
      "Bilježi samo konačni rezultat testiranja bez postupka provjere.",
    ],
    correct: 0,
    explanation: "Specifikacije testnih slučajeva povezuju značajke s postupcima provjere.",
  }),
  q({
    id: "docs-13",
    topic: "Korisnička dokumentacija",
    prompt: "Kome je namijenjena korisnička dokumentacija?",
    answers: [
      "Krajnjim korisnicima i sistemskim administratorima.",
      "Korisnicima proizvoda, ali ne i administratorima koji ga održavaju.",
      "Developerima i testerima koji trebaju razumjeti unutarnju strukturu sustava.",
      "Timovima koji planiraju razvoj, procjene i rasporede projekta.",
    ],
    correct: 0,
    explanation: "Korisnička dokumentacija mora biti prilagođena znanju korisnika.",
  }),
  q({
    id: "docs-14",
    topic: "Korisnička dokumentacija",
    prompt: "Što može sadržavati online korisnička dokumentacija?",
    answers: [
      "Česta pitanja, video upute, ugrađenu pomoć i portale za pomoć.",
      "Samo arhitekturne dijagrame i sigurnosne mjere.",
      "Upute za instalaciju i rad, ali bez interaktivne pomoći ili često postavljanih pitanja.",
      "Samo planove, procjene i metriku rada razvojnog tima.",
    ],
    correct: 0,
    explanation: "Online dokumentacija treba pomagati korisniku u korištenju proizvoda.",
  }),
  q({
    id: "docs-14a",
    topic: "Korisnička dokumentacija",
    prompt: "Zašto je kod korisničke dokumentacije važno prikupljati povratne informacije korisnika?",
    answers: [
      "Da bi se dokumentacija mogla stalno ažurirati i poboljšavati prema stvarnim potrebama korisnika.",
      "Da bi korisnici mogli sami odrediti tehničku strukturu dokumentacije sustava.",
      "Da bi se svaka korisnička primjedba odmah pretvorila u novu funkcionalnost proizvoda.",
      "Da bi se korisnička dokumentacija mogla zaključati nakon prve objave proizvoda.",
    ],
    correct: 0,
    explanation: "Povratne informacije pomažu da korisnička dokumentacija ostane korisna i razumljiva.",
  }),
  q({
    id: "docs-15",
    topic: "Dokumentacija procesa",
    prompt: "Što pripada dokumentaciji procesa?",
    answers: [
      "Projektni planovi, rasporedi testiranja, izvještaji, standardi i bilješke sa sastanaka.",
      "Dokument zahtjeva, opis arhitekture, opis koda i dokumentacija testiranja.",
      "FAQ, video upute, ugrađena pomoć i portali za krajnje korisnike.",
      "Opis proizvoda i upute za rukovanje nakon isporuke.",
    ],
    correct: 0,
    explanation: "Dokumentacija procesa prati aktivnosti i organizaciju razvoja.",
  }),
  q({
    id: "docs-15a",
    topic: "Dokumentacija procesa",
    prompt: "Što su planovi, procjene i rasporedi u dokumentaciji procesa?",
    answers: [
      "Dokumenti koji obično nastaju prije razvoja, ali se mogu prilagođavati tijekom izrade softvera.",
      "Dokumenti koji nastaju samo nakon razvoja i služe za opis gotovog proizvoda.",
      "Dokumenti procesa koji se jednom napišu i ne mijenjaju tijekom razvoja.",
      "Dokumenti koji zamjenjuju potrebu za izvještajima i metrikom tijekom projekta.",
    ],
    correct: 0,
    explanation: "Planovi, procjene i rasporedi pomažu organizirati razvoj i mogu se mijenjati tijekom rada.",
  }),
  q({
    id: "docs-15b",
    topic: "Dokumentacija procesa",
    prompt: "Čemu služe izvještaji i metrika u dokumentaciji procesa?",
    answers: [
      "Praćenju korištenja vremena i kadra tijekom razvoja softvera.",
      "Praćenju stanja projekta, ali bez uvida u utrošeno vrijeme i resurse.",
      "Opisivanju gotovog proizvoda iz perspektive krajnjeg korisnika.",
      "Zamjeni projektnih planova kada se razvoj počne odvijati drukčije od očekivanog.",
    ],
    correct: 0,
    explanation: "Izvještaji i metrika daju uvid u resurse i tijek razvoja.",
  }),
  q({
    id: "docs-16",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja o količini dokumentacije je najtočnija?",
    answers: [
      "Treba je biti dovoljno, ali ne prekratko ni preopsežno.",
      "Uvijek mora biti što opsežnija, bez obzira na ponavljanje.",
      "Treba sadržavati dovoljno informacija bez nepotrebnog ponavljanja i opterećenja.",
      "Treba biti kratka, čak i ako zbog toga ne pokriva bitne odluke i upute.",
    ],
    correct: 0,
    explanation: "Premalo dokumentacije stvara greške, a previše stvara ponavljanje i opterećenje.",
  }),
  q({
    id: "docs-16a",
    topic: "Dokumentacija",
    prompt: "Koja tvrdnja najbolje opisuje status dokumentacije kroz vrijeme?",
    answers: [
      "Dokumentacija nikad nije konačna, nego se stalno nadopunjuje.",
      "Dokumentacija je zaključana čim se završi analiza zahtjeva.",
      "Dokumentacija se može mijenjati, ali samo prije prve isporuke proizvoda.",
      "Dokumentacija se nadopunjuje samo ako se mijenja programski kod.",
    ],
    correct: 0,
    explanation: "Bilješke navode da se dokumentacija stalno nadopunjuje.",
  }),
  q({
    id: "docs-17",
    topic: "Dokumentacija",
    prompt: "Kakva je kvalitetna dokumentacija?",
    answers: [
      "Precizna, jasna i relevantna.",
      "Detaljna, ali samo ako sadrži sve informacije bez obzira na relevantnost.",
      "Kratka i pregledna, čak i ako izostavlja važne tehničke odluke.",
      "Usmjerena na jednu skupinu korisnika, bez obzira na stvarne potrebe ostalih čitatelja.",
    ],
    correct: 0,
    explanation: "Bilješke naglasavaju preciznost, jasnocu i relevantnost.",
  }),
  q({
    id: "docs-17a",
    topic: "Dokumentacija",
    prompt: "Tko doprinosi sastavljanju dokumentacije prema bilješkama?",
    answers: [
      "Svi članovi tima koji su na bilo koji način sudjelovali u razvoju proizvoda.",
      "Samo osoba koja piše kod.",
      "Samo krajnji korisnici nakon završene isporuke.",
      "Samo Scrum Master tijekom Daily Scruma.",
    ],
    correct: 0,
    explanation: "Dokumentacija je rezultat zajednickog rada i komentara više sudionika.",
  }),
  q({
    id: "docs-18",
    topic: "Generatori dokumentacije",
    prompt: "Čemu služe generatori dokumentacije?",
    answers: [
      "Laksem i brzem stvaranju dokumentacije, često iz komentara u kodu.",
      "Ručnom pisanju korisničkih uputa bez povezivanja s izvornim kodom.",
      "Automatskom stvaranju dijela dokumentacije, ali bez korištenja komentara ili strukture koda.",
      "Izradi procesne dokumentacije poput rasporeda, procjena i metrika razvoja.",
    ],
    correct: 0,
    explanation: "Generatori dokumentacije automatiziraju dio izrade dokumentacije.",
  }),
  q({
    id: "docs-19",
    topic: "Generatori dokumentacije",
    prompt: "Što je Doxygen?",
    answers: [
      "Alat za generiranje dokumentacije, primarno za C++, ali podržava i druge jezike.",
      "Format komentara namijenjen isključivo Java klasama i metodama.",
      "Alat za generiranje dokumentacije, ali namijenjen samo korisničkim uputama izvan koda.",
      "Alat koji opisuje strukturu projekta, ali ne može koristiti komentare iz izvornog koda.",
    ],
    correct: 0,
    explanation: "Doxygen generira dokumentaciju iz komentara u kodu.",
  }),
  q({
    id: "docs-19a",
    topic: "Generatori dokumentacije",
    prompt: "Što Doxygen može napraviti osim generiranja tekstualne dokumentacije?",
    answers: [
      "Prikazati strukturu koda i odnose medju elementima pomoću automatski generiranih grafova.",
      "Generirati HTML dokumentaciju, ali bez prikaza odnosa među elementima koda.",
      "Prikazati odnose među elementima, ali samo ako ih developer ručno nacrta.",
      "Izraditi korisničke upute iz komentara, ali bez analize strukture izvornog koda.",
    ],
    correct: 0,
    explanation: "Bilješke navode da Doxygen može izvuci strukturu koda i prikazati odnose.",
  }),
  q({
    id: "docs-20",
    topic: "Generatori dokumentacije",
    prompt: "Što JavaDoc generira?",
    answers: [
      "HTML dokumentaciju za Java kod iz komentara.",
      "Grafove odnosa u C++ kodu kao primarni oblik dokumentacije.",
      "HTML dokumentaciju za bilo koji programski jezik bez posebnog formata komentara.",
      "Procesnu dokumentaciju iz planova, procjena i rasporeda razvoja.",
    ],
    correct: 0,
    explanation: "JavaDoc je vezan uz dokumentiranje Java koda.",
  }),
  q({
    id: "docs-20a",
    topic: "Generatori dokumentacije",
    prompt: "Koje dvije vrste komentara se spominju kod JavaDoca?",
    answers: [
      "Komentari na razini klase i komentari na razini članova klase.",
      "Komentari na razini projekta i komentari na razini korisničkih uputa.",
      "Komentari na razini paketa i komentari na razini testnog plana.",
      "Komentari za opis zahtjeva i komentari za opis arhitekture sustava.",
    ],
    correct: 0,
    explanation: "JavaDoc razlikuje komentare za klasu i za članove poput atributa i metoda.",
  }),
  q({
    id: "docs-21",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje parametar metode?",
    answers: ["@param", "@return", "@version", "@author"],
    correct: 0,
    explanation: "@param se koristi za opis parametra metode.",
  }),
  q({
    id: "docs-22",
    topic: "Generatori dokumentacije",
    prompt: "Koji JavaDoc tag opisuje povratnu vrijednost?",
    answers: ["@return", "@throws", "@author", "@version"],
    correct: 0,
    explanation: "@return opisuje povratnu vrijednost metode.",
  }),
  q({
    id: "docs-23",
    topic: "Generatori dokumentacije",
    prompt: "Koji alati su navedeni kao drugi generatori dokumentacije?",
    answers: [
      "Sphinx, Dr. Explain i PHPDocumentator.",
      "Doxygen, JavaDoc i dokument zahtjeva.",
      "Sphinx, JavaDoc i dokumentacija procesa.",
      "Dr. Explain, Doxygen i plan testiranja.",
    ],
    correct: 0,
    explanation: "Bilješke navode Sphinx, Dr. Explain i PHPDocumentator kao dodatne alate.",
  }),
];
